/**
 * Dosagens — Cálculo Rápido
 * Medicamentos pediátricos mais usados no plantão, com dados estruturados para cálculo por peso.
 * dose_mgkg: dose em mg/kg/dose (ou por dia — ver freq)
 * freq: intervalo em horas (ex: 8 = a cada 8h)
 * dose_min / dose_max: em mg/kg/dose
 * dose_max_abs: dose máxima absoluta em mg/dose
 * apresentacoes: lista de apresentações disponíveis com concentração
 */

export const DOSAGENS_CATEGORIAS = [
  {
    id: 'antitermicos-analgesicos',
    label: 'Antitérmicos e Analgésicos',
    icon: '🌡️',
    color: 'orange',
    drugs: [
      {
        id: 'paracetamol',
        name: 'Paracetamol',
        sinonimo: 'Acetaminofeno',
        marcas: 'Tylenol, Tyflen, Cimegripe',
        via: 'VO/PR',
        dose_min: 10,
        dose_max: 15,
        dose_max_abs: 1000,
        dose_dia_max: 75,
        freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Máx 4 g/dia em adultos. Mínimo 4–6h entre doses. Hepatotóxico em doses altas.',
        apresentacoes: [
          { label: 'Gotas 200 mg/mL (10 mg/gota)', conc: 200, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Suspensão 100 mg/mL (Bebê)', conc: 100, tipo: 'mL' },
          { label: 'Suspensão 32 mg/mL (Criança)', conc: 32, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Comprimido 750 mg', conc: 750, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'ibuprofeno',
        name: 'Ibuprofeno',
        sinonimo: null,
        marcas: 'Alivium, Dalsy, Advil, Motrin',
        via: 'VO',
        dose_min: 5,
        dose_max: 10,
        dose_max_abs: 800,
        dose_dia_max: 40,
        freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Febre alta: 10 mg/kg/dose. Febre baixa: 5 mg/kg/dose. Máx 40 mg/kg/dia.',
        apresentacoes: [
          { label: 'Gotas 50 mg/mL (1 gota = 2,5 mg)', conc: 50, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Gotas 100 mg/mL (1 gota = 5 mg)', conc: 100, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Suspensão 100 mg/5 mL (20 mg/mL)', conc: 20, tipo: 'mL' },
          { label: 'Comprimido 200 mg', conc: 200, tipo: 'comprimido' },
          { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Comprimido 600 mg', conc: 600, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue. Evitar em < 6 meses.',
      },
      {
        id: 'dipirona',
        name: 'Dipirona',
        sinonimo: 'Metamizol',
        marcas: 'Novalgina, Anador, Alivdip',
        via: 'VO/EV/IM',
        dose_min: 10,
        dose_max: 15,
        dose_max_abs: 1000,
        dose_dia_max: 50,
        freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'VO: gotas 500 mg/mL = 0,4–0,6 gota/kg/dose. EV: 0,03 mL/kg/dose da ampola 500 mg/mL.',
        apresentacoes: [
          { label: 'Gotas 500 mg/mL (25 mg/gota)', conc: 500, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Solução oral 50 mg/mL', conc: 50, tipo: 'mL' },
          { label: 'Ampola 500 mg/mL (EV/IM)', conc: 500, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Não usar em < 3 meses ou < 5 kg. Raro mas grave: agranulocitose.',
      },
    ],
  },
  {
    id: 'antibioticos-orais',
    label: 'Antibióticos Orais',
    icon: '💊',
    color: 'red',
    drugs: [
      {
        id: 'amoxicilina',
        name: 'Amoxicilina',
        sinonimo: null,
        marcas: 'Amoxil, Clavulin (com clavulanato)',
        via: 'VO',
        dose_min: 25,
        dose_max: 50,
        dose_max_abs: 500,
        dose_dia_max: 90,
        freq: 8,
        unidade: 'mg/kg/dia ÷ 3 doses',
        obs: 'Otite/sinusite: 40–90 mg/kg/dia. Faringite: 50 mg/kg/dia. Pneumonia leve: 40–90 mg/kg/dia.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Suspensão 500 mg/5 mL (100 mg/mL)', conc: 100, tipo: 'mL' },
          { label: 'Cápsula 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 3,
      },
      {
        id: 'amoxicilina-clavulanato',
        name: 'Amoxicilina + Clavulanato',
        sinonimo: 'Amoxicilina/Ácido Clavulânico',
        marcas: 'Clavulin, Amoxicillin + Clavulanate',
        via: 'VO',
        dose_min: 25,
        dose_max: 45,
        dose_max_abs: 875,
        dose_dia_max: 90,
        freq: 8,
        unidade: 'mg/kg/dia (da amoxicilina) ÷ 3',
        obs: 'Otite/sinusite resistente: 40–90 mg/kg/dia. Suspensão 400/57 mg/5 mL — calcular pela amoxicilina.',
        apresentacoes: [
          { label: 'Suspensão 250/62,5 mg/5 mL (50 mg/mL amox)', conc: 50, tipo: 'mL' },
          { label: 'Suspensão 400/57 mg/5 mL (80 mg/mL amox)', conc: 80, tipo: 'mL' },
          { label: 'Comp. 500/125 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Comp. 875/125 mg', conc: 875, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 3,
      },
      {
        id: 'azitromicina',
        name: 'Azitromicina',
        sinonimo: null,
        marcas: 'Zithromax, Azitro, Astro',
        via: 'VO',
        dose_min: 10,
        dose_max: 10,
        dose_max_abs: 500,
        dose_dia_max: 10,
        freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Dose única diária por 3 dias (ou 5 dias em pneumonia). Faringite: 12 mg/kg/dia × 5 dias.',
        apresentacoes: [
          { label: 'Suspensão 200 mg/5 mL (40 mg/mL)', conc: 40, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 1,
      },
      {
        id: 'claritromicina',
        name: 'Claritromicina',
        sinonimo: null,
        marcas: 'Klaricid, Claritrox',
        via: 'VO',
        dose_min: 7.5,
        dose_max: 15,
        dose_max_abs: 500,
        dose_dia_max: 15,
        freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Dose usual: 15 mg/kg/dia ÷ 2 doses por 7–14 dias.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 2,
      },
      {
        id: 'cefalexina',
        name: 'Cefalexina',
        sinonimo: null,
        marcas: 'Keflex, Cefalexin',
        via: 'VO',
        dose_min: 25,
        dose_max: 50,
        dose_max_abs: 500,
        dose_dia_max: 100,
        freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'Piodermite: 25–50 mg/kg/dia ÷ 3–4 doses. Infecção grave: 100 mg/kg/dia. Máx 4 g/dia.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 4,
      },
      {
        id: 'sulfametoxazol-trimetoprim',
        name: 'Sulfametoxazol + Trimetoprim',
        sinonimo: 'SMX/TMP — Cotrimoxazol',
        marcas: 'Bactrim, Bactelan, Infectrin',
        via: 'VO',
        dose_min: 6,
        dose_max: 12,
        dose_max_abs: 960,
        dose_dia_max: 12,
        freq: 12,
        unidade: 'mg/kg/dia (de TMP) ÷ 2',
        obs: 'Calcular pela fração TMP (20% da dose total). Suspensão 40 mg TMP/5 mL. ITU: 5–6 mg/kg/dia de TMP.',
        apresentacoes: [
          { label: 'Suspensão 200/40 mg/5 mL (8 mg TMP/mL)', conc: 8, tipo: 'mL' },
          { label: 'Comp. 400/80 mg', conc: 80, tipo: 'comprimido' },
          { label: 'Comp. Forte 800/160 mg', conc: 160, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Calcular a dose pelo componente TMP. Contraindicado < 2 meses.',
        dose_por_dia: true,
        doses_por_dia: 2,
      },
      {
        id: 'nitrofurantoina',
        name: 'Nitrofurantoína',
        sinonimo: null,
        marcas: 'Macrobid, Macrodantina',
        via: 'VO',
        dose_min: 5,
        dose_max: 7,
        dose_max_abs: 100,
        dose_dia_max: 7,
        freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'ITU baixa não complicada. Usar com alimento. Profilaxia: 1–2 mg/kg/dia, 1×/dia.',
        apresentacoes: [
          { label: 'Cápsula 100 mg (macrocristal)', conc: 100, tipo: 'comprimido' },
          { label: 'Suspensão 25 mg/5 mL (5 mg/mL)', conc: 5, tipo: 'mL' },
        ],
        alerta: '⚠️ Evitar em < 3 meses e insuficiência renal (ClCr < 45 mL/min).',
        dose_por_dia: true,
        doses_por_dia: 4,
      },
    ],
  },
  {
    id: 'antibioticos-parenterais',
    label: 'Antibióticos Parenterais',
    icon: '💉',
    color: 'purple',
    drugs: [
      {
        id: 'ceftriaxona',
        name: 'Ceftriaxona',
        sinonimo: null,
        marcas: 'Rocefin, Triaxon, Triaxin',
        via: 'EV/IM',
        dose_min: 50,
        dose_max: 100,
        dose_max_abs: 2000,
        dose_dia_max: 100,
        freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Meningite: 100 mg/kg/dia ÷ 1–2. Sepse grave: 100 mg/kg/dia. Fr-amp 500 mg e 1000 mg.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg (diluir em 5–10 mL)', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg (diluir em 10 mL)', conc: 1000, tipo: 'frasco' },
        ],
        alerta: '⚠️ Não infundir com soluções contendo cálcio. Evitar em RN ictérico.',
        dose_por_dia: true,
        doses_por_dia: 1,
      },
      {
        id: 'cefazolina',
        name: 'Cefazolina',
        sinonimo: null,
        marcas: 'Cezolin, Fazolon',
        via: 'EV/IM',
        dose_min: 25,
        dose_max: 50,
        dose_max_abs: 2000,
        dose_dia_max: 100,
        freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Infecções graves: 100 mg/kg/dia. Profilaxia cirúrgica: 50 mg/kg 30–60 min antes.',
        apresentacoes: [
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 3,
      },
      {
        id: 'ampicilina',
        name: 'Ampicilina',
        sinonimo: null,
        marcas: 'Binotal, Ampicilina sódica',
        via: 'EV/IM',
        dose_min: 100,
        dose_max: 200,
        dose_max_abs: 2000,
        dose_dia_max: 400,
        freq: 6,
        unidade: 'mg/kg/dia ÷ 4–6',
        obs: 'Meningite: 200–400 mg/kg/dia. Neonatos: 50 mg/kg/dose × 2–4/dia.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 4,
      },
      {
        id: 'oxacilina',
        name: 'Oxacilina',
        sinonimo: null,
        marcas: 'Oxacilina sódica',
        via: 'EV',
        dose_min: 100,
        dose_max: 200,
        dose_max_abs: 2000,
        dose_dia_max: 200,
        freq: 4,
        unidade: 'mg/kg/dia ÷ 6',
        obs: 'Estafilococos sensíveis. Infecção grave: 200 mg/kg/dia. Fr. amp. 500 mg e 1 g.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 6,
      },
      {
        id: 'vancomicina',
        name: 'Vancomicina',
        sinonimo: null,
        marcas: 'Vancocin, Vancomicina',
        via: 'EV',
        dose_min: 40,
        dose_max: 60,
        dose_max_abs: 2000,
        dose_dia_max: 60,
        freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'MRSA / enterococo. Infundir em ≥ 60 min. Monitorar nível sérico. Neonatos: 15 mg/kg/dose × 2–3.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: '⚠️ Síndrome do homem vermelho se infusão rápida. Nefrotóxico. Monitorar nível sérico.',
        dose_por_dia: true,
        doses_por_dia: 4,
      },
      {
        id: 'gentamicina',
        name: 'Gentamicina',
        sinonimo: null,
        marcas: 'Garamicina, Gentamicina',
        via: 'EV/IM',
        dose_min: 5,
        dose_max: 7.5,
        dose_max_abs: 300,
        dose_dia_max: 7.5,
        freq: 24,
        unidade: 'mg/kg/dia (1×/dia)',
        obs: 'Dose única diária preferida (exceto neonatos). Monitorar função renal e nível sérico.',
        apresentacoes: [
          { label: 'Ampola 40 mg/mL (2 mL = 80 mg)', conc: 40, tipo: 'mL' },
          { label: 'Ampola 10 mg/mL (neonatos)', conc: 10, tipo: 'mL' },
        ],
        alerta: '⚠️ Nefrotóxico e ototóxico. Monitorar nível sérico em uso prolongado.',
        dose_por_dia: true,
        doses_por_dia: 1,
      },
    ],
  },
  {
    id: 'broncodilatadores-corticoides',
    label: 'Broncodilatadores e Corticoides',
    icon: '🫁',
    color: 'blue',
    drugs: [
      {
        id: 'salbutamol',
        name: 'Salbutamol',
        sinonimo: 'Albuterol',
        marcas: 'Aerolin, Airomir, Salbutamol',
        via: 'Inalatório / EV',
        dose_min: 0.15,
        dose_max: 0.3,
        dose_max_abs: 5,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose (nebulização)',
        obs: 'Nebulização: 0,15 mg/kg/dose (mín 2,5 mg, máx 5 mg) em 3 mL SF. A cada 20 min nas crises. MDI: 4–8 jatos + espaçador.',
        apresentacoes: [
          { label: 'Nebulização 0,5% = 5 mg/mL', conc: 5, tipo: 'mL' },
          { label: 'MDI 100 mcg/jato (aerossol)', conc: 0.1, tipo: 'jatos' },
        ],
        alerta: null,
      },
      {
        id: 'prednisolona',
        name: 'Prednisolona',
        sinonimo: null,
        marcas: 'Predsim, Prelone, Meticorten (prednisona)',
        via: 'VO',
        dose_min: 1,
        dose_max: 2,
        dose_max_abs: 60,
        dose_dia_max: 2,
        freq: 24,
        unidade: 'mg/kg/dia (1×/dia)',
        obs: 'Asma moderada/grave: 1–2 mg/kg/dia (máx 60 mg/dia) por 3–5 dias. Crup: 0,6 mg/kg dose única.',
        apresentacoes: [
          { label: 'Suspensão 3 mg/mL', conc: 3, tipo: 'mL' },
          { label: 'Comprimido 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Comprimido 20 mg', conc: 20, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 1,
      },
      {
        id: 'dexametasona',
        name: 'Dexametasona',
        sinonimo: null,
        marcas: 'Decadron, Dexametasona',
        via: 'VO/EV/IM',
        dose_min: 0.15,
        dose_max: 0.6,
        dose_max_abs: 10,
        dose_dia_max: 0.6,
        freq: 24,
        unidade: 'mg/kg/dose',
        obs: 'Crup: 0,15–0,6 mg/kg dose única VO/IM. Meningite: 0,15 mg/kg/dose × 4/dia por 2 dias. Anafilaxia: 0,15 mg/kg EV.',
        apresentacoes: [
          { label: 'Ampola 4 mg/mL (EV/IM)', conc: 4, tipo: 'mL' },
          { label: 'Comprimido 0,5 mg', conc: 0.5, tipo: 'comprimido' },
          { label: 'Comprimido 4 mg', conc: 4, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'hidrocortisona',
        name: 'Hidrocortisona',
        sinonimo: null,
        marcas: 'Solu-Cortef, Flebocortid',
        via: 'EV/IM',
        dose_min: 1,
        dose_max: 10,
        dose_max_abs: 500,
        dose_dia_max: 10,
        freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Asma grave: 5–10 mg/kg/dose EV × 4/dia. Insuf. adrenal aguda: 50–100 mg/m² dose de ataque EV.',
        apresentacoes: [
          { label: 'Fr. amp. 100 mg', conc: 100, tipo: 'frasco' },
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
        ],
        alerta: null,
      },
    ],
  },
  {
    id: 'anticonvulsivantes',
    label: 'Anticonvulsivantes',
    icon: '⚡',
    color: 'yellow',
    drugs: [
      {
        id: 'diazepam',
        name: 'Diazepam',
        sinonimo: null,
        marcas: 'Valium, Diazepam',
        via: 'EV/Retal',
        dose_min: 0.2,
        dose_max: 0.5,
        dose_max_abs: 10,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Convulsão: 0,2–0,5 mg/kg EV lento (máx 10 mg) ou 0,5 mg/kg retal. Pode repetir 1× após 5–10 min.',
        apresentacoes: [
          { label: 'Ampola 5 mg/mL (2 mL = 10 mg)', conc: 5, tipo: 'mL' },
          { label: 'Solução retal 5 mg/2,5 mL', conc: 2, tipo: 'mL' },
        ],
        alerta: '⚠️ Infundir lentamente (< 5 mg/min). Monitorar respiração.',
      },
      {
        id: 'midazolam',
        name: 'Midazolam',
        sinonimo: null,
        marcas: 'Dormonid, Midazolam',
        via: 'EV/IM/Intranasal',
        dose_min: 0.1,
        dose_max: 0.3,
        dose_max_abs: 10,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Convulsão: 0,1–0,3 mg/kg EV/IM (máx 10 mg). Intranasal: 0,2 mg/kg (0,1 mL/narina). Sedação: 0,05–0,1 mg/kg EV.',
        apresentacoes: [
          { label: 'Ampola 5 mg/mL (5 mL = 25 mg)', conc: 5, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar respiração e PA. Ter flumazenil disponível.',
      },
      {
        id: 'fenobarbital',
        name: 'Fenobarbital',
        sinonimo: null,
        marcas: 'Gardenal, Fenocris',
        via: 'EV/VO',
        dose_min: 15,
        dose_max: 20,
        dose_max_abs: 1000,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg (ataque EV)',
        obs: 'Status epilepticus — ataque: 15–20 mg/kg EV lento (1 mg/kg/min). Manutenção VO: 3–5 mg/kg/dia × 1–2/dia.',
        apresentacoes: [
          { label: 'Ampola 100 mg/mL (EV)', conc: 100, tipo: 'mL' },
          { label: 'Comprimido 100 mg (VO)', conc: 100, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Infusão lenta (1 mg/kg/min). Risco de apneia e hipotensão.',
      },
    ],
  },
  {
    id: 'antialergicos',
    label: 'Anti-histamínicos e Antialérgicos',
    icon: '🌿',
    color: 'green',
    drugs: [
      {
        id: 'loratadina',
        name: 'Loratadina',
        sinonimo: null,
        marcas: 'Claritin, Loratadina',
        via: 'VO',
        dose_min: 0.2,
        dose_max: 0.2,
        dose_max_abs: 10,
        dose_dia_max: 0.2,
        freq: 24,
        unidade: 'mg/kg/dia',
        obs: '< 30 kg: 5 mg/dia. ≥ 30 kg: 10 mg/dia. 1×/dia.',
        apresentacoes: [
          { label: 'Xarope 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 1,
      },
      {
        id: 'cetirizina',
        name: 'Cetirizina',
        sinonimo: null,
        marcas: 'Zyrtec, Cetrizin',
        via: 'VO',
        dose_min: 0.25,
        dose_max: 0.25,
        dose_max_abs: 10,
        dose_dia_max: 0.25,
        freq: 24,
        unidade: 'mg/kg/dia',
        obs: '< 15 kg: 2,5 mg/dia. 15–30 kg: 5 mg/dia. > 30 kg: 10 mg/dia. 1×/dia (ou ÷ 2 doses em < 6 anos).',
        apresentacoes: [
          { label: 'Xarope 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 1,
      },
      {
        id: 'prometazina',
        name: 'Prometazina',
        sinonimo: null,
        marcas: 'Fenergan, Prometazina',
        via: 'VO/EV/IM',
        dose_min: 0.5,
        dose_max: 1,
        dose_max_abs: 25,
        dose_dia_max: 1,
        freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Alergia grave/anafilaxia: 0,5–1 mg/kg EV/IM. Sedação: 0,5 mg/kg VO. Máx 25 mg/dose.',
        apresentacoes: [
          { label: 'Ampola 25 mg/mL (EV/IM)', conc: 25, tipo: 'mL' },
          { label: 'Xarope 5 mg/5 mL (1 mg/mL)', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 25 mg', conc: 25, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Evitar em < 2 anos (risco de apneia). Sedativo.',
      },
      {
        id: 'adrenalina',
        name: 'Adrenalina',
        sinonimo: 'Epinefrina',
        marcas: 'Adrenalina, EpiPen',
        via: 'IM/EV/Inalatório',
        dose_min: 0.01,
        dose_max: 0.01,
        dose_max_abs: 0.5,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose IM (1:1000)',
        obs: 'Anafilaxia IM: 0,01 mg/kg da solução 1:1000 (máx 0,5 mg). Pode repetir a cada 5–15 min. Crup: nebulização 0,5 mL/kg (máx 4 mL) da solução 1:1000.',
        apresentacoes: [
          { label: 'Ampola 1 mg/mL (1:1000)', conc: 1, tipo: 'mL' },
          { label: 'Ampola 0,1 mg/mL (1:10.000 — EV PCR)', conc: 0.1, tipo: 'mL' },
        ],
        alerta: '🚨 Anafilaxia: via IM (face anterolateral da coxa). Monitorar FC e PA.',
      },
    ],
  },
  {
    id: 'gastro',
    label: 'Gastrointestinal',
    icon: '🫃',
    color: 'teal',
    drugs: [
      {
        id: 'ondansetrona',
        name: 'Ondansetrona',
        sinonimo: null,
        marcas: 'Vonau, Zofran, Ondansetrona',
        via: 'VO/EV',
        dose_min: 0.1,
        dose_max: 0.15,
        dose_max_abs: 4,
        dose_dia_max: 0.15,
        freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Vômitos: 0,1–0,15 mg/kg/dose (máx 4 mg) VO ou EV a cada 8h. EV em 15 min.',
        apresentacoes: [
          { label: 'Ampola 2 mg/mL (EV)', conc: 2, tipo: 'mL' },
          { label: 'Comprimido 4 mg', conc: 4, tipo: 'comprimido' },
          { label: 'Comprimido 8 mg', conc: 8, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'domperidona',
        name: 'Domperidona',
        sinonimo: null,
        marcas: 'Motilium, Domperidona',
        via: 'VO',
        dose_min: 0.2,
        dose_max: 0.3,
        dose_max_abs: 10,
        dose_dia_max: 0.9,
        freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Refluxo/vômitos: 0,2–0,3 mg/kg/dose × 3/dia. Suspensão 1 mg/mL. Máx 10 mg/dose.',
        apresentacoes: [
          { label: 'Suspensão 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Risco de prolongamento QT. Usar menor dose e duração. Evitar em < 1 mês.',
      },
      {
        id: 'ranitidina',
        name: 'Ranitidina',
        sinonimo: null,
        marcas: 'Antak, Label',
        via: 'VO/EV',
        dose_min: 2,
        dose_max: 4,
        dose_max_abs: 150,
        dose_dia_max: 8,
        freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Refluxo/úlcera: 4–8 mg/kg/dia ÷ 2 doses. EV: 1–2 mg/kg/dose × 3–4/dia.',
        apresentacoes: [
          { label: 'Xarope 15 mg/mL', conc: 15, tipo: 'mL' },
          { label: 'Comprimido 150 mg', conc: 150, tipo: 'comprimido' },
          { label: 'Ampola 25 mg/mL (EV)', conc: 25, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 2,
      },
      {
        id: 'omeprazol',
        name: 'Omeprazol',
        sinonimo: null,
        marcas: 'Losec, Peprazol, Omeprazol',
        via: 'VO/EV',
        dose_min: 0.7,
        dose_max: 1,
        dose_max_abs: 20,
        dose_dia_max: 1,
        freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'DRGE/úlcera: 0,7–1 mg/kg/dia (máx 20 mg/dia). Tomar 30 min antes do café. EV: 0,5–1 mg/kg × 1–2/dia.',
        apresentacoes: [
          { label: 'Cápsula 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Cápsula 20 mg', conc: 20, tipo: 'comprimido' },
          { label: 'Fr. amp. 40 mg (EV)', conc: 40, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true,
        doses_por_dia: 1,
      },
    ],
  },
  {
    id: 'outros-emergencia',
    label: 'Outros / Emergência',
    icon: '🚨',
    color: 'red',
    drugs: [
      {
        id: 'morfina',
        name: 'Morfina',
        sinonimo: null,
        marcas: 'Dimorf, Morfina',
        via: 'EV/SC',
        dose_min: 0.05,
        dose_max: 0.1,
        dose_max_abs: 5,
        dose_dia_max: null,
        freq: 4,
        unidade: 'mg/kg/dose',
        obs: 'Dor moderada a grave: 0,05–0,1 mg/kg/dose EV lento a cada 4h. Neonatos: 0,05 mg/kg/dose.',
        apresentacoes: [
          { label: 'Ampola 10 mg/mL', conc: 10, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL (diluída)', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar respiração. Ter naloxona disponível.',
      },
      {
        id: 'atropina',
        name: 'Atropina',
        sinonimo: null,
        marcas: 'Atropina',
        via: 'EV/IM',
        dose_min: 0.01,
        dose_max: 0.02,
        dose_max_abs: 0.5,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Bradicardia: 0,01–0,02 mg/kg EV (mín 0,1 mg, máx 0,5 mg/dose). PCR: 0,02 mg/kg. Pode repetir 1× após 5 min.',
        apresentacoes: [
          { label: 'Ampola 0,5 mg/mL (EV/IM)', conc: 0.5, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '🚨 Dose mínima 0,1 mg (evitar bradicardia paradoxal).',
      },
      {
        id: 'furosemida',
        name: 'Furosemida',
        sinonimo: null,
        marcas: 'Lasix, Furosemida',
        via: 'EV/IM/VO',
        dose_min: 0.5,
        dose_max: 2,
        dose_max_abs: 40,
        dose_dia_max: 6,
        freq: 12,
        unidade: 'mg/kg/dose',
        obs: 'Edema / IRA: 0,5–2 mg/kg/dose EV × 1–2/dia. VO: 1–4 mg/kg/dia ÷ 1–2. Infundir lentamente.',
        apresentacoes: [
          { label: 'Ampola 10 mg/mL (2 mL = 20 mg)', conc: 10, tipo: 'mL' },
          { label: 'Comprimido 40 mg', conc: 40, tipo: 'comprimido' },
          { label: 'Solução oral 10 mg/mL', conc: 10, tipo: 'mL' },
        ],
        alerta: null,
      },
      {
        id: 'naloxona',
        name: 'Naloxona',
        sinonimo: null,
        marcas: 'Narcan, Naloxona',
        via: 'EV/IM/IN',
        dose_min: 0.01,
        dose_max: 0.1,
        dose_max_abs: 2,
        dose_dia_max: null,
        freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Reversão de opioides: 0,01–0,1 mg/kg EV/IM (máx 2 mg). Pode repetir a cada 2–3 min. Titular conforme resposta.',
        apresentacoes: [
          { label: 'Ampola 0,4 mg/mL', conc: 0.4, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Meia-vida curta — pode precisar repetir. Monitorar rebote de depressão respiratória.',
      },
    ],
  },
];

export function getAllDosagens() {
  return DOSAGENS_CATEGORIAS.flatMap(cat =>
    cat.drugs.map(d => ({ ...d, catLabel: cat.label, catColor: cat.color, catIcon: cat.icon, catId: cat.id }))
  );
}