// PARTE 2: Anti-inflamatórios, Antimicrobianos, Anti-Parasitários, Antitussígenos, Broncodilatadores

export const PART2_CATEGORIAS = [
  {
    id: 'antiinflamatorios',
    label: 'Anti-inflamatórios',
    icon: '🔥',
    color: 'red',
    drugs: [
      {
        id: 'diclofenaco',
        name: 'Diclofenaco',
        sinonimo: null,
        marcas: 'Voltaren, Cataflam',
        descricao: 'AINE indicado para dor e inflamação.',
        indicacoes: [
          {
            id: 'dor-inflamacao',
            label: 'Dor / Inflamação',
            dose_min: 1, dose_max: 1.5, dose_max_abs: 75,
            unidade: 'mg/kg/dia ÷ 3', freq: '8/8h',
            obs: 'Máx 150 mg/dia. IM: 75 mg dose única.',
            apresentacoes: [
              { label: 'Comprimido 25 mg', conc: 25, tipo: 'comprimido' },
              { label: 'Comprimido 50 mg', conc: 50, tipo: 'comprimido' },
              { label: 'Ampola 75 mg/3 mL (IM)', conc: 25, tipo: 'mL' },
            ],
          },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue.',
      },
      {
        id: 'nimesulida',
        name: 'Nimesulida',
        sinonimo: null,
        marcas: 'Nisulid, Scaflan',
        descricao: 'AINE inibidor seletivo de COX-2. Uso restrito em > 12 anos.',
        indicacoes: [
          {
            id: 'dor-inflamacao',
            label: 'Dor / Inflamação (≥ 12 anos)',
            dose_min: 1.5, dose_max: 3, dose_max_abs: 100,
            unidade: 'mg/kg/dose', freq: '12/12h',
            obs: 'Máx 100 mg/dose × 2/dia. Tomar após refeição.',
            apresentacoes: [
              { label: 'Comprimido 100 mg (≥12 anos)', conc: 100, tipo: 'comprimido', idade_min: 12 },
              { label: 'Suspensão 10 mg/mL (≥12 anos)', conc: 10, tipo: 'mL', idade_min: 12 },
            ],
          },
        ],
        alerta: '⚠️ Evitar em < 12 anos. Risco de hepatotoxicidade.',
      },
      {
        id: 'meloxicam',
        name: 'Meloxicam',
        sinonimo: null,
        marcas: 'Mobec, Melox',
        descricao: 'AINE inibidor preferencial de COX-2, indicado para artrite juvenil.',
        indicacoes: [
          {
            id: 'artrite',
            label: 'Artrite Juvenil / Dor',
            dose_min: 0.125, dose_max: 0.25, dose_max_abs: 15,
            unidade: 'mg/kg/dia', freq: '1x ao dia',
            obs: 'Máx 15 mg/dia.',
            apresentacoes: [
              { label: 'Comprimido 7,5 mg', conc: 7.5, tipo: 'comprimido' },
              { label: 'Comprimido 15 mg (≥15 anos)', conc: 15, tipo: 'comprimido', idade_min: 15 },
              { label: 'Suspensão 1,5 mg/mL', conc: 1.5, tipo: 'mL' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'naproxeno',
        name: 'Naproxeno',
        sinonimo: null,
        marcas: 'Flanax, Naprosyn',
        descricao: 'AINE de meia-vida longa indicado para artrite e dor.',
        indicacoes: [
          {
            id: 'artrite-dor',
            label: 'Artrite / Dor',
            dose_min: 5, dose_max: 10, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 2', freq: '12/12h',
            obs: 'Artrite juvenil: 10–20 mg/kg/dia. Máx 1.000 mg/dia.',
            apresentacoes: [
              { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
              { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
              { label: 'Suspensão 25 mg/mL', conc: 25, tipo: 'mL' },
            ],
          },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue.',
      },
    ],
  },

  {
    id: 'antimicrobianos',
    label: 'Antimicrobianos',
    icon: '💊',
    color: 'red',
    drugs: [
      {
        id: 'amoxicilina',
        name: 'Amoxicilina',
        sinonimo: null,
        marcas: 'Amoxil, Trimox',
        descricao: 'Antibiótico de amplo espectro da classe das penicilinas indicado para infecções bacterianas sensíveis.',
        indicacoes: [
          {
            id: 'otite',
            label: 'Otite Média Aguda',
            dose_min: 40, dose_max: 50, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 2–3', freq: '8/8h ou 12/12h',
            obs: 'Por 7–10 dias. Dose máxima: 500 mg/dose.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Suspensão 400 mg/5 mL (80 mg/mL)', conc: 80, tipo: 'mL' },
              { label: 'Suspensão 500 mg/5 mL (100 mg/mL)', conc: 100, tipo: 'mL' },
              { label: 'Cápsula 500 mg (≥40 kg)', conc: 500, tipo: 'comprimido', peso_min: 40 },
            ],
          },
          {
            id: 'faringite',
            label: 'Faringoamigdalite Bacteriana',
            dose_min: 40, dose_max: 50, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 2', freq: '12/12h',
            obs: 'Por 10 dias. Dose máxima: 500 mg/dose.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Suspensão 400 mg/5 mL (80 mg/mL)', conc: 80, tipo: 'mL' },
              { label: 'Cápsula 500 mg (≥40 kg)', conc: 500, tipo: 'comprimido', peso_min: 40 },
            ],
          },
          {
            id: 'pneumonia-leve',
            label: 'Pneumonia Comunitária (ambulatorial)',
            dose_min: 40, dose_max: 90, dose_max_abs: 1000,
            unidade: 'mg/kg/dia ÷ 3', freq: '8/8h',
            obs: 'Alta dose (90 mg/kg/dia) para resistência ao pneumococo.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Suspensão 400 mg/5 mL (80 mg/mL)', conc: 80, tipo: 'mL' },
              { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'amoxicilina-clavulanato',
        name: 'Amoxicilina + Clavulanato',
        sinonimo: 'Amoxicilina/Ácido Clavulânico',
        marcas: 'Clavulin, Augmentin',
        descricao: 'Penicilina com inibidor de beta-lactamase indicada para infecções resistentes à amoxicilina simples.',
        indicacoes: [
          {
            id: 'dose-padrao',
            label: 'Dose Padrão',
            dose_min: 25, dose_max: 45, dose_max_abs: 1000,
            unidade: 'mg/kg/dia (amox) ÷ 2', freq: '12/12h',
            obs: 'Calcular pela amoxicilina. Máx 2 g/dia. Por 7–14 dias.',
            apresentacoes: [
              { label: 'Suspensão 125+31,25 mg/5 mL (25 mg/mL amox)', conc: 25, tipo: 'mL' },
              { label: 'Suspensão 250+62,5 mg/5 mL (50 mg/mL amox)', conc: 50, tipo: 'mL' },
              { label: 'Suspensão 400+57 mg/5 mL (80 mg/mL amox)', conc: 80, tipo: 'mL' },
              { label: 'Comp. 500+125 mg (≥40 kg)', conc: 500, tipo: 'comprimido', peso_min: 40 },
              { label: 'Comp. 875+125 mg (≥50 kg)', conc: 875, tipo: 'comprimido', peso_min: 50 },
            ],
          },
          {
            id: 'dose-alta',
            label: 'Dose Alta (OMA resistente / Sinusite)',
            dose_min: 80, dose_max: 90, dose_max_abs: 2000,
            unidade: 'mg/kg/dia (amox) ÷ 2', freq: '12/12h',
            obs: 'Alta dose para OMA resistente ou sinusite grave. Máx 4 g/dia de amoxicilina.',
            apresentacoes: [
              { label: 'Suspensão 400+57 mg/5 mL (80 mg/mL amox)', conc: 80, tipo: 'mL' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'azitromicina',
        name: 'Azitromicina',
        sinonimo: null,
        marcas: 'Zithromax, Azitro',
        descricao: 'Macrolídeo indicado para infecções do trato respiratório, pele, otite média e DSTs.',
        indicacoes: [
          {
            id: 'respiratorio-pele',
            label: 'Infecções Respiratórias / Pele / OMA',
            dose_min: 5, dose_max: 10, dose_max_abs: 500,
            unidade: 'mg/kg/dia', freq: 'Dia 1: 10 mg/kg; dias 2–5: 5 mg/kg/dia',
            obs: 'Dose de ataque dia 1: 10 mg/kg. Manutenção dias 2–5: 5 mg/kg/dia. Máx 500 mg/dia.',
            apresentacoes: [
              { label: 'Suspensão 200 mg/5 mL (40 mg/mL)', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 500 mg (≥45 kg)', conc: 500, tipo: 'comprimido', peso_min: 45 },
            ],
          },
          {
            id: 'faringite',
            label: 'Faringoamigdalite',
            dose_min: 12, dose_max: 12, dose_max_abs: 500,
            unidade: 'mg/kg/dia', freq: '1x ao dia por 5 dias',
            obs: '12 mg/kg/dia × 5 dias. Máx 500 mg/dia.',
            apresentacoes: [
              { label: 'Suspensão 200 mg/5 mL (40 mg/mL)', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 500 mg (≥45 kg)', conc: 500, tipo: 'comprimido', peso_min: 45 },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'claritromicina',
        name: 'Claritromicina',
        sinonimo: null,
        marcas: 'Klaricid',
        descricao: 'Macrolídeo indicado para infecções do trato respiratório, pele e Helicobacter pylori.',
        indicacoes: [
          {
            id: 'dose-geral',
            label: 'Dose Geral',
            dose_min: 7.5, dose_max: 15, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 2', freq: '12/12h por 10–14 dias',
            obs: 'Máx 500 mg/dose.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
              { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'cefalexina',
        name: 'Cefalexina',
        sinonimo: null,
        marcas: 'Keflex',
        descricao: 'Cefalosporina de 1ª geração indicada para infecções de pele, partes moles e trato urinário.',
        indicacoes: [
          {
            id: 'pele',
            label: 'Infecção de Pele / Partes Moles',
            dose_min: 25, dose_max: 50, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 3–4', freq: '6/6h ou 8/8h',
            obs: 'Infecção grave: até 100 mg/kg/dia. Máx 4 g/dia.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
            ],
          },
          {
            id: 'itu',
            label: 'Infecção do Trato Urinário',
            dose_min: 50, dose_max: 100, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 3–4', freq: '8/8h por 7–10 dias',
            obs: 'ITU febril: até 100 mg/kg/dia. Máx 4 g/dia.',
            apresentacoes: [
              { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
              { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'ceftriaxona',
        name: 'Ceftriaxona',
        sinonimo: null,
        marcas: 'Rocefin, Triaxon',
        descricao: 'Cefalosporina de terceira geração com amplo espectro, indicada para infecções bacterianas graves.',
        indicacoes: [
          {
            id: 'dose-geral',
            label: 'Dose Geral',
            dose_min: 50, dose_max: 75, dose_max_abs: 2000,
            unidade: 'mg/kg/dia', freq: '12/12h ou 1x ao dia',
            obs: 'Máx 2 g/dia. Infundir em 30–60 min.',
            apresentacoes: [
              { label: 'Fr. amp. 500 mg (EV)', conc: 500, tipo: 'frasco' },
              { label: 'Fr. amp. 1000 mg (EV)', conc: 1000, tipo: 'frasco' },
              { label: 'Fr. amp. 500 mg (IM)', conc: 500, tipo: 'frasco' },
              { label: 'Fr. amp. 1000 mg (IM)', conc: 1000, tipo: 'frasco' },
            ],
          },
          {
            id: 'meningite',
            label: 'Meningite Bacteriana',
            dose_min: 80, dose_max: 100, dose_max_abs: 4000,
            unidade: 'mg/kg/dia ÷ 1–2', freq: '12/12h ou 1x ao dia',
            obs: 'Máx 4 g/dia. Associar ampicilina em < 3 meses.',
            apresentacoes: [
              { label: 'Fr. amp. 1000 mg (EV)', conc: 1000, tipo: 'frasco' },
            ],
          },
        ],
        alerta: '⚠️ Não infundir com soluções contendo cálcio. Evitar em RN ictérico.',
      },
      {
        id: 'vancomicina',
        name: 'Vancomicina',
        sinonimo: null,
        marcas: 'Vancocin',
        descricao: 'Glicopeptídeo indicado para infecções por MRSA e enterococos resistentes.',
        indicacoes: [
          {
            id: 'mrsa-neonatal',
            label: 'Infecção por MRSA — Neonatal (≤ 1 mês)',
            dose_min: 10, dose_max: 15, dose_max_abs: 500,
            unidade: 'mg/kg/dose', freq: '12/12h',
            obs: 'Dose ataque: 15 mg/kg. Manutenção: 10 mg/kg 12/12h por 4–7 dias.',
            apresentacoes: [
              { label: 'Pó injetável 500 mg (EV)', conc: 500, tipo: 'frasco' },
            ],
          },
          {
            id: 'mrsa-crianca',
            label: 'Infecção por MRSA — Criança',
            dose_min: 10, dose_max: 15, dose_max_abs: 750,
            unidade: 'mg/kg/dose', freq: '6/6h',
            obs: '40–60 mg/kg/dia ÷ 4. Infundir em ≥ 60 min. Monitorar nível sérico.',
            apresentacoes: [
              { label: 'Pó injetável 500 mg (EV)', conc: 500, tipo: 'frasco' },
              { label: 'Pó injetável 1000 mg (EV)', conc: 1000, tipo: 'frasco' },
            ],
          },
        ],
        alerta: '⚠️ Síndrome do homem vermelho se infusão rápida. Nefrotóxico. Monitorar nível sérico.',
      },
      {
        id: 'sulfametoxazol-tmp',
        name: 'Sulfametoxazol + Trimetoprim',
        sinonimo: 'SMX/TMP — Cotrimoxazol',
        marcas: 'Bactrim, Bactelan',
        descricao: 'Sulfonamida potencializada indicada para ITU, pneumocistose e outras infecções.',
        indicacoes: [
          {
            id: 'itu',
            label: 'Infecção do Trato Urinário',
            dose_min: 5, dose_max: 6, dose_max_abs: 160,
            unidade: 'mg/kg/dia de TMP ÷ 2', freq: '12/12h por 7–10 dias',
            obs: 'Calcular pelo TMP. Máx 160 mg TMP/dose.',
            apresentacoes: [
              { label: 'Suspensão 200+40 mg/5 mL (8 mg TMP/mL)', conc: 8, tipo: 'mL' },
              { label: 'Comp. 400+80 mg (80 mg TMP)', conc: 80, tipo: 'comprimido' },
              { label: 'Comp. Forte 800+160 mg (160 mg TMP)', conc: 160, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: '⚠️ Contraindicado < 2 meses. Calcular pelo componente TMP.',
      },
      {
        id: 'metronidazol',
        name: 'Metronidazol',
        sinonimo: null,
        marcas: 'Flagyl',
        descricao: 'Antibiótico e antiprotozoário com ação contra anaeróbios, Giardia e Entamoeba.',
        indicacoes: [
          {
            id: 'giardíase',
            label: 'Giardíase',
            dose_min: 15, dose_max: 20, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 3', freq: '8/8h por 5–7 dias',
            obs: 'Amebíase: 35–50 mg/kg/dia ÷ 3 por 7–10 dias.',
            apresentacoes: [
              { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
              { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
              { label: 'Ampola 500 mg/100 mL (EV)', conc: 5, tipo: 'mL' },
            ],
          },
          {
            id: 'anaerobios',
            label: 'Infecções por Anaeróbios',
            dose_min: 15, dose_max: 35, dose_max_abs: 500,
            unidade: 'mg/kg/dia ÷ 3', freq: '8/8h',
            obs: 'Infecções anaeróbias graves: 35 mg/kg/dia ÷ 3. Máx 500 mg/dose.',
            apresentacoes: [
              { label: 'Ampola 500 mg/100 mL (EV)', conc: 5, tipo: 'mL' },
              { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'nitazoxanida',
        name: 'Nitazoxanida',
        sinonimo: null,
        marcas: 'Anitta, Annita',
        descricao: 'Antiparasitário de amplo espectro indicado para giardíase e criptosporidiose.',
        indicacoes: [
          {
            id: 'giardia-crypto',
            label: 'Giardíase / Criptosporidiose',
            dose_min: 7.5, dose_max: 7.5, dose_max_abs: 500,
            unidade: 'mg/kg/dose', freq: '12/12h por 3 dias',
            obs: '1–3a: 100 mg × 2/dia. 4–11a: 200 mg × 2/dia. > 12a: 500 mg × 2/dia.',
            apresentacoes: [
              { label: 'Suspensão 20 mg/mL', conc: 20, tipo: 'mL' },
              { label: 'Comprimido 500 mg (≥12 anos)', conc: 500, tipo: 'comprimido', idade_min: 12 },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'aciclovir',
        name: 'Aciclovir',
        sinonimo: null,
        marcas: 'Zovirax',
        descricao: 'Antiviral indicado para herpes simples, varicela-zóster e encefalite herpética.',
        indicacoes: [
          {
            id: 'varicela',
            label: 'Varicela (VO)',
            dose_min: 20, dose_max: 20, dose_max_abs: 800,
            unidade: 'mg/kg/dose', freq: '4 vezes ao dia por 5 dias',
            obs: 'Máx 800 mg/dose. Iniciar nas primeiras 24h de lesões.',
            apresentacoes: [
              { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 200 mg', conc: 200, tipo: 'comprimido' },
              { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
            ],
          },
          {
            id: 'encefalite',
            label: 'Encefalite Herpética (EV)',
            dose_min: 10, dose_max: 20, dose_max_abs: 800,
            unidade: 'mg/kg/dose', freq: '8/8h por 14–21 dias',
            obs: 'Infundir em 1h. Hidratação adequada (nefrotóxico).',
            apresentacoes: [
              { label: 'Fr. amp. 250 mg (EV)', conc: 250, tipo: 'frasco' },
              { label: 'Fr. amp. 500 mg (EV)', conc: 500, tipo: 'frasco' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'oseltamivir',
        name: 'Oseltamivir',
        sinonimo: 'Tamiflu',
        marcas: 'Tamiflu',
        descricao: 'Antiviral inibidor de neuraminidase para tratamento e profilaxia da Influenza.',
        indicacoes: [
          {
            id: 'influenza',
            label: 'Influenza — Tratamento',
            dose_min: 3, dose_max: 3.5, dose_max_abs: 75,
            unidade: 'mg/kg/dia ÷ 2 por 5 dias', freq: '12/12h por 5 dias',
            obs: '≤15 kg: 30 mg 12/12h. 16–23 kg: 45 mg. 24–40 kg: 60 mg. >40 kg: 75 mg.',
            apresentacoes: [
              { label: 'Suspensão 6 mg/mL', conc: 6, tipo: 'mL' },
              { label: 'Cápsula 30 mg', conc: 30, tipo: 'comprimido' },
              { label: 'Cápsula 45 mg', conc: 45, tipo: 'comprimido' },
              { label: 'Cápsula 75 mg (≥40 kg)', conc: 75, tipo: 'comprimido', peso_min: 40 },
            ],
          },
        ],
        alerta: null,
      },
    ],
  },

  {
    id: 'antiparasitarios',
    label: 'Anti-Parasitários',
    icon: '🪱',
    color: 'lime',
    drugs: [
      {
        id: 'albendazol',
        name: 'Albendazol',
        sinonimo: null,
        marcas: 'Zentel',
        descricao: 'Anti-helmíntico de amplo espectro indicado para enterobíase, ascaridíase e outras helmintíases.',
        indicacoes: [
          {
            id: 'enterobiase',
            label: 'Enterobíase (Oxiúros)',
            dose_min: 400, dose_max: 400, dose_max_abs: 400,
            unidade: 'mg — dose única', freq: 'Dose única. Repetir em 2 semanas.',
            obs: '> 2 anos: 400 mg dose única. < 2 anos: 200 mg.',
            apresentacoes: [
              { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 400 mg mastigável', conc: 400, tipo: 'comprimido' },
            ],
          },
          {
            id: 'ascaridiase',
            label: 'Ascaridíase / Ancilostomíase',
            dose_min: 400, dose_max: 400, dose_max_abs: 400,
            unidade: 'mg — dose única', freq: 'Dose única.',
            obs: '> 2 anos: 400 mg dose única. Giardíase: 400 mg 1×/dia × 3–5 dias.',
            apresentacoes: [
              { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
              { label: 'Comprimido 400 mg mastigável', conc: 400, tipo: 'comprimido' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'mebendazol',
        name: 'Mebendazol',
        sinonimo: null,
        marcas: 'Pantelmin',
        descricao: 'Anti-helmíntico indicado para ancilostomíase, tricuríase, enterobíase e ascaridíase.',
        indicacoes: [
          {
            id: 'oxiuros',
            label: 'Enterobíase (Oxiúros)',
            dose_min: 100, dose_max: 100, dose_max_abs: 100,
            unidade: 'mg — dose única', freq: 'Dose única. Repetir em 2–3 semanas.',
            obs: '100 mg dose única (independente do peso). Repetir em 2–3 semanas.',
            apresentacoes: [
              { label: 'Comprimido 100 mg', conc: 100, tipo: 'comprimido' },
              { label: 'Suspensão 20 mg/mL', conc: 20, tipo: 'mL' },
            ],
          },
          {
            id: 'ascaridiase',
            label: 'Ancilostomíase / Ascaridíase',
            dose_min: 100, dose_max: 100, dose_max_abs: 100,
            unidade: 'mg/dose', freq: '12/12h por 3 dias',
            obs: '100 mg × 2/dia × 3 dias (independente do peso).',
            apresentacoes: [
              { label: 'Comprimido 100 mg', conc: 100, tipo: 'comprimido' },
              { label: 'Suspensão 20 mg/mL', conc: 20, tipo: 'mL' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'ivermectina',
        name: 'Ivermectina',
        sinonimo: null,
        marcas: 'Revectina',
        descricao: 'Anti-helmíntico e antiparasitário indicado para sarna, estrongiloidíase e ascaridíase.',
        indicacoes: [
          {
            id: 'ascaridiase',
            label: 'Ascaridíase',
            dose_min: 0.2, dose_max: 0.2, dose_max_abs: 12,
            unidade: 'mg/kg/dose', freq: 'Dose única',
            obs: '0,2 mg/kg dose única. Apenas > 15 kg. Tomar em jejum.',
            apresentacoes: [
              { label: 'Comprimido 6 mg (> 15 kg)', conc: 6, tipo: 'comprimido', peso_min: 15 },
            ],
          },
          {
            id: 'sarna',
            label: 'Escabiose (Sarna)',
            dose_min: 0.2, dose_max: 0.2, dose_max_abs: 12,
            unidade: 'mg/kg/dose', freq: 'Dose única. Repetir em 1–2 semanas.',
            obs: '0,2 mg/kg dose única. Apenas > 15 kg.',
            apresentacoes: [
              { label: 'Comprimido 6 mg (> 15 kg)', conc: 6, tipo: 'comprimido', peso_min: 15 },
            ],
          },
        ],
        alerta: '⚠️ Contraindicado em < 15 kg.',
      },
    ],
  },

  {
    id: 'antitussigenos',
    label: 'Antitussígenos',
    icon: '🤧',
    color: 'cyan',
    drugs: [
      {
        id: 'ambroxol',
        name: 'Ambroxol',
        sinonimo: null,
        marcas: 'Mucosolvan, Ambrex',
        descricao: 'Mucolítico e expectorante que facilita a eliminação do muco brônquico.',
        indicacoes: [
          {
            id: 'mucolitico',
            label: 'Mucolítico',
            dose_min: 0.6, dose_max: 1.2, dose_max_abs: 30,
            unidade: 'mg/kg/dose', freq: '8/8h',
            obs: '2–5a: 7,5 mg × 2–3/dia. 6–12a: 15 mg × 3/dia. > 12a: 30 mg × 3/dia.',
            apresentacoes: [
              { label: 'Xarope 3 mg/mL (15 mg/5 mL)', conc: 3, tipo: 'mL' },
              { label: 'Xarope 6 mg/mL (30 mg/5 mL)', conc: 6, tipo: 'mL' },
              { label: 'Gotas 7,5 mg/mL', conc: 7.5, tipo: 'mL' },
              { label: 'Solução inalatória 7,5 mg/mL', conc: 7.5, tipo: 'mL' },
              { label: 'Comprimido 30 mg (≥12 anos)', conc: 30, tipo: 'comprimido', idade_min: 12 },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'acetilcisteina',
        name: 'Acetilcisteína',
        sinonimo: 'NAC',
        marcas: 'Fluimucil',
        descricao: 'Mucolítico e antídoto do paracetamol.',
        indicacoes: [
          {
            id: 'mucolitico',
            label: 'Mucolítico',
            dose_min: 10, dose_max: 15, dose_max_abs: 600,
            unidade: 'mg/kg/dia ÷ 2–3', freq: '8/8h ou 12/12h',
            obs: '2–6a: 100 mg × 3/dia. 7–14a: 200 mg × 3/dia. ≥14a: 200–600 mg/dia.',
            apresentacoes: [
              { label: 'Sachê 200 mg', conc: 200, tipo: 'comprimido' },
              { label: 'Sachê 600 mg (≥14 anos)', conc: 600, tipo: 'comprimido', idade_min: 14 },
            ],
          },
        ],
        alerta: null,
      },
    ],
  },

  {
    id: 'broncodilatadores',
    label: 'Broncodilatadores',
    icon: '🫁',
    color: 'blue',
    drugs: [
      {
        id: 'salbutamol',
        name: 'Salbutamol',
        sinonimo: 'Albuterol',
        marcas: 'Aerolin, Airomir',
        descricao: 'Broncodilatador beta-2 agonista de ação curta indicado para broncoespasmo agudo.',
        indicacoes: [
          {
            id: 'broncoespasmo',
            label: 'Broncoespasmo Agudo',
            dose_min: 0.15, dose_max: 0.15, dose_max_abs: 5,
            unidade: 'mg/kg/dose (nebulização)', freq: 'A cada 20 min na 1ª hora; depois 6/6h–8/8h',
            obs: 'Mín 2,5 mg, máx 5 mg. Diluir em SF até 3–4 mL. MDI: 2–4 jatos.',
            apresentacoes: [
              { label: 'Sol. nebulização 5 mg/mL', conc: 5, tipo: 'mL' },
              { label: 'Spray (MDI) 100 mcg/jato', conc: 0.1, tipo: 'jatos' },
              { label: 'Xarope 0,4 mg/mL (2 mg/5 mL)', conc: 0.4, tipo: 'mL' },
              { label: 'Sol. injetável 0,5 mg/mL (EV)', conc: 0.5, tipo: 'mL' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'fenoterol',
        name: 'Fenoterol',
        sinonimo: null,
        marcas: 'Berotec',
        descricao: 'Broncodilatador beta-2 agonista de ação curta.',
        indicacoes: [
          {
            id: 'broncoespasmo',
            label: 'Broncoespasmo Agudo',
            dose_min: 0.05, dose_max: 0.1, dose_max_abs: 5,
            unidade: 'mg/kg/dose (nebulização)', freq: 'A cada 20 min; depois 6/6h–8/8h',
            obs: 'Mín 1,25 mg, máx 5 mg. MDI: 2–4 jatos 4/4h–6/6h.',
            apresentacoes: [
              { label: 'Sol. nebulização 5 mg/mL (gotas)', conc: 5, tipo: 'mL' },
              { label: 'Spray (MDI) 100 mcg/jato', conc: 0.1, tipo: 'jatos' },
            ],
          },
        ],
        alerta: null,
      },
      {
        id: 'ipratropio',
        name: 'Ipratrópio',
        sinonimo: null,
        marcas: 'Atrovent',
        descricao: 'Broncodilatador anticolinérgico. Associar ao beta-2 agonista nas crises de asma grave.',
        indicacoes: [
          {
            id: 'asma-grave',
            label: 'Asma Grave / Broncoespasmo (associar ao salbutamol)',
            dose_min: 0.02, dose_max: 0.05, dose_max_abs: 0.5,
            unidade: 'mg/kg/dose', freq: 'A cada 20 min × 3, depois 4/4h–6/6h',
            obs: '< 20 kg: 0,25 mg. ≥ 20 kg: 0,5 mg. Associar ao salbutamol.',
            apresentacoes: [
              { label: 'Sol. nebulização 0,25 mg/mL', conc: 0.25, tipo: 'mL' },
              { label: 'Spray (MDI) 20 mcg/jato', conc: 0.02, tipo: 'jatos' },
            ],
          },
        ],
        alerta: null,
      },
    ],
  },
];