/**
 * Dosagens — Cálculo Rápido
 * Cobertura ampla de medicamentos pediátricos, espelhando as categorias do pedb.com.br
 */

export const DOSAGENS_CATEGORIAS = [
  // ─────────────────────────────────────────
  // 1. ANALGÉSICOS / ANTITÉRMICOS
  // ─────────────────────────────────────────
  {
    id: 'antitermicos-analgesicos',
    label: 'Analgésicos e Antitérmicos',
    icon: '🌡️',
    color: 'orange',
    drugs: [
      {
        id: 'paracetamol',
        name: 'Paracetamol',
        sinonimo: 'Acetaminofeno',
        marcas: 'Tylenol, Tyflen, Cimegripe',
        via: 'VO/PR',
        dose_min: 10, dose_max: 15, dose_max_abs: 1000, dose_dia_max: 75, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Máx 4 g/dia em adultos. Intervalo mínimo 4–6h. Hepatotóxico em doses altas.',
        apresentacoes: [
          { label: 'Gotas 200 mg/mL (10 mg/gota)', conc: 200, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Suspensão 100 mg/mL (Bebê)', conc: 100, tipo: 'mL' },
          { label: 'Suspensão 32 mg/mL (Criança)', conc: 32, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Comprimido 750 mg', conc: 750, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'ibuprofeno',
        name: 'Ibuprofeno',
        sinonimo: null,
        marcas: 'Alivium, Dalsy, Advil, Motrin',
        via: 'VO',
        dose_min: 5, dose_max: 10, dose_max_abs: 800, dose_dia_max: 40, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Febre alta: 10 mg/kg/dose. Febre baixa: 5 mg/kg/dose. Máx 40 mg/kg/dia.',
        apresentacoes: [
          { label: 'Gotas 50 mg/mL (1 gota = 2,5 mg)', conc: 50, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Gotas 100 mg/mL (1 gota = 5 mg)', conc: 100, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Suspensão 20 mg/mL (100 mg/5 mL)', conc: 20, tipo: 'mL' },
          { label: 'Comprimido 200 mg', conc: 200, tipo: 'comprimido' },
          { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Comprimido 600 mg', conc: 600, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue. Evitar em < 6 meses.',
      },
      {
        id: 'dipirona',
        name: 'Dipirona',
        sinonimo: 'Metamizol',
        marcas: 'Novalgina, Anador, Alivdip',
        via: 'VO/EV/IM',
        dose_min: 10, dose_max: 15, dose_max_abs: 1000, dose_dia_max: 50, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Gotas 500 mg/mL: 0,4–0,6 gota/kg/dose. EV: 0,03 mL/kg/dose da ampola 500 mg/mL.',
        apresentacoes: [
          { label: 'Gotas 500 mg/mL (25 mg/gota)', conc: 500, tipo: 'gotas', mL_por_unidade: 0.05 },
          { label: 'Solução oral 50 mg/mL', conc: 50, tipo: 'mL' },
          { label: 'Ampola 500 mg/mL (EV/IM)', conc: 500, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Não usar em < 3 meses ou < 5 kg. Raro mas grave: agranulocitose.',
      },
      {
        id: 'naproxeno',
        name: 'Naproxeno',
        sinonimo: null,
        marcas: 'Flanax, Naprosyn',
        via: 'VO',
        dose_min: 5, dose_max: 10, dose_max_abs: 500, dose_dia_max: 20, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Anti-inflamatório para artrite juvenil: 10–20 mg/kg/dia ÷ 2. Meia-vida longa — 2×/dia.',
        apresentacoes: [
          { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Suspensão 25 mg/mL', conc: 25, tipo: 'mL' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'nimesulida',
        name: 'Nimesulida',
        sinonimo: null,
        marcas: 'Nisulid, Scaflan',
        via: 'VO',
        dose_min: 1.5, dose_max: 3, dose_max_abs: 100, dose_dia_max: 5, freq: 12,
        unidade: 'mg/kg/dose',
        obs: 'Uso restrito em > 12 anos. Máx 100 mg/dose × 2/dia. Tomar após refeição.',
        apresentacoes: [
          { label: 'Comprimido 100 mg', conc: 100, tipo: 'comprimido' },
          { label: 'Suspensão 50 mg/5 mL (10 mg/mL)', conc: 10, tipo: 'mL' },
          { label: 'Sachê 100 mg', conc: 100, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Evitar em < 12 anos. Risco de hepatotoxicidade.',
      },
      {
        id: 'cetoprofeno',
        name: 'Cetoprofeno',
        sinonimo: null,
        marcas: 'Profenid, Artrosil',
        via: 'VO/EV/IM',
        dose_min: 1, dose_max: 1.5, dose_max_abs: 100, dose_dia_max: 3, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Dor/inflamação: 1–1,5 mg/kg/dose × 3/dia. EV: 1–2 mg/kg/dose em 15–30 min.',
        apresentacoes: [
          { label: 'Cápsula 50 mg', conc: 50, tipo: 'comprimido' },
          { label: 'Ampola 50 mg/mL (EV/IM)', conc: 50, tipo: 'mL' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue.',
      },
      {
        id: 'codeina',
        name: 'Codeína',
        sinonimo: null,
        marcas: 'Tylex, Codein',
        via: 'VO',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 60, dose_dia_max: 3, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Dor moderada: 0,5–1 mg/kg/dose × 4–6/dia. Máx 60 mg/dose. Evitar < 12 anos.',
        apresentacoes: [
          { label: 'Comprimido 30 mg', conc: 30, tipo: 'comprimido' },
          { label: 'Solução oral 3 mg/mL', conc: 3, tipo: 'mL' },
        ],
        alerta: '⚠️ Risco de depressão respiratória fatal em metabolizadores ultrarrápidos. Evitar em < 12 anos.',
      },
      {
        id: 'tramadol',
        name: 'Tramadol',
        sinonimo: null,
        marcas: 'Tramal, Ultram',
        via: 'VO/EV',
        dose_min: 1, dose_max: 2, dose_max_abs: 100, dose_dia_max: 8, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Dor moderada a intensa: 1–2 mg/kg/dose VO × 4–6/dia. EV: 1–2 mg/kg em 30 min.',
        apresentacoes: [
          { label: 'Cápsula 50 mg', conc: 50, tipo: 'comprimido' },
          { label: 'Ampola 50 mg/mL (EV)', conc: 50, tipo: 'mL' },
          { label: 'Gotas 100 mg/mL', conc: 100, tipo: 'gotas', mL_por_unidade: 0.025 },
        ],
        alerta: '⚠️ Evitar em < 12 anos. Risco de convulsão e depressão respiratória.',
      },
    ],
  },

  // ─────────────────────────────────────────
  // 2. ANTI-INFLAMATÓRIOS (AINEs tópicos/sistêmicos)
  // ─────────────────────────────────────────
  {
    id: 'antiinflamatorios',
    label: 'Anti-inflamatórios',
    icon: '🔥',
    color: 'red',
    drugs: [
      {
        id: 'diclofenaco',
        name: 'Diclofenaco',
        sinonimo: null,
        marcas: 'Voltaren, Cataflam',
        via: 'VO/IM',
        dose_min: 1, dose_max: 1.5, dose_max_abs: 75, dose_dia_max: 3, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Dose usual: 1–3 mg/kg/dia ÷ 2–3 doses. Máx 150 mg/dia. IM: 75 mg dose única.',
        apresentacoes: [
          { label: 'Comprimido 25 mg', conc: 25, tipo: 'comprimido' },
          { label: 'Comprimido 50 mg', conc: 50, tipo: 'comprimido' },
          { label: 'Comprimido revestido 75 mg', conc: 75, tipo: 'comprimido' },
          { label: 'Ampola 75 mg/3 mL (IM)', conc: 25, tipo: 'mL' },
          { label: 'Supositório 12,5 mg', conc: 12.5, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue.',
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'piroxicam',
        name: 'Piroxicam',
        sinonimo: null,
        marcas: 'Feldene, Piroxicam',
        via: 'VO',
        dose_min: 0.2, dose_max: 0.3, dose_max_abs: 20, dose_dia_max: 0.3, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Artrite juvenil: 0,2–0,3 mg/kg/dia em dose única. Adulto: 10–20 mg/dia.',
        apresentacoes: [
          { label: 'Cápsula 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Cápsula 20 mg', conc: 20, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Contraindicado na suspeita de dengue. Maior risco de toxicidade GI.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'meloxicam',
        name: 'Meloxicam',
        sinonimo: null,
        marcas: 'Mobec, Melox',
        via: 'VO',
        dose_min: 0.125, dose_max: 0.25, dose_max_abs: 15, dose_dia_max: 0.25, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Artrite juvenil: 0,125–0,25 mg/kg/dia (máx 15 mg/dia). Dose única diária.',
        apresentacoes: [
          { label: 'Comprimido 7,5 mg', conc: 7.5, tipo: 'comprimido' },
          { label: 'Comprimido 15 mg', conc: 15, tipo: 'comprimido' },
          { label: 'Suspensão 1,5 mg/mL', conc: 1.5, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 3. ANTIBIÓTICOS ORAIS
  // ─────────────────────────────────────────
  {
    id: 'antibioticos-orais',
    label: 'Antibióticos Orais',
    icon: '💊',
    color: 'red',
    drugs: [
      {
        id: 'amoxicilina',
        name: 'Amoxicilina',
        sinonimo: null,
        marcas: 'Amoxil, Trimox',
        via: 'VO',
        dose_min: 25, dose_max: 50, dose_max_abs: 500, dose_dia_max: 90, freq: 8,
        unidade: 'mg/kg/dia ÷ 3 doses',
        obs: 'Otite/sinusite: 40–90 mg/kg/dia. Faringite: 50 mg/kg/dia. Pneumonia leve: 40–90 mg/kg/dia.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Suspensão 500 mg/5 mL (100 mg/mL)', conc: 100, tipo: 'mL' },
          { label: 'Cápsula 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'amoxicilina-clavulanato',
        name: 'Amoxicilina + Clavulanato',
        sinonimo: 'Amoxicilina/Ácido Clavulânico',
        marcas: 'Clavulin, Augmentin',
        via: 'VO',
        dose_min: 25, dose_max: 45, dose_max_abs: 875, dose_dia_max: 90, freq: 8,
        unidade: 'mg/kg/dia (da amox) ÷ 3',
        obs: 'Otite/sinusite resistente: 40–90 mg/kg/dia. Suspensão 400/57 mg/5 mL — calcular pela amoxicilina.',
        apresentacoes: [
          { label: 'Suspensão 250/62,5 mg/5 mL (50 mg/mL amox)', conc: 50, tipo: 'mL' },
          { label: 'Suspensão 400/57 mg/5 mL (80 mg/mL amox)', conc: 80, tipo: 'mL' },
          { label: 'Comp. 500/125 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Comp. 875/125 mg', conc: 875, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'azitromicina',
        name: 'Azitromicina',
        sinonimo: null,
        marcas: 'Zithromax, Azitro',
        via: 'VO',
        dose_min: 10, dose_max: 10, dose_max_abs: 500, dose_dia_max: 10, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Dose única diária por 3 dias (ou 5 dias em pneumonia). Faringite: 12 mg/kg/dia × 5 dias.',
        apresentacoes: [
          { label: 'Suspensão 200 mg/5 mL (40 mg/mL)', conc: 40, tipo: 'mL' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'claritromicina',
        name: 'Claritromicina',
        sinonimo: null,
        marcas: 'Klaricid, Claritrox',
        via: 'VO',
        dose_min: 7.5, dose_max: 15, dose_max_abs: 500, dose_dia_max: 15, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Dose usual: 15 mg/kg/dia ÷ 2 doses por 7–14 dias.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comprimido 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'cefalexina',
        name: 'Cefalexina',
        sinonimo: null,
        marcas: 'Keflex',
        via: 'VO',
        dose_min: 25, dose_max: 50, dose_max_abs: 500, dose_dia_max: 100, freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'Piodermite: 25–50 mg/kg/dia ÷ 3–4 doses. Infecção grave: 100 mg/kg/dia. Máx 4 g/dia.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 4,
      },
      {
        id: 'cefadroxila',
        name: 'Cefadroxila',
        sinonimo: null,
        marcas: 'Cedroxil, Cefanaxil',
        via: 'VO',
        dose_min: 15, dose_max: 30, dose_max_abs: 1000, dose_dia_max: 50, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Faringite/piodermite: 30 mg/kg/dia ÷ 1–2 doses por 10 dias. Máx 1 g/dose.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Suspensão 500 mg/5 mL (100 mg/mL)', conc: 100, tipo: 'mL' },
          { label: 'Cápsula 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'cefuroxima-oral',
        name: 'Cefuroxima (oral)',
        sinonimo: null,
        marcas: 'Zinnat, Cefuroxima',
        via: 'VO',
        dose_min: 10, dose_max: 15, dose_max_abs: 500, dose_dia_max: 30, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Otite/sinusite: 30 mg/kg/dia ÷ 2 por 10 dias. Faringite: 20 mg/kg/dia ÷ 2.',
        apresentacoes: [
          { label: 'Suspensão 250 mg/5 mL (50 mg/mL)', conc: 50, tipo: 'mL' },
          { label: 'Comp. 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'sulfametoxazol-trimetoprim',
        name: 'Sulfametoxazol + Trimetoprim',
        sinonimo: 'SMX/TMP — Cotrimoxazol',
        marcas: 'Bactrim, Bactelan',
        via: 'VO',
        dose_min: 6, dose_max: 12, dose_max_abs: 960, dose_dia_max: 12, freq: 12,
        unidade: 'mg/kg/dia (TMP) ÷ 2',
        obs: 'Calcular pelo TMP (20% da dose total). ITU: 5–6 mg TMP/kg/dia.',
        apresentacoes: [
          { label: 'Suspensão 200/40 mg/5 mL (8 mg TMP/mL)', conc: 8, tipo: 'mL' },
          { label: 'Comp. 400/80 mg', conc: 80, tipo: 'comprimido' },
          { label: 'Comp. Forte 800/160 mg', conc: 160, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Calcular pelo componente TMP. Contraindicado < 2 meses.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'nitrofurantoina',
        name: 'Nitrofurantoína',
        sinonimo: null,
        marcas: 'Macrobid, Macrodantina',
        via: 'VO',
        dose_min: 5, dose_max: 7, dose_max_abs: 100, dose_dia_max: 7, freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'ITU baixa. Usar com alimento. Profilaxia: 1–2 mg/kg/dia 1×/noite.',
        apresentacoes: [
          { label: 'Cápsula 100 mg', conc: 100, tipo: 'comprimido' },
          { label: 'Suspensão 25 mg/5 mL (5 mg/mL)', conc: 5, tipo: 'mL' },
        ],
        alerta: '⚠️ Evitar em < 3 meses e ClCr < 45 mL/min.',
        dose_por_dia: true, doses_por_dia: 4,
      },
      {
        id: 'penicilina-v',
        name: 'Penicilina V',
        sinonimo: 'Fenoximetilpenicilina',
        marcas: 'Pen-Ve-Oral, Penicilina V',
        via: 'VO',
        dose_min: 12.5, dose_max: 25, dose_max_abs: 500, dose_dia_max: 50, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Faringite estreptocócica: 250–500 mg × 2–3/dia por 10 dias.',
        apresentacoes: [
          { label: 'Suspensão 400.000 UI/5 mL (250 mg/5 mL)', conc: 50, tipo: 'mL' },
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'metronidazol',
        name: 'Metronidazol',
        sinonimo: 'Flagyl',
        marcas: 'Flagyl, Metronidazol',
        via: 'VO/EV',
        dose_min: 7.5, dose_max: 15, dose_max_abs: 500, dose_dia_max: 35, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Anaeróbios/Giardia: 15–35 mg/kg/dia ÷ 3. Giardíase: 15 mg/kg/dia × 5 dias.',
        apresentacoes: [
          { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
          { label: 'Comprimido 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Ampola 500 mg/100 mL (EV)', conc: 5, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'doxiciclina',
        name: 'Doxiciclina',
        sinonimo: null,
        marcas: 'Vibramicina, Clordox',
        via: 'VO',
        dose_min: 2, dose_max: 5, dose_max_abs: 100, dose_dia_max: 5, freq: 12,
        unidade: 'mg/kg/dia ÷ 2 (1º dia dobrado)',
        obs: '1º dia: 5 mg/kg. Manutenção: 2,5 mg/kg/dia ÷ 2. Máx 100 mg/dose. Apenas ≥ 8 anos.',
        apresentacoes: [
          { label: 'Comp. 100 mg', conc: 100, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Contraindicado em < 8 anos (manchas nos dentes).',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'fluconazol-oral',
        name: 'Fluconazol (oral)',
        sinonimo: null,
        marcas: 'Zoltec, Flucoran',
        via: 'VO',
        dose_min: 3, dose_max: 12, dose_max_abs: 400, dose_dia_max: 12, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Candidíase oral: 6 mg/kg ataque; 3 mg/kg/dia manutenção. Infecção grave: 12 mg/kg/dia.',
        apresentacoes: [
          { label: 'Cápsula 100 mg', conc: 100, tipo: 'comprimido' },
          { label: 'Cápsula 150 mg', conc: 150, tipo: 'comprimido' },
          { label: 'Suspensão 10 mg/mL', conc: 10, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'aciclovir-oral',
        name: 'Aciclovir (oral)',
        sinonimo: null,
        marcas: 'Zovirax, Aciclovir',
        via: 'VO',
        dose_min: 20, dose_max: 40, dose_max_abs: 800, dose_dia_max: 80, freq: 6,
        unidade: 'mg/kg/dia ÷ 5',
        obs: 'Varicela: 20 mg/kg/dose × 4–5/dia por 5 dias. Herpes labial: 200–400 mg × 5/dia.',
        apresentacoes: [
          { label: 'Comprimido 200 mg', conc: 200, tipo: 'comprimido' },
          { label: 'Comprimido 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Suspensão 200 mg/5 mL (40 mg/mL)', conc: 40, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 5,
      },
      {
        id: 'oseltamivir',
        name: 'Oseltamivir',
        sinonimo: 'Tamiflu',
        marcas: 'Tamiflu',
        via: 'VO',
        dose_min: 3, dose_max: 3.5, dose_max_abs: 75, dose_dia_max: 7, freq: 12,
        unidade: 'mg/kg/dia ÷ 2 por 5 dias',
        obs: '< 1 ano: 3 mg/kg × 2. 1–12 anos por peso: ≤ 15 kg: 30 mg × 2; 16–23 kg: 45 mg × 2; 24–40 kg: 60 mg × 2; > 40 kg: 75 mg × 2.',
        apresentacoes: [
          { label: 'Cápsula 30 mg', conc: 30, tipo: 'comprimido' },
          { label: 'Cápsula 45 mg', conc: 45, tipo: 'comprimido' },
          { label: 'Cápsula 75 mg', conc: 75, tipo: 'comprimido' },
          { label: 'Suspensão 6 mg/mL', conc: 6, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 4. ANTIBIÓTICOS PARENTERAIS
  // ─────────────────────────────────────────
  {
    id: 'antibioticos-parenterais',
    label: 'Antibióticos Parenterais',
    icon: '💉',
    color: 'purple',
    drugs: [
      {
        id: 'ceftriaxona',
        name: 'Ceftriaxona',
        sinonimo: null,
        marcas: 'Rocefin, Triaxon',
        via: 'EV/IM',
        dose_min: 50, dose_max: 100, dose_max_abs: 2000, dose_dia_max: 100, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Meningite: 100 mg/kg/dia ÷ 1–2. Sepse grave: 100 mg/kg/dia. Fr-amp 500 mg e 1000 mg.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: '⚠️ Não infundir com soluções com cálcio. Evitar em RN ictérico.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'cefazolina',
        name: 'Cefazolina',
        sinonimo: null,
        marcas: 'Cezolin, Fazolon',
        via: 'EV/IM',
        dose_min: 25, dose_max: 50, dose_max_abs: 2000, dose_dia_max: 100, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Infecções graves: 100 mg/kg/dia. Profilaxia cirúrgica: 50 mg/kg 30–60 min antes.',
        apresentacoes: [
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'cefotaxima',
        name: 'Cefotaxima',
        sinonimo: null,
        marcas: 'Claforan, Cefotaxima',
        via: 'EV/IM',
        dose_min: 50, dose_max: 100, dose_max_abs: 2000, dose_dia_max: 200, freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'Meningite: 200–300 mg/kg/dia ÷ 4–6. Lactentes e crianças: 50–180 mg/kg/dia ÷ 3–4.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 4,
      },
      {
        id: 'ceftazidima',
        name: 'Ceftazidima',
        sinonimo: null,
        marcas: 'Fortaz, Ceftazima',
        via: 'EV',
        dose_min: 30, dose_max: 50, dose_max_abs: 2000, dose_dia_max: 150, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Pseudomonas: 150–200 mg/kg/dia ÷ 3–4. Neutropênico: mesmo esquema.',
        apresentacoes: [
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'cefepima',
        name: 'Cefepima',
        sinonimo: null,
        marcas: 'Cefotax, Cemax',
        via: 'EV',
        dose_min: 50, dose_max: 50, dose_max_abs: 2000, dose_dia_max: 150, freq: 8,
        unidade: 'mg/kg/dose a cada 8–12h',
        obs: 'Casos graves/neutropênico: 50 mg/kg/dose × 3/dia. Máx 2 g/dose.',
        apresentacoes: [
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
          { label: 'Fr. amp. 2000 mg', conc: 2000, tipo: 'frasco' },
        ],
        alerta: null,
      },
      {
        id: 'ampicilina',
        name: 'Ampicilina',
        sinonimo: null,
        marcas: 'Binotal, Ampicilina sódica',
        via: 'EV/IM',
        dose_min: 100, dose_max: 200, dose_max_abs: 2000, dose_dia_max: 400, freq: 6,
        unidade: 'mg/kg/dia ÷ 4–6',
        obs: 'Meningite: 200–400 mg/kg/dia. Neonatos: 50 mg/kg/dose × 2–4/dia.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 4,
      },
      {
        id: 'oxacilina',
        name: 'Oxacilina',
        sinonimo: null,
        marcas: 'Oxacilina sódica',
        via: 'EV',
        dose_min: 100, dose_max: 200, dose_max_abs: 2000, dose_dia_max: 200, freq: 4,
        unidade: 'mg/kg/dia ÷ 6',
        obs: 'Estafilococos sensíveis. Infecção grave: 200 mg/kg/dia.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 6,
      },
      {
        id: 'penicilina-g-cristalina',
        name: 'Penicilina G Cristalina',
        sinonimo: null,
        marcas: 'Penicilina G Sódica',
        via: 'EV',
        dose_min: 100000, dose_max: 400000, dose_max_abs: 4000000, dose_dia_max: 400000, freq: 4,
        unidade: 'UI/kg/dia ÷ 6',
        obs: 'Meningite: 250.000–400.000 UI/kg/dia ÷ 4–6. Pneumonia: 200.000–400.000 UI/kg/dia.',
        apresentacoes: [
          { label: 'Fr. amp. 1.000.000 UI', conc: 1000000, tipo: 'frasco' },
          { label: 'Fr. amp. 5.000.000 UI', conc: 5000000, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 6,
      },
      {
        id: 'vancomicina',
        name: 'Vancomicina',
        sinonimo: null,
        marcas: 'Vancocin',
        via: 'EV',
        dose_min: 40, dose_max: 60, dose_max_abs: 2000, dose_dia_max: 60, freq: 6,
        unidade: 'mg/kg/dia ÷ 4',
        obs: 'MRSA/enterococo. Infundir em ≥ 60 min. Monitorar nível sérico. Neonatos: 15 mg/kg/dose × 2–3.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: '⚠️ Síndrome do homem vermelho se infusão rápida. Nefrotóxico. Monitorar nível sérico.',
        dose_por_dia: true, doses_por_dia: 4,
      },
      {
        id: 'gentamicina',
        name: 'Gentamicina',
        sinonimo: null,
        marcas: 'Garamicina',
        via: 'EV/IM',
        dose_min: 5, dose_max: 7.5, dose_max_abs: 300, dose_dia_max: 7.5, freq: 24,
        unidade: 'mg/kg/dia (1×/dia)',
        obs: 'Dose única diária preferida (exceto neonatos). Monitorar função renal e nível sérico.',
        apresentacoes: [
          { label: 'Ampola 40 mg/mL (2 mL = 80 mg)', conc: 40, tipo: 'mL' },
          { label: 'Ampola 10 mg/mL (neonatos)', conc: 10, tipo: 'mL' },
        ],
        alerta: '⚠️ Nefrotóxico e ototóxico. Monitorar nível sérico em uso prolongado.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'amicacina',
        name: 'Amicacina',
        sinonimo: null,
        marcas: 'Novamin, Amicacina',
        via: 'EV/IM',
        dose_min: 15, dose_max: 22.5, dose_max_abs: 1500, dose_dia_max: 22.5, freq: 24,
        unidade: 'mg/kg/dia (1×/dia)',
        obs: 'Dose única diária: 15–22,5 mg/kg. Neonatos: 15–20 mg/kg/dose × 1–2/dia.',
        apresentacoes: [
          { label: 'Ampola 250 mg/mL (2 mL = 500 mg)', conc: 250, tipo: 'mL' },
        ],
        alerta: '⚠️ Nefrotóxico e ototóxico. Monitorar função renal.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'meropenem',
        name: 'Meropenem',
        sinonimo: null,
        marcas: 'Meronem',
        via: 'EV',
        dose_min: 20, dose_max: 40, dose_max_abs: 2000, dose_dia_max: 120, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Infecção grave: 20–40 mg/kg/dose × 3/dia. Meningite: 40 mg/kg/dose × 3. Máx 2 g/dose.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
      },
      {
        id: 'imipenem',
        name: 'Imipenem + Cilastatina',
        sinonimo: null,
        marcas: 'Tienam',
        via: 'EV',
        dose_min: 15, dose_max: 25, dose_max_abs: 1000, dose_dia_max: 100, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Infecção grave: 15–25 mg/kg/dose × 4/dia. Máx 4 g/dia. Infundir em 30–60 min.',
        apresentacoes: [
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
        ],
        alerta: '⚠️ Risco de convulsão. Reduzir dose em insuficiência renal.',
      },
      {
        id: 'clindamicina',
        name: 'Clindamicina',
        sinonimo: null,
        marcas: 'Dalacin C',
        via: 'VO/EV',
        dose_min: 8, dose_max: 20, dose_max_abs: 600, dose_dia_max: 40, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Infecções graves: 20–40 mg/kg/dia ÷ 3–4. EV: 25–40 mg/kg/dia. Cápsula 150/300 mg.',
        apresentacoes: [
          { label: 'Cápsula 150 mg', conc: 150, tipo: 'comprimido' },
          { label: 'Cápsula 300 mg', conc: 300, tipo: 'comprimido' },
          { label: 'Ampola 150 mg/mL (EV)', conc: 150, tipo: 'mL' },
          { label: 'Suspensão 75 mg/5 mL (15 mg/mL)', conc: 15, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'aciclovir-ev',
        name: 'Aciclovir (EV)',
        sinonimo: null,
        marcas: 'Zovirax EV',
        via: 'EV',
        dose_min: 10, dose_max: 20, dose_max_abs: 800, dose_dia_max: 60, freq: 8,
        unidade: 'mg/kg/dose a cada 8h',
        obs: 'Encefalite herpética: 20 mg/kg/dose × 3 por 14–21 dias. Varicela grave: 10–15 mg/kg/dose × 3.',
        apresentacoes: [
          { label: 'Fr. amp. 250 mg', conc: 250, tipo: 'frasco' },
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
        ],
        alerta: '⚠️ Infundir em 1 hora. Hidratação adequada (nefrotóxico).',
      },
    ],
  },

  // ─────────────────────────────────────────
  // 5. BRONCODILATADORES E CORTICOIDES
  // ─────────────────────────────────────────
  {
    id: 'broncodilatadores-corticoides',
    label: 'Broncodilatadores e Corticoides',
    icon: '🫁',
    color: 'blue',
    drugs: [
      {
        id: 'salbutamol',
        name: 'Salbutamol',
        sinonimo: 'Albuterol',
        marcas: 'Aerolin, Airomir',
        via: 'Inalatório/EV',
        dose_min: 0.15, dose_max: 0.3, dose_max_abs: 5, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose (nebulização)',
        obs: 'Nebulização: 0,15 mg/kg/dose (mín 2,5 mg, máx 5 mg) em 3 mL SF. A cada 20 min. MDI: 4–8 jatos.',
        apresentacoes: [
          { label: 'Nebulização 5 mg/mL (0,5%)', conc: 5, tipo: 'mL' },
          { label: 'MDI 100 mcg/jato', conc: 0.1, tipo: 'jatos' },
        ],
        alerta: null,
      },
      {
        id: 'fenoterol',
        name: 'Fenoterol',
        sinonimo: null,
        marcas: 'Berotec',
        via: 'Inalatório',
        dose_min: 0.05, dose_max: 0.1, dose_max_abs: 5, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose (nebulização)',
        obs: 'Nebulização: gotas 5 mg/mL — 0,05–0,1 mg/kg (mín 1,25 mg) em 3 mL SF. MDI: 2–4 jatos.',
        apresentacoes: [
          { label: 'Nebulização 5 mg/mL (gotas)', conc: 5, tipo: 'mL' },
          { label: 'MDI 100 mcg/jato', conc: 0.1, tipo: 'jatos' },
        ],
        alerta: null,
      },
      {
        id: 'ipratropio',
        name: 'Ipratrópio',
        sinonimo: null,
        marcas: 'Atrovent',
        via: 'Inalatório',
        dose_min: 0.02, dose_max: 0.05, dose_max_abs: 0.5, dose_dia_max: null, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Nebulização: < 20 kg: 0,25 mg (1,25 mL); ≥ 20 kg: 0,5 mg (2,5 mL). Associar ao salbutamol.',
        apresentacoes: [
          { label: 'Solução 0,25 mg/mL (nebulização)', conc: 0.25, tipo: 'mL' },
          { label: 'MDI 20 mcg/jato', conc: 0.02, tipo: 'jatos' },
        ],
        alerta: null,
      },
      {
        id: 'prednisolona',
        name: 'Prednisolona',
        sinonimo: null,
        marcas: 'Predsim, Prelone',
        via: 'VO',
        dose_min: 1, dose_max: 2, dose_max_abs: 60, dose_dia_max: 2, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Asma moderada/grave: 1–2 mg/kg/dia (máx 60 mg/dia) × 3–5 dias. Crup: 0,6 mg/kg dose única.',
        apresentacoes: [
          { label: 'Suspensão 3 mg/mL', conc: 3, tipo: 'mL' },
          { label: 'Comprimido 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Comprimido 20 mg', conc: 20, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'prednisona',
        name: 'Prednisona',
        sinonimo: null,
        marcas: 'Meticorten, Predsim',
        via: 'VO',
        dose_min: 1, dose_max: 2, dose_max_abs: 60, dose_dia_max: 2, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Mesmas indicações da prednisolona. Asma: 1–2 mg/kg/dia × 3–5 dias. Máx 60 mg/dia.',
        apresentacoes: [
          { label: 'Comprimido 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Comprimido 20 mg', conc: 20, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'dexametasona',
        name: 'Dexametasona',
        sinonimo: null,
        marcas: 'Decadron, Dexametasona',
        via: 'VO/EV/IM',
        dose_min: 0.15, dose_max: 0.6, dose_max_abs: 10, dose_dia_max: 0.6, freq: 24,
        unidade: 'mg/kg/dose',
        obs: 'Crup: 0,15–0,6 mg/kg dose única. Meningite: 0,15 mg/kg × 4/dia × 2 dias. Anafilaxia: 0,15 mg/kg EV.',
        apresentacoes: [
          { label: 'Ampola 4 mg/mL (EV/IM)', conc: 4, tipo: 'mL' },
          { label: 'Comprimido 0,5 mg', conc: 0.5, tipo: 'comprimido' },
          { label: 'Comprimido 4 mg', conc: 4, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'hidrocortisona',
        name: 'Hidrocortisona',
        sinonimo: null,
        marcas: 'Solu-Cortef, Flebocortid',
        via: 'EV/IM',
        dose_min: 1, dose_max: 10, dose_max_abs: 500, dose_dia_max: 10, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Asma grave: 5–10 mg/kg/dose × 4/dia. Insuf. adrenal aguda: 50–100 mg/m² ataque EV.',
        apresentacoes: [
          { label: 'Fr. amp. 100 mg', conc: 100, tipo: 'frasco' },
          { label: 'Fr. amp. 500 mg', conc: 500, tipo: 'frasco' },
        ],
        alerta: null,
      },
      {
        id: 'metilprednisolona',
        name: 'Metilprednisolona',
        sinonimo: null,
        marcas: 'Solu-Medrol, Depo-Medrol',
        via: 'EV/IM',
        dose_min: 0.5, dose_max: 2, dose_max_abs: 1000, dose_dia_max: 30, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Asma: 1–2 mg/kg/dose × 2–4/dia. Pulsoterapia: 30 mg/kg/dia (máx 1 g) × 3 dias.',
        apresentacoes: [
          { label: 'Fr. amp. 125 mg (EV)', conc: 125, tipo: 'frasco' },
          { label: 'Fr. amp. 500 mg (EV)', conc: 500, tipo: 'frasco' },
          { label: 'Fr. amp. 1000 mg (pulsoterapia)', conc: 1000, tipo: 'frasco' },
        ],
        alerta: null,
      },
      {
        id: 'budesonida-inalatoria',
        name: 'Budesonida (inalatória)',
        sinonimo: null,
        marcas: 'Pulmicort, Busonid',
        via: 'Inalatório',
        dose_min: 0.5, dose_max: 2, dose_max_abs: 2, dose_dia_max: 4, freq: 12,
        unidade: 'mg/dia',
        obs: 'Crup moderado/grave: 2 mg nebulizado dose única (ou 1 mg × 2). Asma: 0,5–1 mg × 2/dia manutenção.',
        apresentacoes: [
          { label: 'Nebulização 0,25 mg/mL (2 mL)', conc: 0.25, tipo: 'mL' },
          { label: 'Nebulização 0,5 mg/mL (2 mL)', conc: 0.5, tipo: 'mL' },
        ],
        alerta: null,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 6. ANTICONVULSIVANTES
  // ─────────────────────────────────────────
  {
    id: 'anticonvulsivantes',
    label: 'Anticonvulsivantes',
    icon: '⚡',
    color: 'yellow',
    drugs: [
      {
        id: 'diazepam',
        name: 'Diazepam',
        sinonimo: null,
        marcas: 'Valium, Diazepam',
        via: 'EV/Retal',
        dose_min: 0.2, dose_max: 0.5, dose_max_abs: 10, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Convulsão: 0,2–0,5 mg/kg EV lento (máx 10 mg) ou 0,5 mg/kg retal. Repetir 1× após 5–10 min.',
        apresentacoes: [
          { label: 'Ampola 5 mg/mL (2 mL = 10 mg)', conc: 5, tipo: 'mL' },
          { label: 'Solução retal 5 mg/2,5 mL', conc: 2, tipo: 'mL' },
        ],
        alerta: '⚠️ Infundir lentamente (< 5 mg/min). Monitorar respiração.',
      },
      {
        id: 'midazolam',
        name: 'Midazolam',
        sinonimo: null,
        marcas: 'Dormonid',
        via: 'EV/IM/Intranasal',
        dose_min: 0.1, dose_max: 0.3, dose_max_abs: 10, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Convulsão: 0,1–0,3 mg/kg EV/IM (máx 10 mg). Intranasal: 0,2 mg/kg (0,1 mL/narina). Sedação: 0,05–0,1 mg/kg.',
        apresentacoes: [
          { label: 'Ampola 5 mg/mL (5 mL = 25 mg)', conc: 5, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar respiração e PA. Ter flumazenil disponível.',
      },
      {
        id: 'fenobarbital',
        name: 'Fenobarbital',
        sinonimo: null,
        marcas: 'Gardenal, Fenocris',
        via: 'EV/VO',
        dose_min: 15, dose_max: 20, dose_max_abs: 1000, dose_dia_max: null, freq: null,
        unidade: 'mg/kg (ataque EV)',
        obs: 'Status: 15–20 mg/kg EV (1 mg/kg/min). Manutenção VO: 3–5 mg/kg/dia × 1–2/dia.',
        apresentacoes: [
          { label: 'Ampola 100 mg/mL (EV)', conc: 100, tipo: 'mL' },
          { label: 'Comp. 100 mg (VO)', conc: 100, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Infusão lenta (1 mg/kg/min). Risco de apneia e hipotensão.',
      },
      {
        id: 'fenitoina',
        name: 'Fenitoína',
        sinonimo: null,
        marcas: 'Hidantal, Epelin',
        via: 'EV/VO',
        dose_min: 15, dose_max: 20, dose_max_abs: 1500, dose_dia_max: null, freq: null,
        unidade: 'mg/kg (ataque EV)',
        obs: 'Ataque: 15–20 mg/kg EV (1 mg/kg/min). Manutenção: 4–8 mg/kg/dia ÷ 1–3. Monitorar ECG.',
        apresentacoes: [
          { label: 'Ampola 50 mg/mL (EV)', conc: 50, tipo: 'mL' },
          { label: 'Comp. 100 mg', conc: 100, tipo: 'comprimido' },
          { label: 'Suspensão 25 mg/mL', conc: 25, tipo: 'mL' },
        ],
        alerta: '⚠️ Infundir ≤ 1 mg/kg/min. Monitorar ECG (arritmias). Não usar em SGl.',
      },
      {
        id: 'valproato',
        name: 'Valproato de Sódio',
        sinonimo: 'Ácido Valpróico',
        marcas: 'Depakene, Depakote',
        via: 'VO/EV',
        dose_min: 10, dose_max: 30, dose_max_abs: 2500, dose_dia_max: 60, freq: 12,
        unidade: 'mg/kg/dia ÷ 2–3',
        obs: 'Iniciar 10–15 mg/kg/dia; aumentar 5–10 mg/kg/semana. Máx 60 mg/kg/dia. EV: mesmo mg/kg.',
        apresentacoes: [
          { label: 'Solução 57,64 mg/mL (= 50 mg/mL VPA)', conc: 50, tipo: 'mL' },
          { label: 'Comp. 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Fr. amp. 500 mg (EV)', conc: 500, tipo: 'frasco' },
        ],
        alerta: '⚠️ Hepatotóxico em < 2 anos. Monitorar função hepática. Teratogênico.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'carbamazepina',
        name: 'Carbamazepina',
        sinonimo: null,
        marcas: 'Tegretol',
        via: 'VO',
        dose_min: 5, dose_max: 20, dose_max_abs: 1200, dose_dia_max: 35, freq: 12,
        unidade: 'mg/kg/dia ÷ 2–3',
        obs: 'Iniciar 5 mg/kg/dia; aumentar gradual. Manutenção: 15–35 mg/kg/dia ÷ 2–3. Nível sérico: 4–12 µg/mL.',
        apresentacoes: [
          { label: 'Comp. 200 mg', conc: 200, tipo: 'comprimido' },
          { label: 'Comp. 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Suspensão 20 mg/mL', conc: 20, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar hemograma e eletrólitos. Interações medicamentosas significativas.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'levetiracetam',
        name: 'Levetiracetam',
        sinonimo: null,
        marcas: 'Keppra',
        via: 'VO/EV',
        dose_min: 10, dose_max: 30, dose_max_abs: 3000, dose_dia_max: 60, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Iniciar 10–20 mg/kg/dia; aumentar 10 mg/kg/semana. Máx 60 mg/kg/dia. EV (status): 20–60 mg/kg.',
        apresentacoes: [
          { label: 'Comp. 250 mg', conc: 250, tipo: 'comprimido' },
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
          { label: 'Solução 100 mg/mL', conc: 100, tipo: 'mL' },
          { label: 'Fr. amp. 500 mg/5 mL (EV)', conc: 100, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 7. ANTI-HISTAMÍNICOS E ANTIALÉRGICOS
  // ─────────────────────────────────────────
  {
    id: 'antialergicos',
    label: 'Anti-histamínicos e Antialérgicos',
    icon: '🌿',
    color: 'green',
    drugs: [
      {
        id: 'loratadina',
        name: 'Loratadina',
        sinonimo: null,
        marcas: 'Claritin, Loratadina',
        via: 'VO',
        dose_min: 0.2, dose_max: 0.2, dose_max_abs: 10, dose_dia_max: 0.2, freq: 24,
        unidade: 'mg/kg/dia',
        obs: '< 30 kg: 5 mg/dia. ≥ 30 kg: 10 mg/dia. 1×/dia.',
        apresentacoes: [
          { label: 'Xarope 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'cetirizina',
        name: 'Cetirizina',
        sinonimo: null,
        marcas: 'Zyrtec, Cetrizin',
        via: 'VO',
        dose_min: 0.25, dose_max: 0.25, dose_max_abs: 10, dose_dia_max: 0.25, freq: 24,
        unidade: 'mg/kg/dia',
        obs: '< 15 kg: 2,5 mg/dia. 15–30 kg: 5 mg/dia. > 30 kg: 10 mg/dia. 1×/dia.',
        apresentacoes: [
          { label: 'Xarope 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'desloratadina',
        name: 'Desloratadina',
        sinonimo: null,
        marcas: 'Desalex, Aerius',
        via: 'VO',
        dose_min: 0.1, dose_max: 0.1, dose_max_abs: 5, dose_dia_max: 0.1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: '6–12 m: 1 mg/dia. 1–5 anos: 1,25 mg/dia. 6–11 anos: 2,5 mg/dia. ≥ 12 anos: 5 mg/dia.',
        apresentacoes: [
          { label: 'Xarope 0,5 mg/mL', conc: 0.5, tipo: 'mL' },
          { label: 'Comprimido 5 mg', conc: 5, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'fexofenadina',
        name: 'Fexofenadina',
        sinonimo: null,
        marcas: 'Allegra',
        via: 'VO',
        dose_min: 1.5, dose_max: 2, dose_max_abs: 180, dose_dia_max: 4, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: '6–11 anos: 30 mg × 2/dia. ≥ 12 anos: 60–120 mg × 2/dia ou 180 mg × 1/dia.',
        apresentacoes: [
          { label: 'Comp. 60 mg', conc: 60, tipo: 'comprimido' },
          { label: 'Comp. 120 mg', conc: 120, tipo: 'comprimido' },
          { label: 'Comp. 180 mg', conc: 180, tipo: 'comprimido' },
          { label: 'Suspensão 6 mg/mL', conc: 6, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'hidroxizina',
        name: 'Hidroxizina',
        sinonimo: null,
        marcas: 'Hixizine, Atarax',
        via: 'VO',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 50, dose_dia_max: 2, freq: 6,
        unidade: 'mg/kg/dose',
        obs: 'Urticária/prurido: 0,5–1 mg/kg/dose × 3–4/dia. Sedação pré-procedimento: 1–2 mg/kg.',
        apresentacoes: [
          { label: 'Xarope 2 mg/mL', conc: 2, tipo: 'mL' },
          { label: 'Comprimido 25 mg', conc: 25, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Sedativo. Evitar em < 6 meses.',
      },
      {
        id: 'prometazina',
        name: 'Prometazina',
        sinonimo: null,
        marcas: 'Fenergan',
        via: 'VO/EV/IM',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 25, dose_dia_max: 1, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Alergia grave/anafilaxia: 0,5–1 mg/kg EV/IM. Sedação: 0,5 mg/kg VO. Máx 25 mg/dose.',
        apresentacoes: [
          { label: 'Ampola 25 mg/mL (EV/IM)', conc: 25, tipo: 'mL' },
          { label: 'Xarope 5 mg/5 mL (1 mg/mL)', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 25 mg', conc: 25, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Evitar em < 2 anos (risco de apneia). Sedativo.',
      },
      {
        id: 'adrenalina',
        name: 'Adrenalina (Epinefrina)',
        sinonimo: 'Epinefrina',
        marcas: 'Adrenalina, EpiPen',
        via: 'IM/EV/Inalatório',
        dose_min: 0.01, dose_max: 0.01, dose_max_abs: 0.5, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose IM (1:1000)',
        obs: 'Anafilaxia IM: 0,01 mg/kg da 1:1000 (máx 0,5 mg). Crup: 0,5 mL/kg (máx 4 mL) da 1:1000 nebulizado.',
        apresentacoes: [
          { label: 'Ampola 1 mg/mL (1:1000)', conc: 1, tipo: 'mL' },
          { label: 'Ampola 0,1 mg/mL (1:10.000 — PCR)', conc: 0.1, tipo: 'mL' },
        ],
        alerta: '🚨 Anafilaxia: via IM (face anterolateral da coxa). Monitorar FC e PA.',
      },
    ],
  },

  // ─────────────────────────────────────────
  // 8. ANTIÁCIDOS / GASTRO
  // ─────────────────────────────────────────
  {
    id: 'gastro',
    label: 'Gastrointestinal',
    icon: '🫃',
    color: 'teal',
    drugs: [
      {
        id: 'ondansetrona',
        name: 'Ondansetrona',
        sinonimo: null,
        marcas: 'Vonau, Zofran',
        via: 'VO/EV',
        dose_min: 0.1, dose_max: 0.15, dose_max_abs: 4, dose_dia_max: 0.45, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Vômitos: 0,1–0,15 mg/kg/dose (máx 4 mg) × 3/dia. EV em 15 min.',
        apresentacoes: [
          { label: 'Ampola 2 mg/mL (EV)', conc: 2, tipo: 'mL' },
          { label: 'Comprimido 4 mg', conc: 4, tipo: 'comprimido' },
          { label: 'Comprimido 8 mg', conc: 8, tipo: 'comprimido' },
          { label: 'Solução oral 0,8 mg/mL', conc: 0.8, tipo: 'mL' },
        ],
        alerta: null,
      },
      {
        id: 'domperidona',
        name: 'Domperidona',
        sinonimo: null,
        marcas: 'Motilium',
        via: 'VO',
        dose_min: 0.2, dose_max: 0.3, dose_max_abs: 10, dose_dia_max: 0.9, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Refluxo/vômitos: 0,2–0,3 mg/kg/dose × 3/dia. Máx 10 mg/dose.',
        apresentacoes: [
          { label: 'Suspensão 1 mg/mL', conc: 1, tipo: 'mL' },
          { label: 'Comprimido 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Risco de prolongamento QT. Usar menor dose e duração.',
      },
      {
        id: 'metoclopramida',
        name: 'Metoclopramida',
        sinonimo: null,
        marcas: 'Plasil, Metoclopramida',
        via: 'VO/EV',
        dose_min: 0.1, dose_max: 0.15, dose_max_abs: 5, dose_dia_max: 0.5, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Vômitos/refluxo: 0,1–0,15 mg/kg/dose × 3/dia. Máx 5 mg/dose em crianças.',
        apresentacoes: [
          { label: 'Ampola 5 mg/mL (EV)', conc: 5, tipo: 'mL' },
          { label: 'Comp. 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Solução 4 mg/mL', conc: 4, tipo: 'mL' },
        ],
        alerta: '⚠️ Risco de reações extrapiramidais. Evitar uso prolongado em crianças.',
      },
      {
        id: 'omeprazol',
        name: 'Omeprazol',
        sinonimo: null,
        marcas: 'Losec, Peprazol',
        via: 'VO/EV',
        dose_min: 0.7, dose_max: 1, dose_max_abs: 20, dose_dia_max: 1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'DRGE/úlcera: 0,7–1 mg/kg/dia (máx 20 mg/dia). Tomar 30 min antes do café.',
        apresentacoes: [
          { label: 'Cápsula 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Cápsula 20 mg', conc: 20, tipo: 'comprimido' },
          { label: 'Fr. amp. 40 mg (EV)', conc: 40, tipo: 'frasco' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'lansoprazol',
        name: 'Lansoprazol',
        sinonimo: null,
        marcas: 'Prazol, Ogastro',
        via: 'VO',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 30, dose_dia_max: 1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'DRGE: 0,5–1 mg/kg/dia (máx 30 mg). Tomar 30 min antes da refeição.',
        apresentacoes: [
          { label: 'Cápsula 15 mg', conc: 15, tipo: 'comprimido' },
          { label: 'Cápsula 30 mg', conc: 30, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'ranitidina',
        name: 'Ranitidina',
        sinonimo: null,
        marcas: 'Antak, Label',
        via: 'VO/EV',
        dose_min: 2, dose_max: 4, dose_max_abs: 150, dose_dia_max: 8, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'Refluxo/úlcera: 4–8 mg/kg/dia ÷ 2 doses. EV: 1–2 mg/kg/dose × 3–4/dia.',
        apresentacoes: [
          { label: 'Xarope 15 mg/mL', conc: 15, tipo: 'mL' },
          { label: 'Comp. 150 mg', conc: 150, tipo: 'comprimido' },
          { label: 'Ampola 25 mg/mL (EV)', conc: 25, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'loperamida',
        name: 'Loperamida',
        sinonimo: null,
        marcas: 'Imosec, Loperamida',
        via: 'VO',
        dose_min: 0.05, dose_max: 0.1, dose_max_abs: 2, dose_dia_max: 0.2, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Diarreia: 0,08–0,24 mg/kg/dia ÷ 2–3. Evitar em < 2 anos. Máx 2 mg/dose.',
        apresentacoes: [
          { label: 'Cápsula 2 mg', conc: 2, tipo: 'comprimido' },
          { label: 'Solução 0,2 mg/mL', conc: 0.2, tipo: 'mL' },
        ],
        alerta: '⚠️ Evitar em < 2 anos, diarreia com sangue ou febre alta.',
      },
      {
        id: 'sulfato-zinco',
        name: 'Sulfato de Zinco (diarreia)',
        sinonimo: null,
        marcas: 'Zincovit, Zinco',
        via: 'VO',
        dose_min: 10, dose_max: 20, dose_max_abs: 20, dose_dia_max: 20, freq: 24,
        unidade: 'mg/dia (elemento zinco)',
        obs: '< 6 meses: 10 mg/dia × 10–14 dias. ≥ 6 meses: 20 mg/dia × 10–14 dias (OMS — diarreia aguda).',
        apresentacoes: [
          { label: 'Comp. 20 mg (elemento zinco)', conc: 20, tipo: 'comprimido' },
          { label: 'Solução 10 mg/5 mL (2 mg/mL)', conc: 2, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 9. ANTITUSSÍGENOS
  // ─────────────────────────────────────────
  {
    id: 'antitussigenos',
    label: 'Antitussígenos e Mucolíticos',
    icon: '🤧',
    color: 'cyan',
    drugs: [
      {
        id: 'ambroxol',
        name: 'Ambroxol',
        sinonimo: null,
        marcas: 'Mucosolvan, Ambrex',
        via: 'VO',
        dose_min: 0.6, dose_max: 1.2, dose_max_abs: 30, dose_dia_max: 3, freq: 8,
        unidade: 'mg/kg/dose',
        obs: '2–5 anos: 7,5 mg × 2–3/dia. 6–12 anos: 15 mg × 3/dia. > 12 anos: 30 mg × 3/dia.',
        apresentacoes: [
          { label: 'Xarope 3 mg/mL (pediátrico)', conc: 3, tipo: 'mL' },
          { label: 'Xarope 6 mg/mL (adulto)', conc: 6, tipo: 'mL' },
          { label: 'Gotas 7,5 mg/mL', conc: 7.5, tipo: 'mL' },
          { label: 'Comprimido 30 mg', conc: 30, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'acetilcisteina',
        name: 'Acetilcisteína',
        sinonimo: 'NAC',
        marcas: 'Fluimucil, Mucolitic',
        via: 'VO/EV',
        dose_min: 10, dose_max: 15, dose_max_abs: 600, dose_dia_max: 30, freq: 8,
        unidade: 'mg/kg/dia ÷ 2–3',
        obs: 'Mucolítico: 10–30 mg/kg/dia ÷ 2–3. Antídoto paracetamol (EV): 150 mg/kg ataque em 15 min.',
        apresentacoes: [
          { label: 'Granulado 200 mg (sachê)', conc: 200, tipo: 'comprimido' },
          { label: 'Granulado 600 mg (sachê)', conc: 600, tipo: 'comprimido' },
          { label: 'Fr. amp. 200 mg/mL (EV)', conc: 200, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'carbocisteina',
        name: 'Carbocisteína',
        sinonimo: null,
        marcas: 'Motosol, Bisolvon',
        via: 'VO',
        dose_min: 10, dose_max: 20, dose_max_abs: 750, dose_dia_max: 30, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: '2–5 anos: 62,5–125 mg × 3/dia. > 5 anos: 125–250 mg × 3/dia.',
        apresentacoes: [
          { label: 'Xarope 50 mg/mL', conc: 50, tipo: 'mL' },
          { label: 'Comp. 375 mg', conc: 375, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 3,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 10. ANTIPARASITÁRIOS
  // ─────────────────────────────────────────
  {
    id: 'antiparasitarios',
    label: 'Anti-Parasitários',
    icon: '🪱',
    color: 'lime',
    drugs: [
      {
        id: 'albendazol',
        name: 'Albendazol',
        sinonimo: null,
        marcas: 'Zentel, Albend',
        via: 'VO',
        dose_min: 7.5, dose_max: 7.5, dose_max_abs: 400, dose_dia_max: 15, freq: 24,
        unidade: 'mg/kg/dose',
        obs: 'Helmintos intestinais: 400 mg dose única (> 2 anos). < 2 anos: 200 mg. Giárdia: 400 mg × 1/dia × 3–5 dias.',
        apresentacoes: [
          { label: 'Comp. 400 mg', conc: 400, tipo: 'comprimido' },
          { label: 'Suspensão 40 mg/mL', conc: 40, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'mebendazol',
        name: 'Mebendazol',
        sinonimo: null,
        marcas: 'Pantelmin, Mebendazol',
        via: 'VO',
        dose_min: 100, dose_max: 100, dose_max_abs: 500, dose_dia_max: 200, freq: 12,
        unidade: 'mg/dose (fixa)',
        obs: 'Ancilostomíase/tricuríase: 100 mg × 2/dia × 3 dias. Oxiuríase: 100 mg dose única.',
        apresentacoes: [
          { label: 'Comp. 100 mg', conc: 100, tipo: 'comprimido' },
          { label: 'Suspensão 20 mg/mL', conc: 20, tipo: 'mL' },
        ],
        alerta: null,
      },
      {
        id: 'ivermectina',
        name: 'Ivermectina',
        sinonimo: null,
        marcas: 'Ivermectin, Revectina',
        via: 'VO',
        dose_min: 0.2, dose_max: 0.4, dose_max_abs: 24, dose_dia_max: 0.4, freq: 24,
        unidade: 'mg/kg/dose',
        obs: 'Sarna: 0,2 mg/kg dose única (repetir em 1–2 semanas). Estrongiloidíase: 0,2 mg/kg × 1–2 dias. Apenas > 15 kg.',
        apresentacoes: [
          { label: 'Comp. 6 mg', conc: 6, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Evitar em < 15 kg. Tomar em jejum.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'nitazoxanida',
        name: 'Nitazoxanida',
        sinonimo: null,
        marcas: 'Anitta, Annita',
        via: 'VO',
        dose_min: 7.5, dose_max: 7.5, dose_max_abs: 500, dose_dia_max: 15, freq: 12,
        unidade: 'mg/kg/dose',
        obs: '1–3 anos: 100 mg × 2/dia. 4–11 anos: 200 mg × 2/dia. > 12 anos: 500 mg × 2/dia. Por 3 dias (Giardia/Crypto).',
        apresentacoes: [
          { label: 'Suspensão 100 mg/5 mL (20 mg/mL)', conc: 20, tipo: 'mL' },
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'permetrina',
        name: 'Permetrina (uso tópico)',
        sinonimo: null,
        marcas: 'Keltrix, Scabiax',
        via: 'Tópico',
        dose_min: null, dose_max: null, dose_max_abs: null, dose_dia_max: null, freq: null,
        unidade: 'Uso tópico — não calcular por kg',
        obs: 'Sarna: creme 5% — aplicar do pescoço para os pés, lavar após 8–14h. Repetir em 1–2 semanas. Pediculose: loção 1% — aplicar por 10 min.',
        apresentacoes: [
          { label: 'Creme 5% (sarna)', conc: 50, tipo: 'mL' },
          { label: 'Loção 1% (pediculose)', conc: 10, tipo: 'mL' },
        ],
        alerta: null,
      },
      {
        id: 'tinidazol',
        name: 'Tinidazol',
        sinonimo: null,
        marcas: 'Fasigyn, Tricomonacid',
        via: 'VO',
        dose_min: 25, dose_max: 50, dose_max_abs: 2000, dose_dia_max: 50, freq: 24,
        unidade: 'mg/kg/dose',
        obs: 'Giardíase: 50 mg/kg dose única (máx 2 g). Amebíase: 50 mg/kg/dia × 3 dias.',
        apresentacoes: [
          { label: 'Comp. 500 mg', conc: 500, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 11. LAXANTES
  // ─────────────────────────────────────────
  {
    id: 'laxantes',
    label: 'Laxantes',
    icon: '🌾',
    color: 'amber',
    drugs: [
      {
        id: 'polietilenoglicol',
        name: 'Polietilenoglicol (PEG)',
        sinonimo: 'Macrogol',
        marcas: 'Muvinlax, Forlax, Movicol',
        via: 'VO',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 34, dose_dia_max: 1.5, freq: 24,
        unidade: 'g/kg/dia',
        obs: 'Constipação: 0,5–1 g/kg/dia. Desimpactação: 1–1,5 g/kg/dia × 3–6 dias. Dissolver em água.',
        apresentacoes: [
          { label: 'Sachê 17 g', conc: 17, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'lactulose',
        name: 'Lactulose',
        sinonimo: null,
        marcas: 'Lactulona, Duphalac',
        via: 'VO',
        dose_min: 0.5, dose_max: 1, dose_max_abs: 40, dose_dia_max: 3, freq: 12,
        unidade: 'mL/kg/dia ÷ 2',
        obs: 'Constipação: 0,5–1 mL/kg × 1–2/dia. Encefalopatia hepática: 0,5–1 mL/kg × 3–4/dia.',
        apresentacoes: [
          { label: 'Xarope 667 mg/mL (66,7%)', conc: 667, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'picossulfato-sodio',
        name: 'Picossulfato de Sódio',
        sinonimo: null,
        marcas: 'Guttalax, Laxol',
        via: 'VO',
        dose_min: 0.1, dose_max: 0.3, dose_max_abs: 10, dose_dia_max: 0.3, freq: 24,
        unidade: 'mg/kg/dia',
        obs: '< 4 anos: 2,5–5 mg/dia. 4–10 anos: 5 mg/dia. > 10 anos: 5–10 mg/dia. Efeito em 6–12h.',
        apresentacoes: [
          { label: 'Gotas 7,5 mg/mL', conc: 7.5, tipo: 'gotas', mL_por_unidade: 0.033 },
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'bisacodil',
        name: 'Bisacodil',
        sinonimo: null,
        marcas: 'Lacto-purga, Dulcolax',
        via: 'VO/Retal',
        dose_min: 0.1, dose_max: 0.3, dose_max_abs: 10, dose_dia_max: 0.3, freq: 24,
        unidade: 'mg/kg/dose',
        obs: '3–12 anos: 5 mg/dose. > 12 anos: 5–10 mg/dose. Supositório: 5 ou 10 mg. 1×/dia.',
        apresentacoes: [
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Supositório 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Supositório 10 mg', conc: 10, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 12. CARDIOVASCULAR / ANTI-HIPERTENSIVOS
  // ─────────────────────────────────────────
  {
    id: 'cardiovascular',
    label: 'Cardiovascular e Anti-hipertensivos',
    icon: '❤️',
    color: 'pink',
    drugs: [
      {
        id: 'captopril',
        name: 'Captopril',
        sinonimo: null,
        marcas: 'Capoten, Captopril',
        via: 'VO',
        dose_min: 0.1, dose_max: 0.5, dose_max_abs: 6, dose_dia_max: 6, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'Iniciar 0,1 mg/kg/dia. Aumentar gradual. Máx 6 mg/kg/dia.',
        apresentacoes: [
          { label: 'Comp. 12,5 mg', conc: 12.5, tipo: 'comprimido' },
          { label: 'Comp. 25 mg', conc: 25, tipo: 'comprimido' },
          { label: 'Solução 1 mg/mL (manipulada)', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar função renal e potássio. Evitar em RN e gravidez.',
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'enalapril',
        name: 'Enalapril',
        sinonimo: null,
        marcas: 'Vasotec, Renitec',
        via: 'VO',
        dose_min: 0.05, dose_max: 0.6, dose_max_abs: 40, dose_dia_max: 1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Iniciar 0,05–0,1 mg/kg/dia. Máx 0,6 mg/kg/dia (máx 40 mg/dia).',
        apresentacoes: [
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Comp. 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Solução 1 mg/mL (manipulada)', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar função renal e potássio.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'propranolol',
        name: 'Propranolol',
        sinonimo: null,
        marcas: 'Inderal, Propranolol',
        via: 'VO',
        dose_min: 0.5, dose_max: 2, dose_max_abs: 60, dose_dia_max: 8, freq: 8,
        unidade: 'mg/kg/dia ÷ 3',
        obs: 'HAS: 0,5–1 mg/kg/dia ÷ 3. Taquicardia: 1–4 mg/kg/dia. Hemangioma: 2–3 mg/kg/dia ÷ 2.',
        apresentacoes: [
          { label: 'Comp. 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Comp. 40 mg', conc: 40, tipo: 'comprimido' },
          { label: 'Solução 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Pode mascarar hipoglicemia. Não interromper abruptamente.',
        dose_por_dia: true, doses_por_dia: 3,
      },
      {
        id: 'amlodipino',
        name: 'Anlodipino',
        sinonimo: null,
        marcas: 'Norvasc, Anlo',
        via: 'VO',
        dose_min: 0.1, dose_max: 0.2, dose_max_abs: 5, dose_dia_max: 0.6, freq: 24,
        unidade: 'mg/kg/dia',
        obs: '6–17 anos: 2,5–5 mg/dia. Iniciar 0,1 mg/kg/dia. Dose única diária.',
        apresentacoes: [
          { label: 'Comp. 2,5 mg', conc: 2.5, tipo: 'comprimido' },
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'digoxina',
        name: 'Digoxina',
        sinonimo: null,
        marcas: 'Lanoxin, Digoxina',
        via: 'VO/EV',
        dose_min: 0.008, dose_max: 0.012, dose_max_abs: 0.25, dose_dia_max: 0.012, freq: 24,
        unidade: 'mg/kg/dia (manutenção)',
        obs: 'Manutenção VO: 8–12 mcg/kg/dia. Digitalização: 20–30 mcg/kg ÷ 3 doses (ver protocolo). Nível sérico: 0,8–2 ng/mL.',
        apresentacoes: [
          { label: 'Solução 0,05 mg/mL (pediátrico)', conc: 0.05, tipo: 'mL' },
          { label: 'Comp. 0,25 mg', conc: 0.25, tipo: 'comprimido' },
          { label: 'Ampola 0,5 mg/2 mL (EV)', conc: 0.25, tipo: 'mL' },
        ],
        alerta: '⚠️ Índice terapêutico estreito. Monitorar nível sérico, ECG, eletrólitos.',
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 13. PSICOTRÓPICOS
  // ─────────────────────────────────────────
  {
    id: 'psicoativos',
    label: 'Psicotrópicos',
    icon: '🧠',
    color: 'purple',
    drugs: [
      {
        id: 'metilfenidato',
        name: 'Metilfenidato',
        sinonimo: null,
        marcas: 'Ritalina, Concerta',
        via: 'VO',
        dose_min: 0.3, dose_max: 1, dose_max_abs: 60, dose_dia_max: 2, freq: 12,
        unidade: 'mg/kg/dia ÷ 2',
        obs: 'TDAH: iniciar 0,3 mg/kg/dose; aumentar 0,1 mg/kg/semana. Máx 60 mg/dia (1 mg/kg/dose).',
        apresentacoes: [
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
          { label: 'Comp. 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Comp. LP 18 mg (Concerta)', conc: 18, tipo: 'comprimido' },
          { label: 'Comp. LP 36 mg (Concerta)', conc: 36, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Monitorar peso, altura, FC e PA. Uso restrito: controle especial.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'risperidona',
        name: 'Risperidona',
        sinonimo: null,
        marcas: 'Risperdal, Risperidona',
        via: 'VO',
        dose_min: 0.01, dose_max: 0.06, dose_max_abs: 3, dose_dia_max: 0.06, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Autismo (irritabilidade): iniciar 0,25 mg/dia (< 20 kg) ou 0,5 mg/dia (≥ 20 kg). Aumentar gradual.',
        apresentacoes: [
          { label: 'Comp. 1 mg', conc: 1, tipo: 'comprimido' },
          { label: 'Comp. 2 mg', conc: 2, tipo: 'comprimido' },
          { label: 'Solução 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar ganho de peso, efeitos extrapiramidais e prolactina.',
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'haloperidol',
        name: 'Haloperidol',
        sinonimo: null,
        marcas: 'Haldol, Haloperidol',
        via: 'VO/IM',
        dose_min: 0.025, dose_max: 0.075, dose_max_abs: 5, dose_dia_max: 0.15, freq: 12,
        unidade: 'mg/kg/dia ÷ 2–3',
        obs: 'Agitação aguda: 0,025–0,075 mg/kg ÷ 2–3/dia. IM (agitação grave): 0,025–0,05 mg/kg/dose.',
        apresentacoes: [
          { label: 'Gotas 2 mg/mL', conc: 2, tipo: 'mL' },
          { label: 'Comp. 1 mg', conc: 1, tipo: 'comprimido' },
          { label: 'Ampola 5 mg/mL (IM)', conc: 5, tipo: 'mL' },
        ],
        alerta: '⚠️ Risco de distonia aguda. Ter biperideno disponível.',
        dose_por_dia: true, doses_por_dia: 2,
      },
      {
        id: 'fluoxetina',
        name: 'Fluoxetina',
        sinonimo: null,
        marcas: 'Prozac, Fluoxetina',
        via: 'VO',
        dose_min: 0.1, dose_max: 0.5, dose_max_abs: 60, dose_dia_max: 1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Depressão/ansiedade ≥ 8 anos: iniciar 5–10 mg/dia. Aumentar gradual. Máx 60 mg/dia.',
        apresentacoes: [
          { label: 'Cápsula 10 mg', conc: 10, tipo: 'comprimido' },
          { label: 'Cápsula 20 mg', conc: 20, tipo: 'comprimido' },
          { label: 'Solução 4 mg/mL', conc: 4, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar ideação suicida nas primeiras semanas. Síndrome de descontinuação.',
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 14. VITAMINAS E SUPLEMENTOS
  // ─────────────────────────────────────────
  {
    id: 'vitaminas-suplementos',
    label: 'Vitaminas e Suplementos',
    icon: '🌟',
    color: 'yellow',
    drugs: [
      {
        id: 'vitamina-d',
        name: 'Vitamina D3 (colecalciferol)',
        sinonimo: null,
        marcas: 'Addera D3, Colecalciferol',
        via: 'VO',
        dose_min: 400, dose_max: 1000, dose_max_abs: 4000, dose_dia_max: 1000, freq: 24,
        unidade: 'UI/dia',
        obs: 'Profilaxia: 400–600 UI/dia. Deficiência: 1000–2000 UI/dia × 3 meses. Raquitismo: 1000–5000 UI/dia.',
        apresentacoes: [
          { label: 'Gotas 200 UI/gota', conc: 200, tipo: 'gotas', mL_por_unidade: null },
          { label: 'Gotas 400 UI/gota', conc: 400, tipo: 'gotas', mL_por_unidade: null },
          { label: 'Comp. 1000 UI', conc: 1000, tipo: 'comprimido' },
          { label: 'Comp. 2000 UI', conc: 2000, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'sulfato-ferroso',
        name: 'Sulfato Ferroso',
        sinonimo: 'Ferro elementar',
        marcas: 'Ibifol, Noripurum',
        via: 'VO',
        dose_min: 3, dose_max: 6, dose_max_abs: 200, dose_dia_max: 6, freq: 24,
        unidade: 'mg/kg/dia de ferro elementar',
        obs: 'Anemia ferropriva: 3–6 mg/kg/dia de Fe elementar ÷ 1–3. Profilaxia: 1–2 mg/kg/dia. Em jejum para melhor absorção.',
        apresentacoes: [
          { label: 'Gotas 25 mg/mL Fe elementar', conc: 25, tipo: 'mL' },
          { label: 'Comp. 40 mg Fe elementar (200 mg sulfato)', conc: 40, tipo: 'comprimido' },
          { label: 'Xarope 25 mg/5 mL Fe elementar', conc: 5, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'acido-folico',
        name: 'Ácido Fólico',
        sinonimo: null,
        marcas: 'Acifol, Ácido Fólico',
        via: 'VO',
        dose_min: 0.05, dose_max: 0.1, dose_max_abs: 1, dose_dia_max: 0.1, freq: 24,
        unidade: 'mg/kg/dia',
        obs: 'Deficiência: 0,5–1 mg/dia. Anemia megaloblástica: 1–5 mg/dia. Prevenção (gestante): 0,4–4 mg/dia.',
        apresentacoes: [
          { label: 'Comp. 0,4 mg', conc: 0.4, tipo: 'comprimido' },
          { label: 'Comp. 1 mg', conc: 1, tipo: 'comprimido' },
          { label: 'Comp. 5 mg', conc: 5, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
      {
        id: 'vitamina-a',
        name: 'Vitamina A',
        sinonimo: null,
        marcas: 'Arovit, Vitamina A',
        via: 'VO/IM',
        dose_min: 50000, dose_max: 200000, dose_max_abs: 200000, dose_dia_max: 200000, freq: 24,
        unidade: 'UI/dose',
        obs: 'Sarampo: < 6 m: 50.000 UI × 2. 6–12 m: 100.000 UI × 2. > 12 m: 200.000 UI × 2. Xeroftalmia: 200.000 UI/dose.',
        apresentacoes: [
          { label: 'Cápsula 200.000 UI', conc: 200000, tipo: 'comprimido' },
          { label: 'Solução gotas 50.000 UI/mL', conc: 50000, tipo: 'mL' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 1,
      },
    ],
  },

  // ─────────────────────────────────────────
  // 15. EMERGÊNCIA
  // ─────────────────────────────────────────
  {
    id: 'outros-emergencia',
    label: 'Drogas de Emergência',
    icon: '🚨',
    color: 'red',
    drugs: [
      {
        id: 'morfina',
        name: 'Morfina',
        sinonimo: null,
        marcas: 'Dimorf, Morfina',
        via: 'EV/SC',
        dose_min: 0.05, dose_max: 0.1, dose_max_abs: 5, dose_dia_max: null, freq: 4,
        unidade: 'mg/kg/dose',
        obs: 'Dor moderada a grave: 0,05–0,1 mg/kg/dose EV lento × 4–6/dia. Neonatos: 0,05 mg/kg/dose.',
        apresentacoes: [
          { label: 'Ampola 10 mg/mL', conc: 10, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL (diluída)', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar respiração. Ter naloxona disponível.',
      },
      {
        id: 'ketamina',
        name: 'Cetamina (Ketamina)',
        sinonimo: null,
        marcas: 'Ketalar, Ketamin',
        via: 'EV/IM',
        dose_min: 1, dose_max: 2, dose_max_abs: 500, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Sedação/analgesia: EV 1–2 mg/kg (infundir em 1–2 min); IM 4–5 mg/kg. Broncodilatador em asma refratária.',
        apresentacoes: [
          { label: 'Ampola 10 mg/mL (EV)', conc: 10, tipo: 'mL' },
          { label: 'Ampola 50 mg/mL (IM)', conc: 50, tipo: 'mL' },
        ],
        alerta: '⚠️ Pode causar laringoespasmo. Manter via aérea acessível. Associar midazolam.',
      },
      {
        id: 'fentanil',
        name: 'Fentanil',
        sinonimo: null,
        marcas: 'Fentanil, Durogesic',
        via: 'EV/IN',
        dose_min: 1, dose_max: 2, dose_max_abs: 200, dose_dia_max: null, freq: null,
        unidade: 'mcg/kg/dose',
        obs: 'Analgesia: 1–2 mcg/kg EV lento. Intransal: 1,5–2 mcg/kg. Intubação: 2–4 mcg/kg.',
        apresentacoes: [
          { label: 'Ampola 50 mcg/mL (10 mL = 0,5 mg)', conc: 0.05, tipo: 'mL' },
        ],
        alerta: '⚠️ Monitorar FR. Ter naloxona disponível. Rigidez torácica se infusão rápida.',
      },
      {
        id: 'atropina',
        name: 'Atropina',
        sinonimo: null,
        marcas: 'Atropina',
        via: 'EV/IM',
        dose_min: 0.01, dose_max: 0.02, dose_max_abs: 0.5, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Bradicardia: 0,01–0,02 mg/kg EV (mín 0,1 mg, máx 0,5 mg/dose). PCR: 0,02 mg/kg.',
        apresentacoes: [
          { label: 'Ampola 0,5 mg/mL', conc: 0.5, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '🚨 Dose mínima 0,1 mg (evitar bradicardia paradoxal).',
      },
      {
        id: 'adenosina',
        name: 'Adenosina',
        sinonimo: null,
        marcas: 'Adenocor, Adenosina',
        via: 'EV (bolus rápido)',
        dose_min: 0.1, dose_max: 0.3, dose_max_abs: 12, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'TSV: 0,1 mg/kg bolus rápido EV; se não reverter, 0,2 mg/kg; máx 0,3 mg/kg (máx 12 mg). Imediatamente após: SF em bolus.',
        apresentacoes: [
          { label: 'Ampola 3 mg/mL (2 mL = 6 mg)', conc: 3, tipo: 'mL' },
        ],
        alerta: '🚨 Bolus EV rápido seguido de flush SF. Meia-vida < 10 segundos.',
      },
      {
        id: 'amiodarona',
        name: 'Amiodarona',
        sinonimo: null,
        marcas: 'Ancoron, Cordarone',
        via: 'EV/VO',
        dose_min: 5, dose_max: 15, dose_max_abs: 300, dose_dia_max: 30, freq: null,
        unidade: 'mg/kg/dose (ataque EV)',
        obs: 'Arritmia/PCR: 5 mg/kg EV. Taquicardia ventricular: 5 mg/kg em 30 min. Infusão contínua: 5–15 mcg/kg/min.',
        apresentacoes: [
          { label: 'Ampola 50 mg/mL (3 mL = 150 mg)', conc: 50, tipo: 'mL' },
          { label: 'Comp. 200 mg (VO)', conc: 200, tipo: 'comprimido' },
        ],
        alerta: '⚠️ Fototóxico, tireotóxico, hepatotóxico com uso prolongado.',
      },
      {
        id: 'furosemida',
        name: 'Furosemida',
        sinonimo: null,
        marcas: 'Lasix',
        via: 'EV/IM/VO',
        dose_min: 0.5, dose_max: 2, dose_max_abs: 40, dose_dia_max: 6, freq: 12,
        unidade: 'mg/kg/dose',
        obs: 'Edema/IRA: 0,5–2 mg/kg/dose × 1–2/dia. VO: 1–4 mg/kg/dia ÷ 1–2. Infundir lentamente.',
        apresentacoes: [
          { label: 'Ampola 10 mg/mL (2 mL = 20 mg)', conc: 10, tipo: 'mL' },
          { label: 'Comp. 40 mg', conc: 40, tipo: 'comprimido' },
          { label: 'Solução oral 10 mg/mL', conc: 10, tipo: 'mL' },
        ],
        alerta: null,
      },
      {
        id: 'naloxona',
        name: 'Naloxona',
        sinonimo: null,
        marcas: 'Narcan',
        via: 'EV/IM/IN',
        dose_min: 0.01, dose_max: 0.1, dose_max_abs: 2, dose_dia_max: null, freq: null,
        unidade: 'mg/kg/dose',
        obs: 'Reversão opioides: 0,01–0,1 mg/kg EV/IM (máx 2 mg). Repetir a cada 2–3 min. Titular pela resposta.',
        apresentacoes: [
          { label: 'Ampola 0,4 mg/mL', conc: 0.4, tipo: 'mL' },
          { label: 'Ampola 1 mg/mL', conc: 1, tipo: 'mL' },
        ],
        alerta: '⚠️ Meia-vida curta — pode precisar repetir. Monitorar rebote de depressão resp.',
      },
      {
        id: 'glicose',
        name: 'Glicose (hipoglicemia)',
        sinonimo: 'Dextrose',
        marcas: 'Soro Glicosado',
        via: 'EV',
        dose_min: 0.2, dose_max: 0.5, dose_max_abs: 25, dose_dia_max: null, freq: null,
        unidade: 'g/kg/dose (EV)',
        obs: 'Hipoglicemia: 0,25 g/kg EV = 2,5 mL/kg de SG 10% ou 1 mL/kg de SG 25%. Repetir se necessário.',
        apresentacoes: [
          { label: 'SG 10% (100 mg/mL = 0,1 g/mL)', conc: 100, tipo: 'mL' },
          { label: 'SG 25% (250 mg/mL = 0,25 g/mL)', conc: 250, tipo: 'mL' },
          { label: 'SG 50% (500 mg/mL = 0,5 g/mL)', conc: 500, tipo: 'mL' },
        ],
        alerta: '🚨 Nunca usar SG 50% puro em crianças — diluir.',
      },
    ],
  },

  // ─────────────────────────────────────────
  // 16. PROBIÓTICOS / ANTIFLATULENTES
  // ─────────────────────────────────────────
  {
    id: 'probioticos',
    label: 'Probióticos e Antiflatulentes',
    icon: '🦠',
    color: 'green',
    drugs: [
      {
        id: 'simeticona',
        name: 'Simeticona',
        sinonimo: null,
        marcas: 'Luftal, Mylicon',
        via: 'VO',
        dose_min: 2.5, dose_max: 5, dose_max_abs: 120, dose_dia_max: 20, freq: 8,
        unidade: 'mg/kg/dose',
        obs: 'Cólicas/gases: 2,5–5 mg/kg/dose × 3–4/dia. Bebê: 20 mg (≈ 0,3 mL) após mamada. Gotas 75 mg/mL.',
        apresentacoes: [
          { label: 'Gotas 75 mg/mL', conc: 75, tipo: 'mL' },
          { label: 'Cápsula 125 mg', conc: 125, tipo: 'comprimido' },
        ],
        alerta: null,
      },
      {
        id: 'saccharomyces-boulardii',
        name: 'Saccharomyces boulardii',
        sinonimo: null,
        marcas: 'Floratil, Reflor',
        via: 'VO',
        dose_min: 200, dose_max: 250, dose_max_abs: 500, dose_dia_max: 500, freq: 12,
        unidade: 'mg/dia ÷ 2',
        obs: 'Diarreia aguda: 200 mg × 2/dia × 5–10 dias. Prevenção diarreia por ATB: 250 mg × 2/dia.',
        apresentacoes: [
          { label: 'Cápsula 200 mg', conc: 200, tipo: 'comprimido' },
          { label: 'Sachê 200 mg', conc: 200, tipo: 'comprimido' },
        ],
        alerta: null,
        dose_por_dia: true, doses_por_dia: 2,
      },
    ],
  },
];

export function getAllDosagens() {
  return DOSAGENS_CATEGORIAS.flatMap(cat =>
    cat.drugs.map(d => ({ ...d, catLabel: cat.label, catColor: cat.color, catIcon: cat.icon, catId: cat.id }))
  );
}