export const antifungicosPolienicos = [
  {
    id: 'anfotericina-b',
    name: 'Anfotericina B convencional',
    category: 'antifungicos-polienicos',
    observations: 'Antifúngico poliênico de primeira escolha para infecções fúngicas graves: aspergilose, blastomicose, sepse por Candida, candidíase sistêmica, criptococose disseminada, histoplasmose, mucormicose e fusariose. Não tem boa penetração no SNC. Preferir azólicos ou equinocandinas quando possível para evitar lesão renal.',
    brands: ['Anforicin B / Fungison — Fr. amp. 50 mg'],
    presentations: [{ label: 'Frasco-ampola 50 mg' }],
    doses: [
      {
        group: 'Crianças',
        items: [
          { label: 'Dose usual EV', value: '0,25–0,5 mg/kg/dia, podendo chegar a 1 mg/kg/dia em neonatos. Não ultrapassar 1,5 mg/kg/dia ou 50 mg/dia' },
          { label: 'Calazar / leishmaniose visceral', value: '1 mg/kg/dia por 15–20 dias (ou alternados por 1 mês)' },
          { label: 'Leishmaniose cutânea', value: '30–50 mg/kg de dose acumulada' },
          { label: 'Candidíase oral na AIDS', value: '0,3–0,5 mg/kg/dia por 7 dias' },
          { label: 'Candidíase sistêmica na AIDS', value: '0,5–1,5 mg/kg/dia por 6–8 semanas' },
          { label: 'Candidíase esofágica', value: '0,3–0,7 mg/kg/dia até dose acumulada de 10 mg/kg' },
          { label: 'Candidíase neonatal', value: '1 mg/kg/dia' },
          { label: 'Sepse fúngica', value: '0,5–1 mg/kg/dia' },
          { label: 'Endocardite por Candida ou aspergilose', value: '1 mg/kg/dia por 6–8 semanas' },
          { label: 'Cistite por Candida resistente ao fluconazol', value: '0,3–0,6 mg/kg/dose por 1–7 dias' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Dose usual EV', value: '0,5–0,7 mg/kg/dia (pode variar 0,3–1,5 mg/kg/dia; máx 50 mg/dia)' },
          { label: 'Aspergilose disseminada', value: '0,5–0,7 mg/kg/dia por 3–6 meses' },
          { label: 'Blastomicose grave', value: '0,7–1 mg/kg/dia por 1–2 semanas; depois itraconazol por 6–12 meses' },
          { label: 'Candidíase disseminada grave', value: '0,7 mg/kg/dia nos não neutropênicos' },
          { label: 'Candidíase esofágica / cistite por Candida', value: '0,5 mg/kg/dia por 7–14 dias' },
          { label: 'Endocardite / miocardite por Candida', value: '0,6–1 mg/kg/dia + flucitosina 25 mg/kg/dose 4×/dia' },
          { label: 'Coccidioidomicose grave', value: '0,6–1 mg/kg/dia por 7 dias; depois 0,8 mg/kg/dia alternados' },
          { label: 'Criptococose — alternativa', value: '0,3 mg/kg/dia + flucitosina por 6 semanas' },
          { label: 'Histoplasmose disseminada', value: '0,7–1 mg/kg/dia até acumular 35 mg/kg; seguido de itraconazol' },
          { label: 'Paracoccidioidomicose disseminada', value: '0,4–0,5 mg/kg/dia até acumular 35 mg/kg' },
          { label: 'Mucormicose', value: '1–1,5 mg/kg/dia até acumular 2,5 g' },
          { label: 'Intratecal — meningite fúngica', value: 'Iniciar 25–300 µg a cada 2–3 dias; aumentar até 0,5–1 mg/dose' },
        ],
      },
    ],
    preparation: 'Infundir em 4–6 horas. Usar água destilada para reconstituição; depois diluir em SGI 5% ou 10%. Não usar SF. Proteger da luz. Pode haver calafrios, febre, taquicardia e dispneia durante a infusão — usar paracetamol, anti-histamínico e/ou hidrocortisona para prevenir reações.',
    renalAdjustment: [
      { label: 'Insuficiência renal', value: 'Não exige correção; pode ser necessário reduzir 50% ou usar dias alternados se houver toxicidade importante' },
    ],
    sensitivity: {
      susceptible: ['Candida, Aspergillus, Cryptococcus, Histoplasma, Blastomyces, Coccidioides, Paracoccidioides, Mucor, Fusarium, Leishmania'],
      resistant: [],
      warning: '',
    },
    sideEffects: [
      'Reação febril aguda, calafrios, tremores, cefaleia, vômitos, taquicardia, hipotensão',
      'Dor óssea, flebite, nefrotoxicidade, distúrbios hidroeletrolíticos',
      'Hipocalemia, hipomagnesemia, anemia, hepatotoxicidade',
      'Diarreia, dispepsia, perda de peso, arritmia',
      'Convulsão, parestesia, anafilaxia',
    ],
    contraindications: [],
  },
  {
    id: 'anfotericina-b-lipossomal',
    name: 'Anfotericina B lipossomal',
    category: 'antifungicos-polienicos',
    observations: 'Antifúngico poliênico. Por ser menos nefrotóxico, é alternativa ao desoxicolato, especialmente em pacientes com insuficiência renal.',
    brands: ['Ambisome — Fr. amp. 50 mg'],
    presentations: [{ label: 'Frasco-ampola 50 mg' }],
    doses: [
      {
        group: 'Adultos e crianças',
        items: [
          { label: 'Dose usual', value: 'EV: 3–5 mg/kg/dia' },
          { label: 'Aspergilose invasiva / candidíase disseminada', value: '3–5 mg/kg/dia' },
          { label: 'Blastomicose / candidíase', value: '3–5 mg/kg/dia até melhora; depois itraconazol' },
          { label: 'Blastomicose com comprometimento meníngeo', value: '5 mg/kg/dia por 4–6 semanas; depois fluconazol' },
          { label: 'Coccidioidomicose', value: '3–5 mg/kg/dia até melhora; depois itraconazol' },
          { label: 'Endoftalmite, infecção cardiovascular ou SNC por Candida', value: '3–5 mg/kg/dia + flucitosina 25 mg/kg/dose 4×/dia' },
          { label: 'Histoplasmose disseminada', value: '3 mg/kg/dia até melhora; depois itraconazol' },
          { label: 'Mucormicose', value: '5–10 mg/kg/dia' },
          { label: 'Osteomielite / artrite por Candida', value: '3–5 mg/kg/dia até melhora; depois fluconazol' },
        ],
      },
    ],
    preparation: 'Reconstituir em 12 mL de ABD; agitar vigorosamente, aspirar com filtro e diluir em SGI. Infundir em 2 horas. Armazenar sob refrigeração.',
    sensitivity: {
      susceptible: ['Candida, Aspergillus, Cryptococcus, Histoplasma, Blastomyces, Coccidioides, Mucor'],
      resistant: [],
      warning: '',
    },
    sideEffects: [
      'Hipopotassemia, hipomagnesemia, hipocalcemia, anemia, trombocitopenia, leucopenia',
      'Transaminases e bilirrubinas aumentadas, diarreia, náusea, vômitos',
      'Febre, cefaleia, calafrio, dor lombar, disfunção respiratória',
      'Disfunção renal, acidose tubular, erupção cutânea, prurido',
      'Hipotensão, arritmia, dor torácica, vasodilatação, parada cardíaca',
    ],
    contraindications: [],
  },
  {
    id: 'anfotericina-b-complexo-lipidico',
    name: 'Anfotericina B complexo lipídico',
    category: 'antifungicos-polienicos',
    observations: 'Formulação lipídica da anfotericina B. Menos nefrotóxica que a convencional.',
    brands: ['Abelcet — Fr. amp. 5 mg/mL'],
    presentations: [{ label: 'Frasco-ampola 5 mg/mL' }],
    doses: [
      {
        group: 'Crianças e Adultos',
        items: [
          { label: 'Dose usual', value: '5 mg/kg/dia' },
          { label: 'Aspergilose invasiva / candidíase disseminada', value: '5 mg/kg/dia por até 14 dias' },
          { label: 'Osteomielite / artrite por Candida', value: '3–5 mg/kg/dia até melhora; depois fluconazol' },
          { label: 'Aspergilose resistente', value: '4 mg/kg/dose' },
          { label: 'Calazar resistente (< 5 anos)', value: '2 mg/kg/dia por 7 dias' },
          { label: 'Paracoccidioidomicose disseminada', value: '4–5 mg/kg/dia até melhora; depois itraconazol' },
          { label: 'Candidíase neonatal', value: '3–5 mg/kg/dia' },
        ],
      },
    ],
    preparation: 'Agitar suavemente. Aspirar com agulha 18 e diluir em glicose. Não misturar com outros medicamentos. Armazenar refrigerado e protegido da luz.',
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sensitivity: {
      susceptible: ['Candida, Aspergillus, Cryptococcus, Histoplasma, Paracoccidioides, Leishmania'],
      resistant: [],
      warning: '',
    },
    sideEffects: [
      'Hipotensão, taquicardia, arritmias, parada cardíaca (rara)',
      'Febre, calafrios, hepatotoxicidade, prurido, anafilaxia',
      'Náusea, vômitos, dor abdominal, anorexia, hiperbilirrubinemia, hemorragia digestiva',
      'Anemia, leucopenia, trombocitopenia, acidose tubular, disfunção renal',
    ],
    contraindications: [],
  },
  {
    id: 'nistatina',
    name: 'Nistatina',
    category: 'antifungicos-polienicos',
    observations: 'Antifúngico para uso tópico (pele e mucosas) e oral (ação dentro do trato GI). Não é absorvido por via oral.',
    brands: ['Nistatina — gotas 100.000 UI/mL'],
    presentations: [{ label: 'Gotas 100.000 UI/mL' }],
    doses: [
      {
        group: 'Crianças — Candidíase oral',
        items: [
          { label: 'Neonatos', value: '100.000 UI/dose 4×/dia' },
          { label: 'Lactentes', value: '200.000–400.000 UI/dose 4×/dia' },
          { label: 'Crianças', value: '400.000–600.000 UI/dose 4×/dia' },
          { label: 'Duração', value: '10–14 dias ou até 2 dias após resolução completa. Meia dose em cada lado da boca.' },
          { label: 'Candidíase intestinal', value: 'Usar dose dobrada ou triplicada' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Candidíase oral', value: '400.000–600.000 UI (4–6 mL/dose) 4×/dia; manter na boca antes de engolir' },
          { label: 'Candidíase oral grave/recorrente', value: 'Considerar associar fluconazol' },
          { label: 'Candidíase intestinal', value: '500.000–1.000.000 UI a cada 8 horas' },
        ],
      },
    ],
    sensitivity: {
      susceptible: ['Candida albicans e espécies relacionadas'],
      resistant: [],
      warning: 'Pesquisar AIDS e outras imunodeficiências em casos crônicos ou atípicos.',
    },
    sideEffects: [
      'Praticamente atóxica',
      'Diarreia, náusea e vômitos em doses altas',
    ],
    contraindications: [],
  },
];