export const corticosteroides = [
  {
    id: 'betametasona',
    name: 'Betametasona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação longa (36–55 h), com maior potência anti-inflamatória e menor retenção de sódio. 1 mg = 8,33 mg de prednisona. O fosfato é solução aquosa (EV/IM); os sais de acetato e dipropionato são suspensões de absorção lenta para uso exclusivo IM.',
    brands: [
      'Celestone / Betametasona — comp. 0,5 e 2 mg; gotas 0,5 mg/mL; elixir 0,5 mg/5 mL; ampola 4 mg/mL',
      'Fosfato + acetato de betametasona — sol. inj. 3 + 3 mg/mL',
      'Fosfato + dipropionato de betametasona — ampola 1+2 mg/mL ou 2+5 mg/mL',
    ],
    presentations: [
      { label: 'Comprimido 0,5 mg e 2 mg' },
      { label: 'Gotas 0,5 mg/mL (1 gota = 0,02 mg)' },
      { label: 'Elixir 0,5 mg/5 mL' },
      { label: 'Ampola 4 mg/mL' },
    ],
    doses: [
      {
        group: 'Crianças',
        items: [
          { label: 'Dose habitual oral/IM', value: '0,02–0,3 mg/kg/dia ou 0,5–8 mg/m²/dia ÷ 2–4 doses' },
          { label: 'Equivalência (1 mg/kg de prednisona)', value: '0,12 mg/kg/dia' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório / imunossupressor — IM', value: '0,25–9 mg/dia a cada 1–4 semanas' },
          { label: 'Anti-inflamatório / imunossupressor — oral', value: '0,25–9 mg/dia ÷ 1–4 doses semanais' },
          { label: 'Corticoterapia antenatal (parto prematuro)', value: 'IM: 2 doses de 12 mg com 24 h de intervalo' },
          { label: 'Artrite reumatoide / osteoartrites', value: 'Oral: 0,5–2 mg/dose 1–4×/dia' },
          { label: 'Intra-articular — grandes articulações', value: '6–12 mg' },
          { label: 'Intra-articular — médias articulações', value: '3–8 mg' },
          { label: 'Intra-articular — pequenas articulações', value: '1,5–3 mg' },
          { label: 'Bursite / tendinite / tenossinovite (intrabursal)', value: '6 mg/dia. Repetir após 1–2 semanas se necessário.' },
          { label: 'Lesões dermatológicas — oral', value: 'Iniciar 2–3 mg/dia. Reduzir 0,25–0,5 mg a cada 2–5 dias.' },
          { label: 'Intralesional', value: '1,2 mg/cm². Máx: 6 mg/semana' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Vertigem', 'Adinamia', 'Excitação', 'Agitação', 'Depressão', 'Distúrbios do sono', 'Convulsão',
      'Vômitos', 'Náusea', 'Úlcera', 'Gastrite', 'Edema', 'Hipertensão', 'Hiperhidrose', 'Acne',
      'Hipotrofia da pele', 'Anemia', 'Leucocitose', 'Neutrofilia', 'Alcalose hipocalêmica',
      'Intolerância à glicose', 'Hiperglicemia', 'Glicosúria',
      'Uso prolongado: retardo do crescimento, ganho de peso, hirsutismo, imunodepressão, supressão do eixo hipófise-adrenal',
      'Osteoporose e fraturas', 'Atrofia muscular', 'Hiperlipidemia', 'Síndrome de Cushing',
      'Doença de Addison', 'Catarata', 'Glaucoma', 'Dificuldade de cicatrização', 'Trombose',
      'Pancreatite aguda', 'Pseudotumor cerebral', 'Hipertensão intracraniana',
      'Miocardiopatia hipertrófica', 'Amenorreia',
      'Aumento do risco de enterocolite em prematuros',
    ],
    contraindications: [
      'Gravidez', 'Lactação', 'Insuficiência hepática', 'Hipertensão não controlada',
      'Diabetes', 'Atrofia muscular', 'Osteoporose', 'Úlcera gástrica',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: 'Tomar pela manhã em dose única com água. Retirar gradualmente após > 7–14 dias ou doses > 3 mg/dia. Suplementar vitaminas, potássio, cálcio. Restringir sódio.' },
  },
  {
    id: 'deflazacorte',
    name: 'Deflazacorte',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação intermediária (12–36 h). Escolha para pacientes com osteoporose ou diabetes. 1 mg = 0,83 mg de prednisona.',
    brands: ['Calcort / Deflanil / Deflazacorte — comp. 6, 7,5 e 30 mg'],
    presentations: [
      { label: 'Comprimido 6 mg' },
      { label: 'Comprimido 7,5 mg' },
      { label: 'Comprimido 30 mg' },
    ],
    doses: [
      {
        group: 'Crianças',
        items: [
          { label: 'Dose habitual', value: '0,22–1,65 mg/kg/dia' },
          { label: 'Distrofia muscular de Duchenne (> 5 anos)', value: '0,9 mg/kg/dia' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório', value: '6–90 mg/dia conforme gravidade. Manutenção: 6–18 mg/dia' },
          { label: 'Doença de Crohn', value: '45–60 mg/dia por até 3 meses' },
          { label: 'Distrofia de Duchenne', value: '0,9 mg/kg/dia' },
          { label: 'Orientação', value: 'Tomar pela manhã em dose única com água. Doses > 30 mg/dia são altas e devem ser retiradas gradualmente.' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Agitação', 'Psicose', 'Dispepsia', 'Dor abdominal', 'Úlcera péptica',
      'Hemorragia gástrica', 'Pancreatite', 'Hipertensão', 'Hiperglicemia',
      'Catarata', 'Glaucoma', 'Hirsutismo', 'Fraqueza muscular', 'Aumento de apetite',
      'Ganho de peso', 'Síndrome de Cushing',
    ],
    contraindications: ['Infecção não controlada', 'Atrofia muscular', 'Úlcera gástrica'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'dexametasona',
    name: 'Dexametasona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação longa (36–55 h), com maior potência anti-inflamatória e ação mineralocorticoide mínima. 1 mg = 6,25 mg de prednisona. Fosfato: solução aquosa (EV/IM). Acetato: suspensão de absorção lenta para uso IM em adultos — não usar EV. EV > 10 mg: diluir em SGI 5% ou SF para correr em 30 min; doses menores: bolus em 1–5 min.',
    brands: [
      'Decadron / Dexametasona — comp. 0,5/0,75/4 mg; elixir 0,5 mg/5 mL',
      'Fosfato dissódico de dexametasona — ampola 2 mg/mL e 4 mg/mL',
      'Acetato de dexametasona — suspensão intra-articular 16 mg/mL',
    ],
    presentations: [
      { label: 'Comprimido 0,5 mg; 0,75 mg; 4 mg' },
      { label: 'Elixir 0,5 mg/5 mL' },
      { label: 'Ampola 2 mg/mL e 4 mg/mL' },
    ],
    doses: [
      {
        group: 'Crianças — Anti-inflamatório / antialérgico',
        items: [
          { label: 'Dose', value: '0,08–0,30 mg/kg/dia ou 2–10 mg/m²/dia ÷ 2–4 doses' },
        ],
      },
      {
        group: 'Crianças — Indicações específicas',
        items: [
          { label: 'Edema cerebral', value: 'Ataque: 1–2 mg/kg; manutenção: 1–1,5 mg/kg/dia a cada 4–6 h por 5 dias, depois retirada progressiva. Máx: 16 mg/dia' },
          { label: 'Crupe / edema de glote (oral/EV/IM)', value: '0,6 mg/kg em dose única' },
          { label: 'Displasia broncopulmonar — facilitar extubação', value: '1º dia: 0,2–0,25 mg/kg/dia ÷ 2; 2º: 0,15 mg/kg/dia ÷ 2; 3º: 0,1 mg/kg/dia ÷ 2; até 5º dia se necessário' },
          { label: 'Meningite bacteriana', value: '0,15 mg/kg/dose 4×/dia por 4 dias (16 doses). Iniciar 30 min antes dos antibióticos.' },
          { label: 'Vômito por quimioterapia', value: '10 mg/m²/dose antes; depois 5 mg/m²/dose 4×/dia' },
          { label: 'Profilaxia de falha de extubação (RN)', value: '0,25 mg/kg/dose a cada 8 h. Máx: 1 mg/kg/dia' },
          { label: 'Leucemia linfoblástica aguda (oral)', value: '4–6 mg/m²/dia por 28–35 dias' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: '0,5–9 mg/dia ÷ 2–4 doses. IM acetato: 8–16 mg a cada 1–3 semanas' },
          { label: 'Corticoterapia antenatal (parto prematuro)', value: 'IM fosfato: 6 mg a cada 12 h por 2 dias (4 doses no total)' },
          { label: 'Edema cerebral', value: 'EV: 10 mg em dose inicial; depois 4 mg a cada 6 h' },
          { label: 'Hipertensão intracraniana por metástase', value: '16–24 mg/dia por 2–8 dias' },
          { label: 'Choque refratário', value: 'EV: 1–6 mg/kg. Máx: 40 mg em dose única; pode usar 4–8 mg a cada 6 h' },
          { label: 'Mieloma múltiplo', value: '40 mg/dia EV ou oral nos dias 1–4, 9–12 e 17–20 a cada 4 semanas' },
          { label: 'Púrpura trombocitopênica imunológica', value: 'Oral: 40 mg 1×/dia por 5 dias' },
          { label: 'Crise tireotóxica', value: 'EV: 2–4 mg/dose a cada 6 h' },
          { label: 'Profilaxia de vômitos por quimioterapia', value: 'EV/oral: 10–20 mg 30 min antes; depois 8 mg 2×/dia → 4 mg 2×/dia por 2 dias' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Vertigem', 'Adinamia', 'Excitação', 'Agitação', 'Insônia', 'Nervosismo', 'Psicose', 'Convulsão',
      'Vômitos', 'Náusea', 'Diarreia', 'Dispepsia', 'Úlcera péptica', 'Gastrite',
      'Edema', 'Hipertensão', 'Hiperhidrose', 'Acne', 'Hipotrofia da pele',
      'Leucocitose', 'Alcalose hipocalêmica', 'Hiperglicemia', 'Glicosúria',
      'Uso prolongado: retardo do crescimento, ganho de peso, imunodepressão, supressão do eixo hipófise-adrenal, osteoporose e fraturas',
      'Retenção de sódio e água', 'Hiperlipidemia', 'Síndrome de Cushing',
      'Fácies de lua cheia', 'Estrias', 'Hirsutismo', 'Catarata', 'Glaucoma',
      'Dificuldade de cicatrização', 'Trombose', 'Pancreatite', 'Pseudotumor cerebral',
      'Hipertensão intracraniana', 'Miocardiopatia hipertrófica', 'Amenorreia',
      'Aumento do risco de enterocolite em prematuros',
      'Síndrome pós-retirada: febre, mialgia, artralgia, mal-estar, hipotensão, hipoglicemia e choque',
    ],
    contraindications: [
      'Infecções não controladas (herpes, varicela, tuberculose, fungos)',
      'Diabetes', 'Atrofia muscular', 'Osteoporose não controlada', 'Úlcera gástrica',
      'Tuberculose ativa', 'Não usar acetato IM em crianças',
    ],
    sensitivity: {
      susceptible: [], resistant: [],
      warning: 'Não infundir EV junto com: amicacina, anfotericina, amiodarona, cálcio, cefuroxima, ciprofloxacino, diazepam, dobutamina, gentamicina, hidantoína, labetalol, midazolam, fenitoína, tobramicina, vancomicina.',
    },
  },
  {
    id: 'hidrocortisona',
    name: 'Hidrocortisona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação curta (8–12 h), com potência anti-inflamatória e mineralocorticoide equivalentes. 1 mg = 0,25 mg de prednisona. Após diluição, estável por 24 h em temperatura ambiente.',
    brands: [
      'Cortisonal / Androcortil / Hidrocortisona — frasco-ampola 100 e 500 mg',
      'Succinato sódico de hidrocortisona — frasco-ampola 100 mg e 500 mg',
    ],
    presentations: [
      { label: 'Frasco-ampola 100 mg' },
      { label: 'Frasco-ampola 500 mg' },
    ],
    doses: [
      {
        group: 'Crianças — Dose habitual',
        items: [
          { label: 'EV/IM', value: '0,16–1 mg/kg/dia ou 6–30 mg/m²/dia ÷ 1–2 doses' },
          { label: 'Dose fisiológica EV', value: '0,5–0,75 mg/kg/dia ou 10–25 mg/m²/dia ÷ 3–4 doses' },
          { label: 'Anti-inflamatório / imunossupressor', value: '1–5 mg/kg/dia ou 30–150 mg/m²/dia ÷ 1–2 doses' },
        ],
      },
      {
        group: 'Crianças — Indicações específicas',
        items: [
          { label: 'Hipoglicemia neonatal refratária', value: '5 mg/kg/min EV; depois 5 mg/kg/dia ÷ 2–3 doses' },
          { label: 'Hipotensão / choque neonatal', value: '1 mg/kg/dose a cada 2–3 h; ou 20–30 mg/m²/dia ÷ 2–3 doses' },
          { label: 'Hiperplasia adrenal congênita', value: 'EV: 7–9 mg/m²/dia ÷ 2–3 doses' },
          { label: 'Asma aguda grave', value: '4 mg/kg/dose a cada 6 h (se possível, usar via oral)' },
          { label: 'Choque séptico refratário a catecolaminas', value: 'EV inicial: 10 mg/kg (máx 200 mg); manutenção: 50 mg/m²/dia até suspensão do vasopressor' },
          { label: 'Insuficiência adrenal aguda (< 1 ano e 1–4 anos)', value: 'Bolus 25 mg; depois 25 mg/dia' },
          { label: 'Insuficiência adrenal aguda (> 4 anos)', value: 'Bolus 50 mg; depois 50 mg/dia' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: 'EV/IM: 15–240 mg/dose 2×/dia. Oral: 20–240 mg/dia manipulado' },
          { label: 'Dose fisiológica', value: '10–12 mg/m²/dia' },
          { label: 'Urgências (anafilaxia / interrupção de corticoide)', value: 'EV/IM: 100–500 mg/dose 3–4×/dia até estabilização' },
          { label: 'Asma aguda grave', value: 'EV inicial: 200–300 mg; manutenção: 100 mg a cada 3–4 h' },
          { label: 'Choque séptico refratário a vasopressor', value: 'EV: 200 mg/24 h; ou 50 mg a cada 6 h. Até suspensão do vasopressor' },
          { label: 'Crise tireotóxica', value: 'EV inicial: 300 mg; depois 100 mg a cada 6–8 h' },
          { label: 'Doença de Crohn aguda', value: 'EV: 100 mg/dose 3–4×/dia' },
          { label: 'Estresse cirúrgico leve', value: '20–25 mg antes da cirurgia' },
          { label: 'Estresse cirúrgico moderado', value: '50–75 mg antes + 25 mg 3×/dia de manutenção' },
          { label: 'Estresse cirúrgico elevado', value: '100–150 mg antes + 50 mg 3×/dia por 2–3 dias' },
          { label: 'Insuficiência adrenal aguda', value: 'EV: 100 mg inicial; depois infusão contínua de 10 mg/h; ou 50–100 mg IM/EV a cada 6 h' },
          { label: 'Retocolite ulcerativa grave', value: 'EV: 100 mg/dose 3×/dia' },
          { label: 'Reação transfusional', value: 'EV: 100–200 mg' },
          { label: 'Fadiga adrenal', value: 'Mulheres: 15–30 mg/dia; homens: 20–40 mg/dia' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Euforia', 'Excitação', 'Distúrbios do sono', 'Agitação', 'Psicose', 'Insônia',
      'Vômitos', 'Náusea', 'Úlcera péptica', 'Gastrite', 'Edema', 'Hipertensão', 'Hipopotassemia', 'Hiperglicemia',
      'Uso prolongado: retardo do crescimento, ganho de peso, hirsutismo, imunodepressão, supressão do eixo hipófise-adrenal',
      'Osteoporose e fraturas', 'Atrofia muscular', 'Hiperlipidemia', 'Síndrome de Cushing',
      'Obesidade típica', 'Fácies de lua cheia', 'Estrias', 'Acne', 'Hirsutismo',
      'Doença de Addison', 'Catarata', 'Glaucoma', 'Dificuldade de cicatrização', 'Trombose',
      'Pancreatite aguda', 'Pseudotumor cerebral', 'Hipertensão intracraniana',
      'Miopatia', 'Miocardiopatia hipertrófica', 'Amenorreia',
    ],
    contraindications: [
      'Infecção não controlada', 'Diabetes', 'Atrofia muscular',
      'Osteoporose não controlada', 'Úlcera gástrica', 'Tuberculose ativa',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: 'Não infundir EV associado a diazepam, fenobarbital ou vancomicina.' },
  },
  {
    id: 'metilprednisolona',
    name: 'Metilprednisolona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação intermediária (18–36 h). 1 mg = 1,25 mg de prednisona. Succinato sódico: solução aquosa (EV/IM). Sal de acetato: suspensão de absorção lenta — não usar EV. Doses > 250 mg EV: infundir lentamente (mín 30 min) diluído a 2,5–20 mg/mL em SF/SGI. Não usar intratecal.',
    brands: [
      'Solu-Medrol (succinato sódico) — fr-amp. 40, 125, 500 e 1000 mg',
      'Depo-Medrol (acetato) — fr-amp. 80 mg',
    ],
    presentations: [
      { label: 'Frasco-ampola 40 mg' },
      { label: 'Frasco-ampola 125 mg' },
      { label: 'Frasco-ampola 500 mg' },
      { label: 'Frasco-ampola 1000 mg' },
      { label: 'Frasco-ampola acetato 80 mg' },
    ],
    doses: [
      {
        group: 'Crianças > 1 mês',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: '0,11–1,6 mg/kg/dia ou 3,2–48 mg/m²/dia ÷ 3–4 doses' },
          { label: 'Dose fisiológica', value: '0,1–0,2 mg/kg/dia' },
          { label: 'Asma grave (EV/IM)', value: '1 mg/kg/dose 4×/dia; depois 1–2 mg/kg/dia ÷ 1–2 doses por 2–10 dias. Máx: 60 mg/dia. < 5 anos: 7,5 mg/kg/dia; > 5 anos: 240 mg/dia' },
          { label: 'Anafilaxia / reação alérgica grave', value: 'EV: 1–2 mg/kg/dia. Máx: 125 mg' },
          { label: 'Complicações reumáticas graves', value: 'EV: 10–30 mg/kg/dia em 1 h por 1–5 dias. Máx: 1 g/dia' },
          { label: 'Esclerose múltipla em exacerbação', value: '20–30 mg/kg/dia ÷ 2 doses. Máx: 1000 mg/dia por 3–5 dias' },
          { label: 'Pulsoterapia (nefrite lúpica, síndrome nefrótica grave, etc.)', value: 'EV: 30 mg/kg/dia ou 600–1000 mg/m²/dia por 3 dias' },
          { label: 'GVHD', value: 'EV: 1–2 mg/kg/dia 1×/dia por 5–7 dias; reduzir 10% da dose a cada 4 dias se melhora' },
          { label: 'Pneumonia pneumocística grave', value: 'EV: 1 mg/kg/dose 4×/dia → 2×/dia → 1×/dia. Até 12–16 dias. Iniciar em até 72 h do diagnóstico.' },
          { label: 'Trauma raquimedular', value: 'EV: 30 mg/kg/dose; depois 5,4 mg/kg/h por 23 h em infusão contínua' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: 'EV/IM succinato: 10–40 mg a cada 4–6 h por até 3 dias. IM acetato: 4–120 mg/dia. Oral: 2–60 mg/dia ÷ 1–4 doses' },
          { label: 'Anafilaxia / reação alérgica grave', value: 'EV: 125 mg em dose única' },
          { label: 'Asma grave', value: 'EV: 40–80 mg/dia 1–2 doses. IM acetato: 240 mg dose única. Oral: 40–60 mg/dia por 3–10 dias' },
          { label: 'Artrite reumatoide / osteoartrites intra-articular', value: 'Grande: 40–80 mg; Média: 20–40 mg; Pequena: 10–20 mg. Repetir a cada 3 meses.' },
          { label: 'Pulsoterapia EV', value: '1 g/dia em 2 h por até 3 dias' },
          { label: 'DPOC grave em exacerbação', value: 'EV: 40–125 mg/dose 1–4×/dia até via oral' },
          { label: 'Esclerose múltipla em exacerbação', value: 'EV: 1000 mg/dia por 3–5 dias' },
          { label: 'Pulsoterapia — nefrite do lúpus', value: 'EV: 500 mg/dia por 3 dias' },
          { label: 'Pulsoterapia — dermatomiosite / polimiosite / cardite reumática', value: 'EV: 1000 mg/dia por 3 dias, seguido de terapia oral' },
          { label: 'Síndrome nefrótica', value: 'EV: 1 g/dia por 3 dias, seguido de terapia oral' },
          { label: 'Imunossupressão em transplante', value: 'Hepático/pulmonar: 0,5–1 g EV intraoperatório; renal/cardíaco: 0,25–1 g EV intraoperatório. Manter por 3 dias.' },
          { label: 'Pneumonia pneumocística em imunodeprimidos', value: 'EV: 30 mg 2×/dia → 30 mg/dia → 15 mg/dia. Por 21 dias ou até 72 h após diagnóstico.' },
          { label: 'Histoplasmose pulmonar aguda', value: 'EV: 0,5–1 mg/kg por 1–2 semanas (com antifúngico)' },
          { label: 'Gota aguda', value: 'EV/IM: 0,5–2 mg/kg; repetir conforme resposta' },
          { label: 'Doença de Crohn', value: 'Enema por 6 sem; depois 250 mg 1×/semana por 6 sem; depois 250 mg 1×/semana por mais 6 sem' },
        ],
      },
    ],
    preparation: 'EV: reconstituir com diluente incluído (água + álcool benzílico) e aplicar em mín 5 min. Doses > 250 mg: diluir a 2,5–20 mg/mL em SF/SGI e infundir em mín 30 min. Após reconstituição: geladeira por até 48 h. Após diluição: usar em até 24 h. Não usar intratecal. Não usar acetato EV.',
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Vertigem', 'Psicose', 'Insônia', 'Depressão', 'Euforia', 'Convulsões',
      'Náusea', 'Úlcera', 'Gastrite', 'Edema', 'Hipertensão', 'Insuficiência cardíaca congestiva',
      'Hipopotassemia', 'Hiponatremia', 'Alcalose hipocalêmica', 'Hiperglicemia', 'Glicosúria',
      'Catarata', 'Glaucoma', 'Hipotrofia da pele', 'Inibição de cicatrização', 'Hirsutismo',
      'Uso prolongado: síndrome de Cushing, obesidade típica, fácies de lua cheia, estrias, acne, hirsutismo, retardo do crescimento, ganho de peso, imunossupressão, supressão do eixo hipófise-adrenal, insuficiência adrenal, osteoporose e fraturas',
      'Hipertensão intracraniana', 'Risco de AVC', 'Atrofia muscular', 'Hiperlipidemia',
      'Hipocalcemia', 'Hepatotoxicidade',
    ],
    contraindications: [
      'Infecções não controladas', 'Diabetes', 'Atrofia muscular', 'Osteoporose não controlada',
      'Úlcera gástrica', 'Tuberculose ativa',
      'Vacinas com vírus atenuados em doentes com doses imunossupressoras',
      'Diluente com álcool benzílico não deve ser usado em prematuros',
      'Não usar em PTI por via EV',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: 'Por via oral, tomar pela manhã com água e alimentos. Doses > 20 mg/dia são consideradas altas e devem ser retiradas gradualmente.' },
  },
  {
    id: 'prednisolona',
    name: 'Prednisolona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação intermediária (18–36 h). Primeira escolha para uso oral em crianças. Não precisa de conversão hepática — útil em hepatopatias (preferir em relação à prednisona). 1 gota = 0,55 mg.',
    brands: [
      'Prelone / Predsim / EMS Pred — sol. oral 15 mg/5 mL; comp. 5 e 20 mg; gotas 11 mg/mL',
      'Fosfato sódico de prednisolona — sol. oral 15 mg/5 mL',
    ],
    presentations: [
      { label: 'Comprimido 5 mg' },
      { label: 'Comprimido 20 mg' },
      { label: 'Solução oral 15 mg/5 mL' },
      { label: 'Gotas 11 mg/mL (1 gota = 0,55 mg)' },
    ],
    doses: [
      {
        group: 'Crianças',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: '0,1–2 mg/kg/dia. Máx: 60 mg/dia' },
          { label: 'Anafilaxia / reação alérgica grave', value: '0,5–1 mg/kg. Máx: 60 mg' },
          { label: 'Asma grave', value: '1–2 mg/kg/dose a cada 12 h por até 5 dias. Máx: 60 mg/dia' },
          { label: 'Cardite reumática', value: '2 mg/kg/dia ÷ 1–4 doses. Máx: 80 mg/dia por 10–21 dias' },
          { label: 'Síndrome nefrótica — etapa 1', value: '60 mg/m²/dia ou 2 mg/kg/dia ÷ 1–4 doses. Máx: 60 mg/dia' },
          { label: 'Síndrome nefrótica — etapa 2', value: '40 mg/m² ou 1,5 mg/kg em dias alternados por 2–5 meses (reduzir 10 mg/m² a cada 2 dias)' },
          { label: 'Púrpura trombocitopênica', value: '1–4 mg/kg/dia. Máx: 14 dias' },
          { label: 'Sarcoidose', value: '1–2 mg/kg/dia por 2–3 meses (máx 40 mg/dia); redução gradual 6–12 meses; manutenção 5–10 mg/dia' },
          { label: 'Distrofia muscular de Duchenne', value: '0,75 mg/kg/dia por 1–10 dias mensalmente' },
          { label: 'Leucemia linfoblástica aguda', value: '40 mg/m²/dia por 28 dias' },
          { label: 'Profilaxia de alergia a contraste iodado', value: '0,5–0,7 mg/kg/dose (máx 50 mg): 13h, 7h e 1h antes. + difenidramina 1,25 mg/kg 1h antes.' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Anti-inflamatório / imunossupressor', value: '5–60 mg/dia 1×/manhã' },
          { label: 'Artrite reumatoide', value: '0,3 mg/kg/dia ÷ 2–3 doses; casos graves: 1 mg/kg/dia' },
          { label: 'Asma, crise refratária', value: '2–5 mg/kg/dia; depois 1 mg/kg/dia ou 40–50 mg/dia ÷ 1–2 doses por 2 dias; reduzir 10 mg/dia e suspender no 6º dia' },
          { label: 'Cardite reumática aguda', value: '60–80 mg/dia por 6 semanas, depois redução gradual' },
          { label: 'Doença de Crohn', value: '40–60 mg/dia 1–2×/dia' },
          { label: 'Exacerbações de DPOC', value: '30–40 mg/dia 1×/dia por 10–14 dias' },
          { label: 'Glomerulonefrite', value: '1 mg/kg/dia pela manhã por 4–16 semanas. Máx: 120 mg/dia' },
          { label: 'Herpes-zoster', value: '60 mg/dia por 7 dias → 30 mg/dia por 7 dias → 15 mg/dia por 7 dias' },
          { label: 'Nefrite do lúpus', value: '0,5–1 mg/kg/dia por até 6 meses' },
          { label: 'Pneumonia pneumocística em imunodeprimidos', value: '40 mg 2×/dia → 40 mg/dia por 5 dias → 20 mg/dia dias 11–21. Iniciar até 72 h após diagnóstico.' },
          { label: 'Polimialgia reumática', value: '12,5–25 mg/dia; após controle: 10 mg/dia; reduzir 1 mg a cada 4 semanas' },
          { label: 'Púrpura trombocitopênica', value: '0,5–2 mg/kg/dia por 2–4 semanas' },
          { label: 'Profilaxia de alergia a contraste', value: '50 mg: 13h, 7h e 1h antes + difenidramina/prometazina 50 mg 1h antes' },
          { label: 'Gota aguda', value: '0,5–35 mg/kg/dia por 5–10 dias' },
          { label: 'Dermatopatias autoimunes', value: '1–1,5 mg/kg/dia; reduzir com melhora clínica' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Vertigem', 'Pseudotumor cerebral', 'Psicoses', 'Insônia', 'Depressão', 'Euforia', 'Convulsões',
      'Acne', 'Petéquias', 'Estrias', 'Inibição de cicatrização', 'Hirsutismo',
      'Vômitos', 'Náusea', 'Úlcera péptica', 'Gastrite', 'Irregularidade menstrual',
      'Edema', 'Hipertensão', 'Insuficiência cardíaca congestiva', 'Síncope', 'Edema pulmonar',
      'Hipopotassemia', 'Alcalose hipocalêmica', 'Hiperglicemia', 'Glicosúria',
      'Catarata', 'Glaucoma',
      'Uso prolongado: síndrome de Cushing, obesidade típica, fácies de lua cheia, estrias, acne, hirsutismo, retardo do crescimento, ganho de peso, imunossupressão, supressão do eixo hipófise-adrenal, osteoporose e fraturas',
      'Atrofia muscular', 'Fraqueza muscular', 'Hipertensão', 'Hiperlipidemia',
      'Trombose', 'Pancreatite aguda', 'Hipertensão intracraniana', 'Miocardiopatia', 'Amenorreia',
    ],
    contraindications: [
      'Infecções não controladas (herpes, varicela, tuberculose, fungos)',
      'Diabetes', 'Atrofia muscular', 'Osteoporose não controlada', 'Úlcera gástrica',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: 'Atenção à concentração da solução oral entre as marcas (5 ou 15 mg/5 mL). Tomar pela manhã com água e alimentos. Retirada abrupta após > 7 dias ou doses > 25 mg pode causar insuficiência adrenal secundária.' },
  },
  {
    id: 'prednisona',
    name: 'Prednisona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação intermediária (18–36 h). Precisa ser convertida no fígado para prednisolona — CONTRAINDICADA em disfunção hepática. Nestas situações, preferir prednisolona. Doses seguem os mesmos esquemas da prednisolona.',
    brands: ['Meticorten / Corticorten / CrisPred / Predcort / Prednisona genérica — comp. 5 e 20 mg'],
    presentations: [
      { label: 'Comprimido 5 mg' },
      { label: 'Comprimido 20 mg' },
    ],
    doses: [
      {
        group: 'Adultos e Crianças',
        items: [
          { label: 'Dose', value: 'Segue os mesmos esquemas da prednisolona. Em insuficiência hepática, substituir por prednisolona.' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Fadiga', 'Tontura', 'Insônia', 'Náusea', 'Diarreia',
      'Hipertensão', 'Hiperglicemia', 'Retenção hídrica', 'Supressão adrenal',
      'Osteoporose', 'Ganho de peso', 'Imunossupressão', 'Gastrite', 'Úlcera',
      'Catarata', 'Glaucoma', 'Alterações de humor', 'Miopatia', 'Pancreatite',
    ],
    contraindications: [
      'Disfunção hepática (usar prednisolona)',
      'Infecções não controladas (herpes, varicela, tuberculose, fungos)',
      'Diabetes', 'Atrofia muscular', 'Osteoporose não controlada', 'Úlcera gástrica',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'triancinolona',
    name: 'Triancinolona',
    category: 'corticosteroides',
    observations: 'Glicocorticoide de ação intermediária (18–36 h), com maior potência anti-inflamatória e menor retenção de sódio e água. 1 mg = 0,8 mg de prednisona. Uso principalmente intra-articular e intralesional.',
    brands: [
      'Triancil / Triancinolona — fr-amp. 20 mg/mL; fr-amp. 100 mg',
      'Triancinolona acetonida — fr-amp. 40 mg/mL',
    ],
    presentations: [
      { label: 'Frasco-ampola 20 mg/mL' },
      { label: 'Frasco-ampola acetonida 40 mg/mL' },
    ],
    doses: [
      {
        group: 'Adultos',
        items: [
          { label: 'Lesões dermatológicas (intra/sublesional)', value: 'Até 0,08 mg/cm² de área afetada. Variação: 2–48 mg/dia conforme tipo de lesão.' },
          { label: 'Intra-articular — pequenas articulações', value: '2–6 mg a cada 3–4 semanas' },
          { label: 'Intra-articular — grandes articulações', value: '10–20 mg a cada 3–4 semanas' },
          { label: 'Inflamações oculares — intravítrea', value: '4 mg em dose única' },
          { label: 'Inflamações oculares — subtenoniana', value: '40 mg em dose única' },
          { label: 'Orientação', value: 'Aspirar líquido sinovial antes da injeção intra-articular. Na aplicação intralesional, pode-se usar anestésico sem parabenos ou fenol.' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Aplicação local reduz efeitos sistêmicos, mas não os elimina',
      'Local: alergias, hipopigmentação, atrofia da pele, calcificações subcutâneas, lesões articulares, escaras, necrose óssea, ruptura de tendões, abscesso',
      'Oculares: glaucoma, catarata',
    ],
    contraindications: [
      'Infecções não controladas', 'Diabetes', 'Atrofia muscular',
      'Osteoporose não controlada', 'Úlcera gástrica', 'Tuberculose ativa',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
];