// ============================================================
// GUIA DE DOSES PEDIÁTRICO — Estrutura rica por medicamento
// ============================================================

export const GUIDE_CATEGORIES = [
  {
    id: 'cefalosporinas',
    label: 'Cefalosporinas',
    color: 'red-500',
    icon: '🦠',
    drugs: [
      {
        id: 'cefotaxima',
        name: 'Cefotaxima',
        suffix: 'AM',
        category: 'cefalosporinas',
        observations: 'Cefalosporina de terceira geração. Espectro semelhante à ceftriaxona, mas exige mais doses diárias e é menos eficaz que esta para gonococo e meningococo. Boa opção nas infecções ósseas, articulares e quadros de sepse.',
        brands: [
          'Cetazima (Novafarma) — Fr. Amp.: 500 e 1.000 mg',
          'Clafordil (Blau) — Fr. Amp.: 1.000 mg',
          'Kefozil (Biochimico)',
          '[G] Cefotaxima sódica — Fr. Amp.: 500 e 1.000 mg',
          'Descontinuados: Cefacolin, Ceforan, Claforan, Kefaxim, Loxporin',
        ],
        presentations: [
          { label: 'Fr. Amp. 500 mg', price: 'R$ 20' },
          { label: 'Fr. Amp. 1.000 mg', price: 'R$ 64' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'RN ≤ 7 dias (> 1 kg) a 14 dias', value: '50 mg/kg/dose × 2' },
              { label: 'RN 8 a 28 dias', value: '50 mg/kg/dose × 2 a 3' },
              { label: 'Lactentes e crianças (dose usual EV/IM)', value: '50 a 180 mg/kg/dia ÷ 3 a 4. Máx: 6 g/dia' },
              { label: 'Infecções graves', value: '200 a 225 mg/kg/dia ÷ 4 a 6. Máx: 12 g/dia' },
              { label: 'Endocardite', value: '200 mg/kg/dia ÷ 4, por 4 a 6 semanas' },
              { label: 'Pneumonia', value: '150 a 200 mg/kg/dia ÷ 3 a 4 (7–10 dias). Máx: 2 g/dose' },
              { label: 'Meningite', value: '50 mg/kg/dose × 4 (em < 1 mês: 75 mg/kg/dose × 4). Máx: 2 g/dose. No tratamento empírico, associar ampicilina ou aminoglicosídeo.' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Dose usual EV/IM', value: '1 g/dose × 3 a 4' },
              { label: 'Infecções graves', value: '1 a 2 g/dose × 3' },
              { label: 'Infecções complicadas', value: '2 g/dose × 4 a 6' },
              { label: 'Sepse', value: '2 g/dose × 3 a 4' },
              { label: 'Meningite / abscesso cerebral', value: '2 g/dose × 6 + metronidazol 30 mg/kg/dia ÷ 2 ou 4' },
              { label: 'Peritonite / infecções intra-abdominais', value: '2 g/dose × 3 (× 4 nos casos graves)' },
              { label: 'Pneumonia', value: '1 a 2 g/dose × 3' },
              { label: 'Infecção urinária comunitária', value: '1 g/dose × 2' },
              { label: 'Gonorreia (alternativa)', value: 'IM: 0,5 a 1 g/dose única' },
              { label: 'Profilaxia em cesariana', value: '1 g na clampagem do cordão + 6 h e 12 h depois' },
            ],
          },
        ],
        preparation: 'EV: diluir para 200 mg/mL com ABD, agitar até dissolver, depois rediluir para 40 mg/mL com SGI/SF/RL e infundir em 3–5 min. IM: diluir em ABD para 230–330 mg/mL; máximo de 2 g por sítio.',
        renalAdjustment: [
          { label: 'ClCr 10–50 mL/min', value: 'Mesma dose a cada 12 horas' },
          { label: 'ClCr < 10 mL/min', value: 'Mesma dose a cada 24 h ou 50% da dose' },
          { label: 'Hemodiálise', value: 'Mesma dose a cada 12–24 h' },
          { label: 'CPAD', value: '0,5 a 1 g/dose a cada 12–24 h' },
        ],
        sensitivity: {
          susceptible: [
            'Gram+: Streptococcus A,B,C,G, Pneumococo, S. viridans, Estafilococo sensível à oxacilina/meticilina',
            'Gram−: H. influenzae, N. meningitidis, M. catarrhalis, E. coli, Proteus mirabilis, Klebsiella',
            '20–30% das cepas hospitalares de: Pseudomonas, Enterobacter, Salmonella, Shigella, Yersinia, Citrobacter, Providencia, Morganella, Serratia, Pasteurella, Eikenella, Aeromonas, Vibrio cholerae',
            'Anaeróbios: Clostridios não difficile, Actinomyces, Peptostreptococcus',
          ],
          resistant: [],
          warning: '',
        },
        sideEffects: [
          'Alergia, erupção cutânea, prurido',
          'Cefaleia, febre',
          'Colite pseudomembranosa',
          'Diarreia, náusea, vômitos',
          'Flebite, dor no local da injeção',
          'Coombs positivo',
          'Plaquetopenia, leucopenia, neutropenia, eosinofilia',
          'Aumento transitório de ureia, creatinina e transaminases',
          'Candidíase genital',
          'Cada grama contém 2,2 mEq de sódio',
          'Infiltração provoca necrose tecidual',
        ],
        contraindications: [],
      },

      {
        id: 'ceftriaxona',
        name: 'Ceftriaxona',
        suffix: 'AM',
        category: 'cefalosporinas',
        observations: 'Cefalosporina de terceira geração com mesmo espectro que a cefotaxima, mas pode ser usada em dose única diária. Boa opção em sepse, pneumonia e meningite (até a idade pré-escolar). Na meningite neonatal, associar ampicilina para cobrir Listeria e estreptococo do grupo B. Em pediatria, preferir à cefotaxima — exceto em RN < 15 dias, prematuros, ictéricos, colestase intensa e em casos de abscesso cerebral ou ventriculites.',
        brands: [
          'Rocefin (Roche) — Fr. Amp. IV: 500 e 1.000 mg; Fr. Amp. IM: 500 e 1.000 mg',
          'Triaxin (Momenta) — Fr. Amp. IM: 500 e 1.000 mg',
          'Triaxon (Teuto) — Fr. Amp. IV: 500 e 1.000 mg; Fr. Amp. IM: 500 e 1.000 mg',
          'Amplospec (Biochimico), Ceftriax (EMS), Keftron (ABL), Triaxton (Blau)',
          '[G] Ceftriaxona sódica — Fr. Amp. IM e IV: 500 e 1.000 mg',
          'Descontinuados: Bioteral, Celtricina, Celltriaxon, Glicocef, Neoceftriona, Prodoxin, Trioxina',
        ],
        presentations: [
          { label: 'Fr. Amp. IV 500 mg', price: 'R$ 54' },
          { label: 'Fr. Amp. IM 500 mg', price: 'R$ 103' },
          { label: 'Fr. Amp. 250 mg / 1.000 mg', price: '' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'Dose usual', value: '50 a 75 mg/kg/dia ÷ 1. Máx: 1 g/dia' },
              { label: 'Sepse / casos graves', value: '100 mg/kg/dia ÷ 1 a 2. Máx: 4 g/dia' },
              { label: 'Meningite não gonocócica', value: 'Ataque: 100 mg/kg; Manutenção: 80–100 mg/kg/dia ÷ 1 a 2. Associar ampicilina no RN para cobrir Listeria.' },
              { label: 'Profilaxia meningite meningocócica', value: '125 mg/dose única IM' },
              { label: 'Pneumonia / Epiglotite', value: '50–100 mg/kg/dia ÷ 1 a 2 por 7–14 dias' },
              { label: 'Otite média aguda', value: '50 mg/kg/dose única. Máx: 1 g/dia' },
              { label: 'Profilaxia contato meningococo / conjuntivite gonocócica neonatal', value: '25–50 mg/kg/dose única. Máx: 125 mg/dose' },
              { label: 'Infecção gonocócica disseminada (neonatos)', value: '25–50 mg/kg/dia ÷ 1 por 7 dias (10–14 dias se meningite)' },
              { label: 'Infecção gonocócica disseminada (lactentes/crianças)', value: '50 mg/kg/dia ÷ 1' },
              { label: 'Doença de Lyme', value: '50–75 mg/kg/dia ÷ 1 por 2–4 semanas' },
              { label: 'Endocardite', value: '100 mg/dia ÷ 2 ou 80 mg/kg/dia ÷ 1 por 4–6 semanas. Máx: 4 g/dia' },
              { label: 'Profilaxia de endocardite/peritonite', value: '50 mg/kg, 30–60 min antes. Máx: 1 g/dose' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Dose usual', value: '1 a 2 g/dose × 1 a 2' },
              { label: 'Pneumonia', value: '1 a 2 g/dia ÷ 1 a 2 (4 g/dia ÷ 2 para pneumococo resistente)' },
              { label: 'Sepse / meningite', value: '2 g/dose × 2 por 7–14 dias. Máx: 4 g/dia' },
              { label: 'Profilaxia meningite meningocócica', value: '250 mg/dose única' },
              { label: 'Cistite / pielonefrite', value: '1 a 2 g/dia ÷ 1' },
              { label: 'DST — Gonorreia não complicada, cancro mole, estupro', value: 'IM: 250–500 mg (dose única) + azitromicina + metronidazol' },
              { label: 'DST — Granuloma inguinal', value: '1 g/dia por 10–14 dias' },
              { label: 'Infecção gonocócica disseminada', value: '1–2 g/dose × 1 (× 3 nos casos graves), por 7 dias ou enquanto houver sintomas' },
              { label: 'Endocardite', value: '2 g/dia ÷ 1 por 4–6 semanas. Enterococo sensível: 4 g/dia ÷ 2 + ampicilina (2 g × 6) por 6 semanas' },
              { label: 'Profilaxia de endocardite', value: '1 g, 30–60 min antes' },
            ],
          },
        ],
        preparation: 'EV: diluir para 100 mg/mL com ABD ou SF, agitar até dissolver, depois rediluir para 40 mg/mL com SG/SF/RL; infundir em 5–30 min. NÃO infundir com soluções contendo cálcio. IM: diluir com lidocaína 1% sem vasoconstritor para 350 mg/mL. Infusão contínua pode ser mais eficaz que bolus.',
        renalAdjustment: [
          { label: 'Insuficiência renal ou hepática', value: 'Máximo 2 g/dia' },
        ],
        sensitivity: {
          susceptible: [],
          resistant: [
            'Gram+: Estafilococo MRSA, Pneumococo resistente à penicilina',
            'Gram−: Listeria, Pseudomonas aeruginosa, E. coli/Klebsiella ESBL+, KPC+, Acinetobacter, Stenotrophomonas maltophilia, Burkholderia cepacia (maioria), Enterobacter cloacae, Mycoplasma, Chlamydia, Legionella, Flavobacterium',
            'Anaeróbios: Bacteroides fragilis, Clostridium difficile, Prevotella melaninogenica',
          ],
          warning: 'Mesmo quando sensível in vitro, resistência comum durante o tratamento (associar aminoglicosídeo): Enterobacter, P. aeruginosa, Serratia, Citrobacter, Acinetobacter, Proteus.',
        },
        sideEffects: [
          'Erupção cutânea, prurido, alergia',
          'Diarreia, colite pseudomembranosa, náusea, vômitos, estomatite',
          'Formação de "lodo biliar" / colelitíase',
          'Distúrbios de coagulação',
          'Leucopenia, anemia, trombocitopenia/trombocitose, ↑ transaminases',
          'Eosinofilia, febre, calafrio, cefaleia, tontura',
          'Flebite e dor no local da injeção',
          'Risco de precipitados com cálcio (embolia pulmonar em neonatos)',
          'Cada 1g contém 83 mg (3,6 mEq) de sódio',
        ],
        contraindications: [
          'Neonato com icterícia grave — preferir cefotaxima',
        ],
      },
    ],
  },
  {
    id: 'analgesicos',
    label: 'Analgésicos e Anti-inflamatórios',
    color: 'orange-500',
    icon: '💊',
    drugs: [
      {
        id: 'aas',
        name: 'Ácido acetilsalicílico',
        suffix: 'AAS',
        category: 'analgesicos',
        observations: 'Analgésico, antitérmico, anti-inflamatório e antiagregante plaquetário. Reduz mortalidade em adultos com risco cardíaco elevado (Framingham > 6%). Risco de Síndrome de Reye em menores de 16 anos com gripe/influenza B ou varicela — evitar nesses casos.',
        brands: [
          'Aspirina: comprimido 500 mg',
          'Aspirina Microativa: comprimido liberação modificada 500 mg',
          'Aspirina Prevent: comprimido liberação entérica 100 e 300 mg',
          'Ecasil-81: comprimido revestido 81 mg',
          'AAS: comprimido 100 mg',
          'AAS Protect: comprimido revestido 100 mg',
          'Melhoral: comprimido 85 mg',
          'Aceticil / As-med / Acetildor / Dormec / Salicetil / Sedalive: comprimido 100 e 500 mg',
          'Somalgin Cardio (+ carbonato de magnésio + glicinato de alumínio): comprimido revestido 81, 100, 200 e 325 mg',
          'Aspirina C / Melhoral C: comprimido efervescente 400 mg + vitamina C 240 mg',
          'Descontinuadas: Acstin, Analgesin, Antifebrin, Asetisin, Assedatil, Butlerin Cardio, CAAS, Cardio AAS, entre outras',
        ],
        presentations: [
          { label: 'Comprimido 100 mg', price: '' },
          { label: 'Comprimido 300 mg', price: '' },
          { label: 'Comprimido 500 mg', price: '' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'Febre e dor (mg/kg)', value: '10–15 mg/kg/dose, 4 a 6 vezes ao dia (máx: 120 mg/kg/dia ou 4 g/dia)' },
              { label: 'Febre e dor — até 1 ano (comprimido 100 mg)', value: '1/4 a 1/2 comprimido/dose' },
              { label: 'Febre e dor — 1 a 2 anos', value: '1/2 a 1 comprimido/dose' },
              { label: 'Febre e dor — 3 a 5 anos', value: '1 a 2 comprimidos/dose' },
              { label: 'Febre e dor — 6 a 9 anos', value: '2 a 3 comprimidos/dose' },
              { label: 'Febre e dor — 10 a 12 anos', value: '4 a 5 comprimidos/dose' },
              { label: 'Anti-inflamatório', value: '60–90 mg/kg/dia ÷ 3 a 4 doses' },
              { label: 'Febre reumática', value: '80–100 mg/kg/dia ÷ 4 doses por até 15 dias. Máx: 6 g/dia' },
              { label: 'Artrite reumatoide', value: '90–130 mg/kg/dia ÷ 4 a 6 doses' },
              { label: 'Doença de Kawasaki (fase febril)', value: '80–100 mg/kg/dia ÷ 4 doses por até 14 dias; depois 1–5 mg/kg/dia por 6–8 semanas' },
              { label: 'Antiagregante plaquetário', value: '1–5 mg/kg/dia, 1 vez ao dia' },
              { label: 'Prótese valvar', value: '6–20 mg/kg/dia, 1 vez ao dia' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Febre ou dor leve a moderada', value: '500 mg/dose, 4 vezes ao dia. Máx: 3 g/dia' },
              { label: 'Anti-inflamatório', value: '2,5–4,0 g/dia ÷ 4 a 6 doses' },
              { label: 'Artrite reumatoide / osteoartrites', value: 'Iniciar 3 g/dia ÷ 4–6 doses; máx: 8 g/dia' },
              { label: 'Antiagregante plaquetário', value: '100–300 mg/dia' },
              { label: 'Profilaxia cardiovascular (Framingham > 6%)', value: '80–325 mg/dia, 1 vez ao dia' },
              { label: 'Profilaxia do AVC isquêmico', value: '100–325 mg/dia' },
              { label: 'IAM — primeiro sinal', value: 'Mastigar 2–3 comprimidos de 100 mg; manutenção: 80–165 mg/dia' },
              { label: 'Angina instável', value: '80–325 mg/dia' },
              { label: 'Pós-prótese arterial / bypass', value: '160–325 mg/dia, iniciar 6 h depois' },
              { label: 'Implantação de stent', value: '160–325 mg/dia, iniciar 2 h antes' },
              { label: 'Pericardite pós-infarto (Dressler)', value: '500 mg/dose, 4 vezes ao dia' },
              { label: 'Profilaxia da pré-eclâmpsia', value: '80–165 mg/dia entre o 4º e 6º mês de gestação' },
              { label: 'Dor do herpes-zoster (uso tópico)', value: 'Triturar 500 mg em 10 mL de vaselina; aplicar até 3 vezes ao dia no local' },
            ],
          },
        ],
        renalAdjustment: [
          { label: 'ClCr < 10 mL/min', value: 'Evitar' },
          { label: 'Insuficiência hepática', value: 'Melhor evitar' },
          { label: 'Idosos > 80 anos', value: 'Evitar uso crônico' },
        ],
        sideEffects: [
          'Hemorragias, inclusive aguda grave; duplica o risco de sangramento gástrico',
          'Gastrite e ulcerações gástricas (até 30%)',
          'Náusea, diarreia, vômitos, cefaleia, dor gástrica, azia e pirose',
          'Alergia, broncoespasmo, angioedema e anafilaxia',
          'Disfunção plaquetária',
          'Agravamento de insuficiência renal; nefrite intersticial; necrose papilar renal',
          'Aumento de enzimas hepáticas e hepatite',
          'Hipertensão, taquicardia e arritmia',
          'Confusão mental, tontura e zumbido',
          'Rabdomiólise',
          'Síndrome de Reye (risco em < 16 anos com gripe ou varicela)',
          'Risco para o feto no primeiro trimestre; retarda trabalho de parto',
        ],
        contraindications: [
          'Suspeita de dengue',
          'Antecedente de anafilaxia ou crise de asma com salicilatos',
          'Último trimestre da gravidez (exceto tratamento de pré-eclâmpsia)',
          'Pré-operatório',
          'Gastrite ou úlcera péptica ativa',
          'Lesão hepática grave; hemofilia ou coagulopatias; trombocitopenia',
          'Uso de anticoagulantes (exceto protocolos específicos)',
          'Crianças com influenza ou varicela',
          'Síndrome de asma + pólipo nasal',
        ],
      },

      {
        id: 'clonixinato',
        name: 'Clonixinato de lisina',
        category: 'analgesicos',
        observations: 'Anti-inflamatório não esteroide com ação predominantemente analgésica. Útil nas cólicas renais, dores neurogênicas ou musculares, dor de dente e cefaleia. Uso não recomendado em crianças.',
        brands: [
          'Dolamin: comprimido revestido 125 mg',
          'Dolamin Flex / Benziflex Lis: comprimido revestido 125 mg + ciclobenzaprina 5 mg',
        ],
        presentations: [
          { label: 'Comprimido revestido 125 mg', price: '' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'Uso em crianças', value: 'Não recomendado' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Dismenorreia', value: '125 mg/dose, 4 vezes ao dia' },
              { label: 'Artrose de joelho', value: '125 mg/dose, 3 vezes ao dia' },
              { label: 'Dor leve a moderada / pós-operatório', value: '125–250 mg/dose, 3 vezes ao dia. Máx: 750 mg/dia' },
            ],
          },
        ],
        renalAdjustment: [
          { label: 'Insuficiência renal', value: 'Não exige ajuste' },
          { label: 'Insuficiência hepática', value: 'Melhor evitar' },
        ],
        sideEffects: [
          'Diarreia, náusea, vômitos, boca seca, dor epigástrica, pirose, azia',
          'Hemorragia digestiva, flatulência',
          'Risco de sangramento',
          'Cefaleia, tontura, sonolência',
          'Edema, hipotensão, proteinúria',
          'Prurido, urticária, irritação da pele',
        ],
        contraindications: [
          'Asma',
          'Úlcera péptica',
          'Lactentes',
        ],
      },

      {
        id: 'dipirona',
        name: 'Dipirona',
        suffix: 'Metamizol',
        category: 'analgesicos',
        observations: 'Analgésico e antitérmico pirazolônico. Único antitérmico de uso parenteral amplamente disponível no Brasil. Apesar de proibida em vários países, tem se mostrado segura em doses habituais, sobretudo em crianças maiores. Não usar em crianças abaixo de 3 meses ou de 5 kg pelo risco de disfunção renal.',
        brands: [
          'Novalgina: ampola 2 mL 500 mg/mL; comprimido 500 e 1000 mg; gotas 500 mg/mL; solução oral 50 mg/mL; supositório 300 mg',
          'Anador: comprimido 500 mg; gotas 500 mg/mL',
          'Alivdip / Diprin / Magnopyrol / Maxalgina: gotas 500 mg/mL; solução oral 50 mg/mL',
          'Hynalgin / Santidor / Dipifarma: ampola 500 mg/mL',
          'Lisador Dip / Termopirona: comprimido 1000 mg',
          'Outras: Algona, Anagos, Doralgina, Dorona, Doron, Febrilon, Prodopirona, Zitalgin, entre outras',
        ],
        presentations: [
          { label: 'Comprimido 500 mg', price: '' },
          { label: 'Gotas 10 mL — 500 mg/mL (25 mg/gota)', price: '' },
          { label: 'Solução oral 100 mL — 50 mg/mL', price: '' },
          { label: 'Ampola 2 mL — 500 mg/mL', price: '' },
          { label: 'Supositório 300 mg', price: '' },
        ],
        doses: [
          {
            group: 'Crianças — Via oral',
            items: [
              { label: 'Dose por peso', value: '10–15 mg/kg/dose, 4 vezes ao dia. Máx: 25 mg/kg/dose' },
              { label: 'Gotas (500 mg/mL)', value: '0,4–0,6 gotas/kg/dose, 4 vezes ao dia' },
              { label: 'Solução oral (50 mg/mL)', value: '0,2–0,3 mL/kg/dose, 4 vezes ao dia' },
              { label: '3–11 meses (5–8 kg)', value: '2–5 gotas ou 1,25–2,5 mL da solução' },
              { label: '1–3 anos (9–15 kg)', value: '3–9 gotas ou 2,5–5,0 mL da solução' },
              { label: '4–6 anos (16–23 kg)', value: '6–14 gotas ou 3,75–7,5 mL da solução' },
              { label: '7–9 anos (24–30 kg)', value: '9–18 gotas ou 5,0–10 mL da solução' },
              { label: '10–12 anos (31–45 kg)', value: '12–27 gotas ou 7,5–15 mL da solução' },
              { label: 'Via retal (> 4 anos)', value: 'Supositório 300 mg, até 4 vezes ao dia' },
            ],
          },
          {
            group: 'Crianças — Via EV ou IM (ampola 500 mg/mL)',
            items: [
              { label: 'Dose por peso', value: '15 mg/kg/dose = 0,03 mL/kg/dose' },
              { label: '5–8 kg', value: 'EV: evitar; IM: 0,1–0,2 mL' },
              { label: '9–15 kg', value: 'EV: 0,2–0,5 mL; IM: 0,2–0,5 mL' },
              { label: '16–23 kg', value: 'EV: 0,3–0,8 mL; IM: 0,3–0,8 mL' },
              { label: '24–30 kg', value: 'EV: 0,4–1,0 mL; IM: 0,4–1,0 mL' },
              { label: '31–45 kg', value: 'EV: 0,5–1,5 mL; IM: 0,5–1,5 mL' },
              { label: '46–53 kg', value: 'EV: 0,8–1,8 mL; IM: 0,8–1,8 mL' },
              { label: '> 53 kg', value: 'EV: 1,0–2,0 mL; IM: 1,0–2,0 mL' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Febre e dor — via oral', value: '500–1000 mg/dose (20–40 gotas), 3–4 vezes ao dia. Máx: 3000 mg/dia' },
              { label: 'EV ou IM', value: '500–2500 mg/dose. Máx: 5000 mg/dia' },
              { label: 'Administração EV', value: 'Diluir em 20 mL de SF ou ABD; infundir lentamente (máx 1 mL/min)' },
              { label: 'Dor oncológica', value: '2000–4000 mg/dia ÷ 3–4 doses; ou 500 mg × 4/dia + morfina 10 mg × 6/dia' },
              { label: 'Idosos', value: 'Usar a dose mais baixa' },
            ],
          },
        ],
        renalAdjustment: [
          { label: 'Insuficiência renal', value: 'Melhor evitar' },
          { label: 'Insuficiência hepática', value: 'Melhor evitar' },
        ],
        sideEffects: [
          'Náusea, vômitos, dor abdominal, diarreia, desconforto gástrico, erupção cutânea, sonolência',
          'Hipotermia',
          'Anafilaxia, broncoespasmo, edema angioneurótico, hipotensão, crise de asma',
          'RAROS E GRAVES: depressão medular, neutropenia, agranulocitose (pode ser fatal em até 10%), anemia, plaquetopenia',
          'Choque anafilático; Síndrome de Stevens-Johnson',
          'Distúrbios renais transitórios: anúria, proteinúria, nefrite intersticial',
          'Hemorragia gastrointestinal',
          'Pode corar a urina de vermelho (sem importância clínica)',
        ],
        contraindications: [
          'Crianças abaixo de 3 meses ou de 5 kg',
          'Nefrites crônicas',
          'Discrasias sanguíneas; supressão da medula óssea',
          'Alergia a AAS ou anti-inflamatórios não hormonais',
          'Deficiência de G6PD',
        ],
      },

      {
        id: 'ibuprofeno',
        name: 'Ibuprofeno',
        category: 'analgesicos',
        observations: 'Anti-inflamatório derivado do ácido propiônico. Considerado primeira escolha para substituir analgésicos não opioides no controle da dor. Efeito inicia em 1–2 horas e dura 6–8 horas. Ibuprofeno arginina tem início em 15–30 min. Atenção: existem apresentações em gotas com 50 mg/mL e 100 mg/mL — não calcular dose como gotas/kg sem saber a concentração.',
        brands: [
          'Advil / Buscofem: cápsula 400 mg',
          'Alivium: comprimido 400 e 600 mg; cápsula 400 e 600 mg; suspensão 150 mg/5 mL',
          'Dalsy: gotas 50 mg/mL e 100 mg/mL; comprimido 200, 400 e 600 mg; suspensão 100 mg/5 mL',
          'Motrin: comprimido 600 mg',
          'Ibufran / Ibupril / Ibuliv / Ibuvix / Buprovil: comprimido 300–600 mg; gotas 50 mg/mL',
          'Spidufen (+ arginina): granulado sachê 400 mg e 600 mg',
          'Outras: Algy-Flanderil, Doraliv, Febsen, Ibuprotrat, Novalfem, Parartrin, Vantil, Nurofen, entre outras',
        ],
        presentations: [
          { label: 'Comprimido 200, 300, 400 e 600 mg', price: '' },
          { label: 'Gotas 30 mL — 50 mg/mL', price: '' },
          { label: 'Gotas 20 mL — 100 mg/mL', price: '' },
          { label: 'Suspensão 100 mL — 100 mg/5 mL', price: '' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'Febre baixa', value: '5 mg/kg/dose, 1–4 vezes ao dia (= 1 gota/kg se 50 mg/mL)' },
              { label: 'Febre alta', value: '10 mg/kg/dose, 1–3 vezes ao dia. Máx: 40 mg/kg/dia' },
              { label: 'Dor leve a moderada', value: '5–10 mg/kg/dose, 3–4 vezes ao dia. Máx: 50 mg/kg/dia' },
              { label: 'Anti-inflamatório', value: '30–40 mg/kg/dia ÷ 3–4 doses' },
              { label: 'Artrite reumatoide juvenil', value: '30–50 mg/kg/dia ÷ 4 doses. Máx: 2400 mg/dia' },
              { label: 'Fibrose cística', value: '20–30 mg/kg/dose, 2 vezes ao dia (por mais de 4 anos)' },
              { label: 'Canal arterial no prematuro (500–1500 g)', value: '10 mg/kg; depois 5 mg/kg em 24 h e 48 h' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Febre', value: '200–400 mg/dose, 4–6 vezes ao dia. Máx: 1200 mg/dia' },
              { label: 'Dor leve ou moderada', value: '200–400 mg/dose, 4–6 vezes ao dia' },
              { label: 'Dor intensa', value: '400–800 mg/dose, 4 vezes ao dia. Máx: 3200 mg/dia' },
              { label: 'Cefaleia leve/moderada', value: '400–800 mg/dose' },
              { label: 'Cefaleia intensa', value: '800–1200 mg/dose' },
              { label: 'Anti-inflamatório', value: '400–800 mg/dose, 3–4 vezes ao dia. Máx: 3200 mg/dia' },
              { label: 'Dismenorreia', value: '400 mg/dose, até 4 vezes ao dia' },
              { label: 'Dor de drepanocitose', value: '600 mg/dose, 4 vezes ao dia' },
              { label: 'Osteoartrite / artrite reumatoide', value: '1200–3200 mg/dia ÷ 3–4 doses' },
            ],
          },
        ],
        renalAdjustment: [
          { label: 'Insuficiência renal', value: 'Usar a menor dose possível' },
          { label: 'Insuficiência hepática', value: 'Evitar' },
        ],
        sideEffects: [
          'Náusea, vômitos, dispepsia, azia, dor abdominal, erupção cutânea, tontura (3–9%)',
          'Cefaleia, edema, prurido, úlcera gástrica, gastrite, zumbido, constipação (1–3%)',
          'Hemorragia digestiva, trombocitopenia, icterícia, ↑ transaminases (< 1%)',
          'RAROS: insuficiência cardíaca, hipertensão, síndrome de Stevens-Johnson, perfuração GI, pancreatite',
          'RAROS: agranulocitose, hepatite fulminante, nefrite intersticial, insuficiência renal aguda',
          'Broncoespasmo e anafilaxia; síndrome de ativação de macrófago (CIVD)',
          'Uso crônico: disfunção renal em 1–5%; hipertensão reversível com suspensão',
        ],
        contraindications: [
          'Suspeita de dengue',
          'Alergia ou broncoespasmo por AAS ou anti-inflamatórios',
          'Úlcera péptica ativa',
          'Hipertensão grave; edema; insuficiência cardíaca',
          'Cardiopatias congênitas canal dependente',
          'Prematuros com sepse ou enterocolite necrosante suspeita/confirmada',
          'Hemorragia ativa',
        ],
      },

      {
        id: 'paracetamol',
        name: 'Paracetamol',
        suffix: 'Acetaminofeno',
        category: 'analgesicos',
        observations: 'Analgésico e antitérmico. Principal alternativa segura em idosos e pacientes com contraindicação a AINEs. Hepatotoxicidade sobretudo com doses altas; risco aumenta com jejum e ingestão de álcool. Antídoto: acetilcisteína.',
        brands: [
          'Tylenol: comprimido 500 e 750 mg; mastigável 160 mg; gotas 200 mg/mL',
          'Tylenol Bebê: suspensão 100 mg/mL',
          'Tylenol Criança: suspensão 160 mg/5 mL',
          'Alivian / Cyfenol / Dorsanol / Multigripe / Paralgen / Termol / Tyflen / Tylaflex / Tylidol: comprimido 500 e 750 mg; gotas 200 mg/mL',
          'Tyflen Bebê / Tylemax Baby: suspensão 100 mg/mL',
          'Tyflen Criança / Tylemax Criança: suspensão 160 mg/5 mL',
          'Vick Pyrena / Cimegripe / Emsgripe / Fervex / Resfenol Thermos: pó sachê 100 mg/g',
          'Pratium: gotas 140 mg/mL',
          'Ofirmev (EV): frasco-ampola 1000 mg/100 mL',
          'Outras: Analgisen, Codyflex, Dorfenol, Dorfen, Paramol, Sonridor efervescente, entre outras',
        ],
        presentations: [
          { label: 'Comprimido 500 mg', price: '' },
          { label: 'Comprimido 750 mg', price: '' },
          { label: 'Gotas 15 mL — 200 mg/mL (10 mg/gota)', price: '' },
          { label: 'Gotas 15 mL — 100 mg/mL (5 mg/gota)', price: '' },
          { label: 'Bebê: suspensão 15 mL — 100 mg/mL', price: '' },
          { label: 'Criança: suspensão 60 mL — 160 mg/5 mL', price: '' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'Prematuros 28–32 sem', value: '10–12 mg/kg/dose, 4 vezes ao dia (mínimo 6 h entre doses)' },
              { label: 'Prematuros 32–36 sem', value: '10–15 mg/kg/dose, 4 vezes ao dia' },
              { label: 'Lactentes e crianças', value: '10–15 mg/kg/dose, 4 vezes ao dia' },
              { label: 'Gotas 200 mg/mL (10 mg/gota)', value: '1 gota/kg/dose' },
              { label: 'Gotas 100 mg/mL (5 mg/gota)', value: '2 gotas/kg/dose' },
              { label: '0–3 meses: 40 mg', value: '4 gotas (200 mg/mL) ou 8 gotas (100 mg/mL)' },
              { label: '4–11 meses: 80 mg', value: '8 gotas (200 mg/mL) ou 16 gotas (100 mg/mL)' },
              { label: '1–2 anos: 120 mg', value: '12 gotas (200 mg/mL) ou 24 gotas (100 mg/mL)' },
              { label: '2–3 anos: 160 mg', value: '16 gotas (200 mg/mL) ou 32 gotas (100 mg/mL)' },
              { label: '4–5 anos: 240 mg', value: '24 gotas (200 mg/mL) ou 48 gotas (100 mg/mL)' },
              { label: '6–8 anos: 320 mg', value: '32 gotas (200 mg/mL) ou 64 gotas (100 mg/mL)' },
              { label: '9–10 anos: 400 mg', value: '40 gotas (200 mg/mL) ou 80 gotas (100 mg/mL)' },
              { label: '11–12 anos: 480 mg', value: '48 gotas (200 mg/mL) ou 96 gotas (100 mg/mL)' },
              { label: '> 12 anos: 500 mg', value: '50 gotas (200 mg/mL) ou 100 gotas (100 mg/mL)' },
              { label: 'Suspensão 160 mg/5 mL — 12–15 kg', value: '5,0 mL/dose' },
              { label: 'Suspensão 160 mg/5 mL — 16–21 kg', value: '7,5 mL/dose' },
              { label: 'Suspensão 160 mg/5 mL — 22–26 kg', value: '10,0 mL/dose' },
              { label: 'Suspensão 160 mg/5 mL — 27–32 kg', value: '12,5 mL/dose' },
              { label: 'Suspensão 160 mg/5 mL — 33–43 kg', value: '15,0 mL/dose' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Analgésico e antitérmico', value: '500 mg de 4/4 h; ou 750–1000 mg de 6/6 h. Máx: 4 g/dia' },
              { label: 'Apresentação AP', value: '650–1300 mg de 8/8 h' },
              { label: 'Via EV (não disponível no Brasil)', value: '1000 mg em 15 min, de 6/6 h. Máx: 4 g/dia (> 50 kg)' },
              { label: 'Dor crônica em idosos', value: '500 mg/dose, 3–4 vezes ao dia. Máx: 4 g/dia' },
              { label: 'Cefaleia', value: '500–1000 mg/dose' },
            ],
          },
        ],
        renalAdjustment: [
          { label: 'ClCr 10–50 mL/min', value: 'Máx 4 doses/dia, a cada 6 horas' },
          { label: 'ClCr < 10 mL/min', value: 'Máx 3 doses/dia, a cada 8 horas' },
          { label: 'Insuficiência hepática', value: 'Melhor evitar' },
        ],
        sideEffects: [
          'Erupção cutânea, náusea, vômitos, dor de garganta, febre',
          'Urticária, angioedema e anafilaxia',
          'Anemia, leucopenia, neutropenia, pancitopenia',
          'Nefrotoxicidade; lesão renal com uso crônico',
          'Hepatotoxicidade (sobretudo com doses altas, jejum ou álcool); disfunção hepática tardia',
          'Nível tóxico: 200 mcg/mL 4 h após ingestão, ou 50 mcg/mL 12 h após ingestão',
        ],
        contraindications: [
          'Deficiência de G6PD (risco de hemólise em doses altas)',
          'Hepatopatias graves',
        ],
      },
    ],
  },
  {
    id: 'anfenicois-tetraciclinas',
    label: 'Anfenicóis e Tetraciclinas',
    color: 'green-500',
    icon: '🧫',
    drugs: [
      {
        id: 'cloranfenicol',
        name: 'Cloranfenicol',
        category: 'anfenicois-tetraciclinas',
        observations: 'Anfenicol, inibidor de síntese de proteínas de amplo espectro. Bacteriostático para a maioria das bactérias sensíveis e bactericida contra H. influenzae, Neisseria meningitidis e S. pneumoniae. Pelo grande risco de toxicidade, o uso deve ser limitado a infecções para as quais os benefícios superem os riscos.',
        brands: [
          'Arifenicol — Fr. amp. 1.000 mg',
          'Comprimidos/cápsulas 250 mg',
          'Suspensão oral 25 mg/mL',
          'Succinato sódico de cloranfenicol — Fr. amp. 1.000 mg',
        ],
        presentations: [
          { label: 'Fr. amp. 1.000 mg' },
          { label: 'Comprimido/cápsula 250 mg' },
          { label: 'Suspensão oral 25 mg/mL' },
        ],
        doses: [
          {
            group: 'Crianças',
            items: [
              { label: 'EV / oral (dose usual)', value: '50–75 mg/kg/dia ÷ 3–4 doses' },
              { label: 'RN < 7 dias ou ≤ 2 kg ou metabolismo imaturo', value: '25 mg/kg/dia ÷ 1–4 doses' },
              { label: 'RN > 7 dias e > 2 kg', value: '50 mg/kg/dia ÷ 1–2 doses' },
              { label: 'Meningite', value: '75–100 mg/kg/dia ÷ 4 doses. Associar ampicilina.' },
              { label: 'Tempo de tratamento usual', value: '10–14 dias' },
            ],
          },
          {
            group: 'Adultos — infecções graves',
            items: [
              { label: 'EV / oral', value: '50 mg/kg/dia ÷ 4 doses. Se necessário, iniciar com 75–100 mg/kg/dia e reduzir. Máx: 4 g/dia' },
            ],
          },
        ],
        preparation: 'EV: diluir 100 mg/mL ou mais e infundir em 5 minutos. NÃO usar por via intramuscular. Monitorar hemograma cerca de 2 × por semana. Nível sérico de pico (30 min após dose): neonatos 15–25 µg/mL; crianças/adolescentes 15–30 µg/mL; adultos 10–20 µg/mL. Basal (antes da próxima dose): 5–15 µg/mL.',
        sensitivity: {
          susceptible: [
            'Anaeróbios, B. anthracis, Bacteroides, Bordetella pertussis, Burkholderia cepacia',
            'Enterococcus resistentes à vancomicina, E. coli, Espiroqueta',
            'Haemophilus influenzae, Klebsiella, Mycoplasma, Neisseria gonorrhoeae, Neisseria meningitidis',
            'P. pseudomallei, Rickettsia, Salmonella typhi, Serratia',
            'Staphylococcus aureus, S. epidermidis, Streptococcus A, B, C e G, Streptococcus pneumoniae',
            'Vibrio cholerae, Yersinia pestis',
          ],
          resistant: [
            'Cepas de Pseudomonas, Shigella, Salmonella',
            'Streptococcus pneumoniae resistentes à penicilina',
          ],
          warning: '',
        },
        sideEffects: [
          'Náusea, vômito, diarreia, estomatite, alergia, erupção cutânea, enterocolite, febre',
          'Confusão, cefaleia, pesadelo, neurite óptica, cardiotoxicidade, depressão ventricular aguda',
          'Depressão medular reversível dose-dependente, pior com nível sérico > 25 µg/mL',
          'Aplasia fatal independente da dose — pode ocorrer 1 a 12 meses depois',
          'Síndrome cinzenta em neonatos: colapso circulatório, cianose, hipotermia, acidose, coma e morte',
          'Hepatite medicamentosa com pancitopenia, anafilaxia',
        ],
        contraindications: [],
      },

      {
        id: 'doxiciclina',
        name: 'Doxiciclina',
        category: 'anfenicois-tetraciclinas',
        observations: 'Tetraciclina bacteriostática de amplo espectro e ação longa. Menor toxicidade gastrointestinal que outras tetraciclinas. Útil para infecções do trato respiratório e tecidos moles. Primeira escolha para infecções por Chlamydia trachomatis.',
        brands: [
          'Vibramicina — comprimido solúvel 100 mg; comprimido revestido 100 mg',
          'Clordox, Doxiclin — comprimido revestido 100 mg',
          'Neo doxicillin, Protectina',
          'Genérico (cloridrato de doxiciclina) — comprimido 100 mg; injetável 100 mg; comprimido revestido 100 mg',
        ],
        presentations: [
          { label: 'Comprimido 100 mg' },
          { label: 'Injetável 100 mg' },
        ],
        doses: [
          {
            group: 'Crianças ≥ 8 anos',
            items: [
              { label: 'Dose usual', value: '5 mg/kg/dia no 1º dia, seguido de 2–5 mg/kg/dia ÷ 1–2 doses. Máx: 100 mg/dose' },
              { label: 'Malária', value: '2,2 mg/kg/dose a cada 12 h por 7 dias' },
              { label: 'Profilaxia malária', value: '2,2 mg/kg/dia, de 2 dias antes até 1 mês após o retorno' },
              { label: 'Brucelose', value: '1–2 mg/kg/dia por 6 semanas. Associar rifampicina ou aminoglicosídeo' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Dose usual', value: '100–200 mg/dia ÷ 1–2 doses' },
              { label: 'Acne grau III', value: '100 mg/dia ÷ 1–2 doses por 3–4 meses' },
              { label: 'Rosácea', value: '50–100 mg/dose 2×/dia por 1–3 meses' },
              { label: 'Pneumonia comunitária / exacerbação DPOC', value: '100 mg/dose 2×/dia' },
              { label: 'Diarreia', value: '100 mg 2×/dia por 5–7 dias' },
              { label: 'Cólera grave', value: '300 mg em dose única (adjunto)' },
              { label: 'Doença de Lyme — tratamento', value: '100 mg/dose 2×/dia por 14–28 dias' },
              { label: 'Doença de Lyme — profilaxia', value: '200 mg em dose única' },
              { label: 'DST (Chlamydia, cancro mole, gonorreia não complicada)', value: '100 mg/dose 2×/dia por 10 dias. Associar ceftriaxona dose única' },
              { label: 'DST — granuloma inguinal', value: '100 mg/dose 2×/dia por 3–4 semanas' },
              { label: 'Sífilis / DIP', value: '100 mg/dose 2×/dia por 14 dias (28 dias na sífilis tardia)' },
              { label: 'Malária por P. falciparum + cloroquina', value: '100 mg/dose 2×/dia por 7 dias' },
              { label: 'Profilaxia malária', value: '100 mg/dia de 2 dias antes até 1 mês após a viagem' },
              { label: 'Rinossinusite aguda / alternativa', value: '100 mg/dose 2×/dia por 5–7 dias' },
              { label: 'Insuficiência renal', value: 'Não exige ajuste' },
            ],
          },
        ],
        sensitivity: {
          susceptible: [
            'Acinetobacter, Actinomyces, Bacteroides, Bartonella, Borrelia, Brucella, Calymmatobacterium',
            'Campylobacter fetus, Chlamydia, Clostridium, C. burnetii, D. fragilis, E. coli, F. tularensis',
            'Haemophilus ducreyi, Legionella, L. buccalis, Listeria monocytogenes, Mycoplasma pneumoniae',
            'Neisseria gonorrhoeae, Rickettsia, Staphylococcus resistente, Streptococcus pneumoniae',
            'Treponema pallidum, Ureaplasma urealyticum, V. cholerae, Y. pestis',
            'Malária por Plasmodium falciparum resistente',
          ],
          resistant: [
            'Enterococcus, Proteus, Salmonella, Serratia, Staphylococcus epidermidis',
            'Cepas de Bacillus anthracis, Enterobacter, H. influenzae, Klebsiella, Moraxella',
            'Pneumococcus, Shigella, Streptococcus pyogenes',
          ],
          warning: 'Aumenta níveis séricos de digoxina e varfarina. Não associar com isotretinoína ou penicilinas.',
        },
        sideEffects: [
          'Descoloração dos dentes e displasia do esmalte em < 8 anos',
          'Anorexia, náusea, vômitos, diarreia, secura na boca, glossite',
          'Fotossensibilização, erupção, urticária, Síndrome de Stevens-Johnson',
          'Anemia hemolítica, depressão medular, eosinofilia, pericardite',
          'Hipertensão intracraniana, hepatotoxicidade',
        ],
        contraindications: [
          'Menores de 8 anos',
        ],
      },

      {
        id: 'limeciclina',
        name: 'Limeciclina',
        category: 'anfenicois-tetraciclinas',
        observations: 'Tetraciclina bacteriostática de amplo espectro.',
        brands: [
          'Tetralysal',
          'Meciclin — cápsulas 150 e 300 mg',
        ],
        presentations: [
          { label: 'Cápsula 150 mg' },
          { label: 'Cápsula 300 mg' },
        ],
        doses: [
          {
            group: 'Adultos',
            items: [
              { label: 'Acne grau III, rosácea ou erupção acneiforme', value: '300 mg/dia ÷ 1–2 doses por 8–12 semanas' },
              { label: 'Outras infecções', value: '300 mg/dose, 1–2 vezes ao dia' },
            ],
          },
        ],
        sensitivity: {
          susceptible: [
            'Brucella, Chlamydia, Haemophilus, Leptospira, M. pneumoniae, N. gonorrhoeae',
            'Pasteurella, Propionibacterium acnes, Rickettsia, T. pallidum, U. urealyticum, V. cholerae',
          ],
          resistant: [],
          warning: 'Não usar antes dos 8 anos de idade — risco de mancha no esmalte dentário.',
        },
        sideEffects: [
          'Mancha no esmalte dentário (não usar < 8 anos), erupção cutânea, urticária, alergia',
          'Anemia hemolítica, plaquetopenia, eosinofilia, neutropenia, disfunção renal',
        ],
        contraindications: [],
      },

      {
        id: 'minociclina',
        name: 'Minociclina',
        category: 'anfenicois-tetraciclinas',
        observations: 'Tetraciclina sintética com meia-vida mais longa. Bacteriostático.',
        brands: [
          'Minociclina — comprimido revestido 100 mg',
          'Genérico — comprimido revestido 100 mg',
        ],
        presentations: [
          { label: 'Comprimido revestido 100 mg' },
        ],
        doses: [
          {
            group: 'Crianças ≥ 8 anos',
            items: [
              { label: 'Dose usual', value: '4 mg/kg/dia ÷ 2 doses. Primeira dose dobrada.' },
            ],
          },
          {
            group: 'Adultos',
            items: [
              { label: 'Dose inicial', value: '200 mg/dia em dose única' },
              { label: 'Manutenção', value: '100 mg/dose 2×/dia. Máx: 400 mg/dia' },
              { label: 'Acne', value: '50–100 mg/dose 2×/dia' },
              { label: 'Hanseníase — alternativa', value: '100 mg/dia + ofloxacino + rifampicina em dose diária' },
              { label: 'Insuficiência renal (ClCr < 80 mL/min)', value: 'Máx 200 mg/dia' },
              { label: 'Orientação', value: 'Não tomar com alimentos ou leite' },
            ],
          },
        ],
        sensitivity: {
          susceptible: [
            'Acinetobacter, Actinomyces, B. anthracis, Bartonella, B. recurrentis, Brucella, C. fetus',
            'Chlamydia, Clostridium, Cutibacterium, E. histolytica, E. aerogenes, E. coli, F. tularensis',
            'F. fusiforme, Klebsiella, L. monocytogenes, Microbacterium, Neisseria, Nocardia, Rickettsia',
            'Staphylococcus (incluindo SARM), S. pneumoniae, Shigella, Treponema, U. urealyticum',
            'V. cholerae, Y. pestis',
          ],
          resistant: [
            'Enterococcus, Proteus, Providencia, Pseudomonas, Serratia, S. agalactiae',
          ],
          warning: '',
        },
        sideEffects: [
          'Náusea, vômitos, diarreia, esofagite, vertigem, ataxia',
          'Alergia, erupção cutânea, fotossensibilização, anafilaxia',
          'Descoloração de dentes em < 8 anos, Síndrome de Stevens-Johnson',
          'Febre, insuficiência renal, disfunção hepática, eosinofilia, trombocitopenia',
          'Pneumonite por hipersensibilidade',
        ],
        contraindications: [],
      },
    ],
  },
];

export function getAllGuideDrugs() {
  return GUIDE_CATEGORIES.flatMap(cat => cat.drugs.map(d => ({ ...d, catLabel: cat.label, catColor: cat.color, catIcon: cat.icon })));
}