export const antimalaricos = [
  {
    id: 'artemeter-lumefantrina',
    name: 'Arteméter + Lumefantrina',
    category: 'antimalaricos',
    observations: 'Derivado de artemisinina associado a quinolinometanol, ambos esquizonticidas. Dar 8 horas de intervalo entre a 1ª e 2ª dose; doses restantes de manhã e à noite com 12 h de intervalo.',
    brands: ['Coartem — comprimido 20 + 120 mg'],
    presentations: [{ label: 'Comprimido 20 + 120 mg' }],
    doses: [
      {
        group: 'Adultos e crianças > 6 meses — Malária por P. falciparum não complicada',
        items: [
          { label: '5 a 14 kg', value: '20 + 120 mg (1 comprimido/dose), 2×/dia por 3 dias' },
          { label: '15 a 24 kg', value: '40 + 240 mg (2 comprimidos/dose), 2×/dia por 3 dias' },
          { label: '25 a 34 kg', value: '60 + 360 mg (3 comprimidos/dose), 2×/dia por 3 dias' },
          { label: '≥ 35 kg', value: '80 + 480 mg (4 comprimidos/dose), 2×/dia por 3 dias' },
          { label: 'Orientação', value: 'Para crianças, esmagar e misturar com água. Tomar durante ou após refeição.' },
        ],
      },
    ],
    sideEffects: [
      'Cefaleia', 'Insônia', 'Fadiga', 'Tontura', 'Astenia',
      'Náusea', 'Vômito', 'Diarreia', 'Perda de apetite', 'Dispepsia', 'Dor abdominal',
      'Artralgia', 'Mialgia', 'Erupção cutânea',
      'Palpitação', 'Prolongamento do intervalo QT',
      'Esplenomegalia', 'Hepatomegalia', 'Tosse', 'Febre',
    ],
    contraindications: ['Primeiro trimestre de gestação'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'artesunato',
    name: 'Artesunato',
    category: 'antimalaricos',
    observations: 'Esquizonticida e gametocitocida derivado de artemisinina, potente e com rápida ação nas formas assexuadas. Usar para malária grave por P. falciparum.',
    brands: ['Frasco-ampola 60 mg'],
    presentations: [{ label: 'Frasco-ampola 60 mg' }],
    doses: [
      {
        group: 'Adultos e crianças — Malária grave por P. falciparum',
        items: [
          { label: '< 20 kg', value: '3 mg/kg/dose' },
          { label: '≥ 20 kg', value: '2,4 mg/kg/dose' },
          { label: 'Esquema', value: '4 doses EV (ou IM): 1 dose de ataque + 2 doses com 12 h de intervalo + 4ª dose no 3º dia' },
          { label: 'Continuação', value: 'Se possível, passar para via oral ou manter 1 dose/dia por no máximo 7 dias' },
        ],
      },
    ],
    preparation: 'Reconstituir em 1 mL de bicarbonato 5% e diluir com 5 mL (EV) ou 2 mL (IM) de SGI 5% ou SF 0,9%. Usar imediatamente. EV: administrar em 3 a 4 mL/minuto.',
    sideEffects: [
      'Neurotoxicidade', 'Tontura', 'BAV', 'Taquicardia', 'Agranulocitose',
      'Náusea', 'Vômitos', 'Diarreia', 'Aumento de transaminases',
      'Redução transitória de reticulócitos',
    ],
    contraindications: [],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'artesunato-mefloquina',
    name: 'Artesunato + Mefloquina',
    category: 'antimalaricos',
    observations: 'Derivado de artemisinina associado a quinolinometanol, ambos esquizonticidas. Para crianças, esmagar e misturar com água.',
    brands: [
      'Comprimido revestido adulto: 100 + 200 mg',
      'Comprimido revestido infantil: 25 + 50 mg',
    ],
    presentations: [
      { label: 'Comprimido revestido adulto 100 + 200 mg' },
      { label: 'Comprimido revestido infantil 25 + 50 mg' },
    ],
    doses: [
      {
        group: 'Adultos e crianças > 6 meses — Malária por P. falciparum não complicada',
        items: [
          { label: '5 a 8 kg', value: '25 + 55 mg — 1 comprimido infantil ao dia por 3 dias' },
          { label: '9 a 17 kg', value: '50 + 110 mg — 2 comprimidos infantis ao dia por 3 dias' },
          { label: '18 a 29 kg', value: '100 + 220 mg — 1 comprimido adulto ao dia por 3 dias' },
          { label: '≥ 30 kg', value: '200 + 440 mg — 2 comprimidos adultos ao dia por 3 dias' },
          { label: 'Orientação', value: 'Para crianças, esmagar e misturar com água. Tomar durante ou após refeição.' },
        ],
      },
    ],
    sideEffects: [
      'Cefaleia', 'Insônia', 'Fadiga', 'Tontura', 'Disforia', 'Pode aumentar risco de suicídio',
      'Palpitação', 'Náusea', 'Vômitos', 'Anorexia', 'Dispepsia', 'Dor abdominal', 'Erupção cutânea',
    ],
    contraindications: ['Primeiro trimestre de gestação'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'atovaquona-proguanil',
    name: 'Atovaquona + Proguanil',
    category: 'antimalaricos',
    observations: 'Antimalárico para profilaxia e tratamento, principalmente em áreas de P. falciparum resistente. Como profilático, iniciar 1 dia antes e manter até 7 dias após retorno.',
    brands: [
      'Malarone — comprimido 250 + 100 mg; comprimido pediátrico 62,5 + 25 mg',
    ],
    presentations: [
      { label: 'Comprimido 250 + 100 mg' },
      { label: 'Comprimido pediátrico 62,5 + 25 mg' },
    ],
    doses: [
      {
        group: 'Adultos e crianças — Malária por P. falciparum resistente',
        items: [
          { label: '5 a 8 kg — Profilaxia', value: '31,25 + 12,5 mg' },
          { label: '5 a 8 kg — Tratamento (3 dias)', value: '125 + 50 mg' },
          { label: '9 a 10 kg — Profilaxia', value: '46,8 + 18,75 mg' },
          { label: '9 a 10 kg — Tratamento (3 dias)', value: '187,5 + 75 mg' },
          { label: '11 a 20 kg — Profilaxia', value: '62,5 + 25 mg' },
          { label: '11 a 20 kg — Tratamento (3 dias)', value: '250 + 100 mg' },
          { label: '21 a 30 kg — Profilaxia', value: '125 + 50 mg' },
          { label: '21 a 30 kg — Tratamento (3 dias)', value: '500 + 200 mg' },
          { label: '31 a 40 kg — Profilaxia', value: '187,5 + 75 mg' },
          { label: '31 a 40 kg — Tratamento (3 dias)', value: '750 + 300 mg' },
          { label: '> 40 kg — Profilaxia', value: '250 + 100 mg' },
          { label: '> 40 kg — Tratamento (3 dias)', value: '1000 + 400 mg' },
        ],
      },
    ],
    sideEffects: [
      'Cefaleia', 'Distúrbios do sono', 'Fadiga', 'Febre', 'Tontura',
      'Diarreia', 'Dispepsia', 'Náusea', 'Vômitos', 'Dor abdominal', 'Anorexia',
      'Aumento de transaminases', 'Exantema', 'Prurido', 'Angioedema', 'Fotossensibilidade',
      'Neutropenia', 'Pancitopenia', 'Hepatite', 'Palpitações', 'Tosse',
    ],
    contraindications: ['Gestação', 'Insuficiência renal grave'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'cloroquina',
    name: 'Cloroquina',
    category: 'antimalaricos',
    observations: '4-aminoquinolina esquizonticida de ação rápida. Tratamento da malária não complicada por P. vivax e P. malariae. Para P. falciparum, só se a região for sensível. Uso também em artrite reumatoide, lúpus e osteoartrites.',
    brands: ['Cloroquina — comprimido 150 mg (250 mg de difosfato = 150 mg de base)'],
    presentations: [{ label: 'Comprimido 150 mg' }],
    doses: [
      {
        group: 'Adultos e crianças — Malária não complicada por P. vivax/P. ovale/P. malariae',
        items: [
          { label: 'Esquema 3 dias', value: '10 mg/kg/dia no 1º dia; 7,5 mg/kg/dia nos dias 2 e 3' },
          { label: 'Esquema alternativo', value: '10 mg/kg seguido de 5 mg/kg após 6 h para completar 25 mg/kg nos 3 dias' },
          { label: 'Profilaxia (P. vivax ou P. ovale)', value: '5 mg/kg/dose semanal. Iniciar 1–2 semanas antes e manter 4–8 semanas após retorno' },
          { label: 'Evitar recaída frequente', value: '5 mg/kg/dose mensal por 12 semanas' },
          { label: 'Amebíase extraintestinal', value: '600 mg/dia por 2 dias; depois 300 mg/dia por 2–3 semanas' },
          { label: 'Orientação', value: 'Tomar durante ou após refeição. Tomar separado da primaquina.' },
        ],
      },
    ],
    renalAdjustment: [
      { label: 'ClCr < 10 mL/min', value: '50% da dose' },
    ],
    sideEffects: [
      'Náusea', 'Vômitos', 'Diarreia', 'Irritação gástrica', 'Estomatite',
      'Fadiga', 'Lassidão', 'Cefaleia', 'Vertigem', 'Confusão', 'Psicose',
      'Visão turva', 'Diplopia', 'Neuromiopatia', 'Mialgia', 'Retinopatia',
      'Prurido intenso (sobretudo em palmas e plantas)', 'Exantema',
      'Coloração azulada reversível no palato e unhas', 'Exacerbação de psoríase', 'Porfiria',
      'Anemia aplásica', 'Depressão medular (muito raro)',
      'EV: risco de hipotensão e colapso vascular grave',
    ],
    contraindications: ['Retinopatia'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'halofantrina',
    name: 'Halofantrina',
    category: 'antimalaricos',
    observations: '4-aminoquinolina esquizonticida sanguíneo. Reservado para casos de resistência à cloroquina. No tratamento de P. vivax, associar primaquina.',
    brands: ['Halfan — comprimido revestido 250 mg'],
    presentations: [{ label: 'Comprimido revestido 250 mg' }],
    doses: [
      {
        group: 'Adultos e crianças > 10 anos — Malária resistente à cloroquina',
        items: [
          { label: 'Dose', value: '3 doses de 8 mg/kg/dose. Máx: 500 mg/dose. Intervalo de 6 h entre doses. Dose total: 24 mg/kg.' },
          { label: 'Repetição', value: 'Repetir as 3 doses 7 dias depois' },
          { label: 'Orientação', value: 'Usar apenas para cepas resistentes. Tomar em jejum (1 h antes ou 2 h após refeição).' },
        ],
      },
    ],
    sideEffects: [
      'Aumento do intervalo QTc', 'Arritmias ventriculares graves', 'Palpitações', 'Hipotensão postural',
      'Diarreia', 'Náusea', 'Vômito', 'Dor abdominal', 'Anorexia', 'Estomatite',
      'Tosse', 'Erupção cutânea', 'Prurido', 'Angioedema',
      'Cefaleia', 'Tontura', 'Convulsões', 'Febre', 'Fadiga', 'Astenia',
      'Elevação de transaminases',
    ],
    contraindications: [
      'Gestantes', 'Crianças < 10 anos', 'Cardiopatas', 'QT prolongado',
      'Uso com drogas que prolongam QT', 'Menores de 40 kg', 'Associação com mefloquina',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'mefloquina',
    name: 'Mefloquina',
    category: 'antimalaricos',
    observations: '4-aminoquinolina esquizonticida sanguíneo. Usada para todas as espécies resistentes de P. falciparum. No tratamento de P. vivax, associar primaquina para eliminar parasitas exoeritrocíticos.',
    brands: ['Mefoquin — comprimido 250 mg'],
    presentations: [{ label: 'Comprimido 250 mg' }],
    doses: [
      {
        group: 'Adultos e crianças — Malária falciparum resistente ou P. vivax resistente à cloroquina',
        items: [
          { label: 'Dose total', value: '1250 mg (se > 20 mg/kg). Dividir: 750 mg na 1ª dose (500 mg) e 2ª dose 6–12 h depois' },
          { label: 'Profilaxia', value: '250 mg ou 5 mg/kg/dose semanal. Iniciar 1 semana antes até 4 semanas após o retorno' },
          { label: 'Orientação', value: 'Tomar com alimentos' },
        ],
      },
    ],
    sideEffects: [
      'Convulsões', 'Psicose', 'Obnubilação', 'Confusão', 'Pesadelos', 'Mialgia', 'Cefaleia', 'Vertigem',
      'Náusea', 'Vômito', 'Anorexia', 'Dor abdominal', 'Exantema',
      'Leucopenia', 'Trombocitopenia', 'Aumento de TGO/TGP',
      'Arritmia', 'Cardiotoxicidade',
    ],
    contraindications: ['Neuropatia', 'Convulsão', 'Miocardiopatia', 'Arritmia', 'Primeiro trimestre de gestação'],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'primaquina',
    name: 'Primaquina',
    category: 'antimalaricos',
    observations: '8-aminoquinolina gametocitocida e hipnozoiticida. Bloqueia transmissão e esquizonticida da forma hepática. Útil para profilaxia radical de infecções recidivantes. Risco de hemólise grave na deficiência de G6PD.',
    brands: ['Primaquina — comprimido 5 e 15 mg (26,3 mg de fosfato = 15 mg de base)'],
    presentations: [
      { label: 'Comprimido 5 mg' },
      { label: 'Comprimido 15 mg' },
    ],
    doses: [
      {
        group: 'Crianças',
        items: [
          { label: 'Esquema curto', value: '0,5 mg/kg/dia por 7 dias' },
          { label: 'Esquema longo', value: '0,25 mg/kg/dia por 14 dias' },
          { label: '5–9 kg (7 dias / 14 dias)', value: '1 comprimido no 1º dia, depois 1/2 / 1/4 comprimido' },
          { label: '10–14 kg', value: '1 comprimido por 7 dias / 1/2 por 14 dias' },
          { label: '15–24 kg', value: '2 comprimidos por 7 dias / 1 por 14 dias' },
          { label: '25–34 kg', value: '3 por 7 dias / 1 e 1/2 por 14 dias' },
          { label: '35–49 kg', value: '4 por 7 dias / 2 por 14 dias' },
          { label: '> 50 kg', value: '4 por 7 dias / 2 por 14 dias' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'P. ovale ou P. vivax — esquema curto', value: '30 mg/dia por 7 dias (associada à cloroquina)' },
          { label: 'P. ovale ou P. vivax — esquema longo', value: '15 mg/dia por 14 dias' },
          { label: 'Infecção mista com P. falciparum', value: 'Iniciar arteméter+lumefantrina ou artesunato+mefloquina por 3 dias; depois primaquina por 7 dias' },
          { label: 'Deficiência de G6PD', value: '0,75 mg/kg/dose, máx 45 mg/dose semanal, por 8 semanas' },
          { label: 'Gametocitocida / bloqueio da transmissão', value: '0,75 mg/kg, dose única, no 2º dia de arteméter ou artesunato' },
        ],
      },
    ],
    renalAdjustment: [{ label: 'Insuficiência renal', value: 'Não exige ajuste' }],
    sideEffects: [
      'Cefaleia', 'Arritmia', 'Hipertensão', 'Vômito', 'Dor abdominal', 'Diarreia',
      'Fraqueza', 'Mal-estar', 'Coriza',
      'Meta-hemoglobinemia', 'Hemólise grave na deficiência de G6PD',
      'Interromper se aparecer icterícia',
    ],
    contraindications: [
      'Gestantes', 'Crianças < 6 meses', 'Risco de hemólise', 'Granulocitopenia',
      'Lúpus', 'Artrite reumatoide ativa',
    ],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
  {
    id: 'quinina',
    name: 'Quinina',
    category: 'antimalaricos',
    observations: '4-aminoquinolina. Primeira escolha para malária não complicada por P. falciparum. Esquizonticida sanguíneo. Gametocida para P. vivax, mas não para P. falciparum.',
    brands: ['Sulfato de quinina — comprimido 500 mg (600 mg de sulfato = 500 mg de base)'],
    presentations: [{ label: 'Comprimido 500 mg' }],
    doses: [
      {
        group: 'Crianças — Malária resistente a cloroquina',
        items: [
          { label: 'Oral', value: '8 mg/kg/dose, 3×/dia, associada à clindamicina ou doxiciclina' },
        ],
      },
      {
        group: 'Adultos',
        items: [
          { label: 'Oral — malária resistente', value: '500 mg/dose, 3×/dia, associada à clindamicina, doxiciclina ou tetraciclina' },
          { label: 'EV', value: '600 mg/dose ou 10 mg/kg/dose. Correr em 4 h. Repetir a cada 8 h (meia dose em infusão contínua de 0,02 mg/kg/min por 72 h)' },
          { label: 'Malária grave por falciparum', value: 'EV: 20 mg/kg/dia em 3 doses + clindamicina' },
          { label: 'Malária grave em < 6 meses e gestantes', value: 'Ataque EV: 20 mg/kg; depois a cada 8 h, 4 h por infusão. Diluir a 2 mg/mL em SGI 5%. Passar para oral: 10 mg/kg/dose 3×/dia por 7 dias. Associar clindamicina 20 mg/kg/dia ÷ 4 por 7 dias.' },
        ],
      },
    ],
    preparation: 'Diluir em 10 mL/kg de SGI. Correr em 4 horas. Após reconstituir, repetir a 5 mL/h.',
    renalAdjustment: [
      { label: 'ClCr 10–50 mL/min', value: '1 dose a cada 12 h' },
      { label: 'ClCr < 10 mL/min', value: '1 dose a cada 24 h' },
    ],
    sideEffects: [
      'Tontura', 'Zumbido', 'Visão embaçada', 'Tremores', 'Cefaleia', 'Febre',
      'Inquietação', 'Delírio', 'Síncope', 'Excitação', 'Má-escuta', 'Neuropatia periférica',
      'Cinchonismo', 'Perda da audição', 'Vertigem',
      'Cardiotoxicidade por via venosa', 'Arritmia', 'Angina', 'BAV',
      'Angioedema', 'Erupção cutânea', 'Mialgia',
      'Náusea', 'Vômitos', 'Diarreia', 'Boca amarga', 'Dor abdominal',
      'Hipoglicemia por hiperinsulinemia',
      'Hematúria', 'Anemia', 'Púrpura', 'Plaquetopenia', 'Protrombina reduzida', 'Agranulocitose',
    ],
    contraindications: [],
    sensitivity: { susceptible: [], resistant: [], warning: '' },
  },
];